
var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.Uf||(f.Uf=0);f.Uf++;
(function(a){function b(m,t,r,w){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(m,function(x,A){x?w(x):r(A.buffer)});else{var v=new XMLHttpRequest;v.open("GET",m,!0);v.responseType="arraybuffer";v.onprogress=function(x){var A=t;x.total&&(A=x.total);if(x.loaded){v.cf?f.pf[m].loaded=x.loaded:(v.cf=!0,f.pf||(f.pf={}),f.pf[m]={loaded:x.loaded,total:A});var D=A=x=0,H;for(H in f.pf){var da=f.pf[H];x+=da.total;A+=da.loaded;
D++}x=Math.ceil(x*f.Uf/D);f.setStatus&&f.setStatus("Downloading data... ("+A+"/"+x+")")}else!f.pf&&f.setStatus&&f.setStatus("Downloading data...")};v.onerror=function(){throw Error("NetworkError for: "+m);};v.onload=function(){if(200==v.status||304==v.status||206==v.status||0==v.status&&v.response)r(v.response);else throw Error(v.statusText+" : "+v.responseURL);};v.send(null)}}function c(m){console.error("package error:",m)}function d(){function m(v,x,A){this.start=v;this.end=x;this.audio=A}function t(v){if(!v)throw"Loading data file failed."+
Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);m.prototype.Cg=v;v=a.files;for(var x=0;x<v.length;++x)m.prototype.cf[v[x].filename].onload();f.removeRunDependency("datafile_gate.data")}f.FS_createPath("/","assets",!0,!0);f.FS_createPath("/assets","themes",!0,!0);f.FS_createPath("/assets","shaders",!0,!0);f.FS_createPath("/assets/shaders","renderer",!0,!0);f.FS_createPath("/assets","textures",!0,!0);m.prototype={cf:{},open:function(v,
x){this.name=x;this.cf[x]=this;f.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Qf(this.Cg.subarray(this.start,this.end))},Qf:function(v){f.FS_createDataFile(this.name,null,v,!0,!0,!0);f.removeRunDependency("fp "+this.name);this.cf[this.name]=null}};for(var r=a.files,w=0;w<r.length;++w)(new m(r[w].start,r[w].end,r[w].audio||0)).open("GET",r[w].filename);f.addRunDependency("datafile_gate.data");f.ug||(f.ug={});f.ug["gate.data"]={dh:!1};l?(t(l),l=null):k=t}"object"===typeof window?
window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof f.locateFilePackage||f.locateFile||(f.locateFile=f.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=f.locateFile?f.locateFile("gate.data",""):"gate.data",g=a.remote_package_size,k=null,l=f.getPreloadedPackage?f.getPreloadedPackage(e,g):null;l||b(e,g,function(m){k?(k(m),k=null):l=m},c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/assets/themes/default.json",start:0,end:208},{filename:"/assets/shaders/Outline.glsl",start:208,end:985},{filename:"/assets/shaders/FlatColor.glsl",start:985,end:1216},{filename:"/assets/shaders/renderer/Quad.glsl",start:1216,end:3844},
{filename:"/assets/shaders/renderer/Circle.glsl",start:3844,end:4818},{filename:"/assets/textures/PixelFont_7x9_112x54.png",start:4818,end:5805}],remote_package_size:5805,package_uuid:"a0ab6506-b9dd-4e02-b876-3c962f18b7ca"});var aa={},ba;for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],ea="./this.program";function fa(a,b){throw b;}
var ha="object"===typeof window,ia="function"===typeof importScripts,ja="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,n="",ka,la,ma,na,oa;
if(ja)n=ia?require("path").dirname(n)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},la=function(a,b,c){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);na.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==
typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",function(a){throw a;}),fa=function(a,b){if(noExitRuntime||0<qa)throw process.exitCode=a,b;b instanceof pa||h("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ha||ia)ia?n=self.location.href:"undefined"!==typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?
n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ia&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var p=f.print||console.log.bind(console),h=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(ea=f.thisProgram);f.quit&&(fa=f.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,h(a))}var sa,ta;f.wasmBinary&&(ta=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&ua("no native wasm support detected");
function va(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":xa=[b>>>0,(y=b,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];u[a>>2]=xa[0];u[a+4>>2]=xa[1];break;case "float":z[a>>2]=b;break;case "double":ya[a>>3]=b;break;default:ua("invalid type for setValue: "+c)}}var za,Aa=!1,Ca;
function assert(a,b){a||ua("Assertion failed: "+b)}function Da(a){var b=Ea(a.length);a.subarray||a.slice?B.set(a,b):B.set(new Uint8Array(a),b);return b}var Fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ga(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?Ga(B,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ia(a){var b=Ha(a)+1,c=Ja(b);E(a,q,c,b);return c}var Ka,q,B,wa,La,u,F,z,ya;
function Ma(){var a=za.buffer;Ka=a;f.HEAP8=q=new Int8Array(a);f.HEAP16=wa=new Int16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=La=new Uint16Array(a);f.HEAPU32=F=new Uint32Array(a);f.HEAPF32=z=new Float32Array(a);f.HEAPF64=ya=new Float64Array(a)}var Na,Oa=[],Pa=[],Qa=[],Ra=[],Sa=!1,qa=0;function Ta(){var a=f.preRun.shift();Oa.unshift(a)}var Ua=0,Va=null,Wa=null;function Xa(){Ua++;f.monitorRunDependencies&&f.monitorRunDependencies(Ua)}
function Ya(){Ua--;f.monitorRunDependencies&&f.monitorRunDependencies(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}f.preloadedImages={};f.preloadedAudios={};function ua(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";h(a);Aa=!0;Ca=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Za(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="gate.wasm";
if(!Za()){var $a=G;G=f.locateFile?f.locateFile($a,n):n+$a}function ab(){var a=G;try{if(a==G&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){ua(b)}}
function bb(){if(!ta&&(ha||ia)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return ab()});if(la)return new Promise(function(a,b){la(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return ab()})}var y,xa;
function cb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Jg;"number"===typeof c?void 0===b.Cf?I(c)():I(c)(b.Cf):c(void 0===b.Cf?null:b.Cf)}}}function I(a){return Na.get(a)}function db(a){a instanceof pa||"unwind"==a||fa(1,a)}function eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ja)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){ua("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],rf:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.rf.flush(a.tty)},flush:function(a){a.tty.rf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.rf.mg)throw new J(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.rf.mg(a.tty)}catch(l){throw new J(29);}if(void 0===k&&0===e)throw new J(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.rf.$f)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.rf.$f(a.tty,b[c+e])}catch(g){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},pb={mg:function(a){if(!a.input.length){var b=null;if(ja){var c=Buffer.alloc(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},$f:function(a,b){null===b||10===b?(p(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(p(Ga(a.output,0)),a.output=[])}},qb={$f:function(a,b){null===b||10===b?(h(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ga(a.output,0)),a.output=[])}},K={ef:null,ff:function(){return K.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.ef||(K.ef={dir:{node:{kf:K.Ye.kf,bf:K.Ye.bf,lookup:K.Ye.lookup,Jf:K.Ye.Jf,rename:K.Ye.rename,unlink:K.Ye.unlink,rmdir:K.Ye.rmdir,readdir:K.Ye.readdir,symlink:K.Ye.symlink},stream:{mf:K.Ze.mf}},file:{node:{kf:K.Ye.kf,bf:K.Ye.bf},stream:{mf:K.Ze.mf,read:K.Ze.read,write:K.Ze.write,eg:K.Ze.eg,qg:K.Ze.qg,sg:K.Ze.sg}},link:{node:{kf:K.Ye.kf,bf:K.Ye.bf,readlink:K.Ye.readlink},stream:{}},hg:{node:{kf:K.Ye.kf,bf:K.Ye.bf},
stream:rb}});c=sb(a,b,c,d);16384===(c.mode&61440)?(c.Ye=K.ef.dir.node,c.Ze=K.ef.dir.stream,c.Xe={}):32768===(c.mode&61440)?(c.Ye=K.ef.file.node,c.Ze=K.ef.file.stream,c.$e=0,c.Xe=null):40960===(c.mode&61440)?(c.Ye=K.ef.link.node,c.Ze=K.ef.link.stream):8192===(c.mode&61440)&&(c.Ye=K.ef.hg.node,c.Ze=K.ef.hg.stream);c.timestamp=Date.now();a&&(a.Xe[b]=c,a.timestamp=c.timestamp);return c},eh:function(a){return a.Xe?a.Xe.subarray?a.Xe.subarray(0,a.$e):new Uint8Array(a.Xe):new Uint8Array(0)},ig:function(a,
b){var c=a.Xe?a.Xe.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Xe,a.Xe=new Uint8Array(b),0<a.$e&&a.Xe.set(c.subarray(0,a.$e),0))},Sg:function(a,b){if(a.$e!=b)if(0==b)a.Xe=null,a.$e=0;else{var c=a.Xe;a.Xe=new Uint8Array(b);c&&a.Xe.set(c.subarray(0,Math.min(b,a.$e)));a.$e=b}},Ye:{kf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.$e:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Fg=4096;b.blocks=Math.ceil(b.size/b.Fg);return b},bf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Sg(a,b.size)},lookup:function(){throw tb[44];},Jf:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ub(b,c)}catch(g){}if(d)for(var e in d.Xe)throw new J(55);
}delete a.parent.Xe[a.name];a.parent.timestamp=Date.now();a.name=c;b.Xe[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Xe[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ub(a,b),d;for(d in c.Xe)throw new J(55);delete a.Xe[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Xe)a.Xe.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},Ze:{read:function(a,b,c,d,e){var g=a.node.Xe;if(e>=a.node.$e)return 0;a=Math.min(a.node.$e-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===q.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Xe||a.Xe.subarray)){if(g)return a.Xe=b.subarray(c,c+d),a.$e=d;if(0===a.$e&&0===e)return a.Xe=b.slice(c,c+d),a.$e=d;if(e+d<=a.$e)return a.Xe.set(b.subarray(c,c+d),e),d}K.ig(a,e+
d);if(a.Xe.subarray&&b.subarray)a.Xe.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Xe[e+g]=b[c+g];a.$e=Math.max(a.$e,e+d);return d},mf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.$e);if(0>b)throw new J(28);return b},eg:function(a,b,c){K.ig(a.node,b+c);a.node.$e=Math.max(a.node.$e,b+c)},qg:function(a,b,c,d,e,g){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.Xe;if(g&2||a.buffer!==Ka){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;ua();c=void 0;if(!c)throw new J(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{yf:c,Xg:d}},sg:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.Ze.write(a,b,0,d,c,!1);return 0}}};function vb(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ya(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Xa(d)}
var wb=null,xb={},yb=[],zb=1,Ab=null,Bb=!0,J=null,tb={};
function Cb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={jg:!0,ag:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ag)throw new J(32);a=eb(a.split("/").filter(function(k){return!!k}),!1);var e=wb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=ub(e,a[d]);c=fb(c+"/"+a[d]);e.xf&&(!g||g&&b.jg)&&(e=e.xf.root);if(!g||b.Vf)for(g=0;40960===(e.mode&61440);)if(e=Db(c),c=jb(gb(c),e),e=Cb(c,{ag:b.ag}).node,40<g++)throw new J(32);}return{path:c,node:e}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.ff.rg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length}function ub(a,b){var c;if(c=(c=Gb(a,"x"))?c:a.Ye.lookup?0:2)throw new J(c,a);for(c=Ab[Fb(a.id,b)];c;c=c.qf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ye.lookup(a,b)}
function sb(a,b,c,d){a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.qf=Ab[b];return Ab[b]=a}var Ib={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(Bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){try{return ub(a,b),20}catch(c){}return Gb(a,"wx")}
function Lb(a){var b=4096;for(a=a||0;a<=b;a++)if(!yb[a])return a;throw new J(33);}function Mb(a,b){Nb||(Nb=function(){},Nb.prototype={});var c=new Nb,d;for(d in a)c[d]=a[d];a=c;b=Lb(b);a.fd=b;return yb[b]=a}var rb={open:function(a){a.Ze=xb[a.node.rdev].Ze;a.Ze.open&&a.Ze.open(a)},mf:function(){throw new J(70);}};function mb(a,b){xb[a]={Ze:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&wb)throw new J(10);if(!c&&!d){var e=Cb(b,{jg:!1});b=e.path;e=e.node;if(e.xf)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,lh:{},rg:b,Qg:[]};a=a.ff(b);a.ff=b;b.root=a;c?wb=a:e&&(e.xf=b,e.ff&&e.ff.Qg.push(b))}function Pb(a,b,c){var d=Cb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Kb(d,a);if(e)throw new J(e);if(!d.Ye.Jf)throw new J(63);return d.Ye.Jf(d,a,b,c)}function L(a){return Pb(a,16895,0)}
function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Pb(a,b|8192,c)}function Rb(a,b){if(!jb(a))throw new J(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new J(44);b=hb(b);var d=Kb(c,b);if(d)throw new J(d);if(!c.Ye.symlink)throw new J(63);c.Ye.symlink(c,b,a)}
function Sb(a){var b=Cb(a,{parent:!0}).node,c=hb(a);a=ub(b,c);a:{try{var d=ub(b,c)}catch(g){d=g.jf;break a}var e=Gb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new J(d);if(!b.Ye.unlink)throw new J(63);if(a.xf)throw new J(10);b.Ye.unlink(b,c);b=Fb(a.parent.id,a.name);if(Ab[b]===a)Ab[b]=a.qf;else for(b=Ab[b];b;){if(b.qf===a){b.qf=a.qf;break}b=b.qf}}function Db(a){a=Cb(a).node;if(!a)throw new J(44);if(!a.Ye.readlink)throw new J(28);return jb(Eb(a.parent),a.Ye.readlink(a))}
function Tb(a,b){a="string"===typeof a?Cb(a,{Vf:!0}).node:a;if(!a.Ye.bf)throw new J(63);a.Ye.bf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ub(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Ib[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=fb(a);try{g=Cb(a,{Vf:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new J(20);}else g=Pb(a,c,0),e=!0;if(!g)throw new J(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new J(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Jb(b)||b&512)?31:Gb(g,Jb(b)):44))throw new J(c);if(b&512){c=g;c="string"===typeof c?Cb(c,{Vf:!0}).node:c;if(!c.Ye.bf)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Gb(c,"w"))throw new J(e);c.Ye.bf(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Mb({node:g,path:Eb(g),id:g.id,flags:b,mode:g.mode,seekable:!0,position:0,Ze:g.Ze,Ye:g.Ye,Ug:[],error:!1},d);d.Ze.open&&d.Ze.open(d);!f.logReadFiles||b&1||(Vb||(Vb={}),
a in Vb||(Vb[a]=1));return d}function Wb(a){if(null===a.fd)throw new J(8);a.Xf&&(a.Xf=null);try{a.Ze.close&&a.Ze.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null}function Xb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.Ze.mf)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.Ze.mf(a,b,c);a.Ug=[]}
function Yb(a,b,c,d,e,g){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.Ze.write)throw new J(28);a.seekable&&a.flags&1024&&Xb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new J(70);b=a.Ze.write(a,b,c,d,e,g);k||(a.position+=b);return b}
function Zb(){J||(J=function(a,b){this.node=b;this.Tg=function(c){this.jf=c};this.Tg(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){tb[a]=new J(a);tb[a].stack="<generic error, no stack>"}))}var $b;function ac(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function bc(a,b){a="string"===typeof a?a:Eb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=fb(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}
function cc(a,b,c,d){a=fb(("string"===typeof a?a:Eb(a))+"/"+b);c=ac(c,d);return Pb(a,(void 0!==c?c:438)&4095|32768,0)}function dc(a,b,c,d,e,g){a=b?fb(("string"===typeof a?a:Eb(a))+"/"+b):a;d=ac(d,e);e=Pb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Tb(e,d|146);a=Ub(e,577);Yb(a,c,0,c.length,0,g);Wb(a);Tb(e,d)}return e}
function M(a,b,c,d){a=fb(("string"===typeof a?a:Eb(a))+"/"+b);b=ac(!!c,!!d);M.og||(M.og=64);var e=M.og++<<8|0;mb(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,l,m){for(var t=0,r=0;r<m;r++){try{var w=c()}catch(v){throw new J(29);}if(void 0===w&&0===t)throw new J(6);if(null===w||void 0===w)break;t++;k[l+r]=w}t&&(g.node.timestamp=Date.now());return t},write:function(g,k,l,m){for(var t=0;t<m;t++)try{d(k[l+t])}catch(r){throw new J(29);}m&&(g.node.timestamp=
Date.now());return t}});return Qb(a,b,e)}function ec(a){if(!(a.Ng||a.Og||a.link||a.Xe)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.Xe=ob(ka(a.url),!0),a.$e=a.Xe.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function fc(a,b,c,d,e){function g(){this.Yf=!1;this.cf=[]}g.prototype.get=function(r){if(!(r>this.length-1||0>r)){var w=r%this.chunkSize;return this.ng(r/this.chunkSize|0)[w]}};g.prototype.Qf=function(r){this.ng=r};g.prototype.fg=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var w=Number(r.getResponseHeader("Content-length")),v,x=(v=r.getResponseHeader("Accept-Ranges"))&&
"bytes"===v;r=(v=r.getResponseHeader("Content-Encoding"))&&"gzip"===v;var A=1048576;x||(A=w);var D=this;D.Qf(function(H){var da=H*A,Ba=(H+1)*A-1;Ba=Math.min(Ba,w-1);if("undefined"===typeof D.cf[H]){var me=D.cf;if(da>Ba)throw Error("invalid range ("+da+", "+Ba+") or no bytes requested!");if(Ba>w-1)throw Error("only "+w+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);w!==A&&N.setRequestHeader("Range","bytes="+da+"-"+Ba);"undefined"!=typeof Uint8Array&&(N.responseType=
"arraybuffer");N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);if(!(200<=N.status&&300>N.status||304===N.status))throw Error("Couldn't load "+c+". Status: "+N.status);da=void 0!==N.response?new Uint8Array(N.response||[]):ob(N.responseText||"",!0);me[H]=da}if("undefined"===typeof D.cf[H])throw Error("doXHR failed!");return D.cf[H]});if(r||!w)A=w=1,A=w=this.ng(0).length,p("LazyFiles on gzip forces download of the whole file when length is accessed");this.Eg=
w;this.Dg=A;this.Yf=!0};if("undefined"!==typeof XMLHttpRequest){if(!ia)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Yf||this.fg();return this.Eg}},chunkSize:{get:function(){this.Yf||this.fg();return this.Dg}}});var l=void 0}else l=c,k=void 0;var m=cc(a,b,d,e);k?m.Xe=k:l&&(m.Xe=null,m.url=l);Object.defineProperties(m,{$e:{get:function(){return this.Xe.length}}});
var t={};Object.keys(m.Ze).forEach(function(r){var w=m.Ze[r];t[r]=function(){ec(m);return w.apply(null,arguments)}});t.read=function(r,w,v,x,A){ec(m);r=r.node.Xe;if(A>=r.length)return 0;x=Math.min(r.length-A,x);if(r.slice)for(var D=0;D<x;D++)w[v+D]=r[A+D];else for(D=0;D<x;D++)w[v+D]=r.get(A+D);return x};m.Ze=t;return m}
function gc(a,b,c,d,e,g,k,l,m,t){function r(x){function A(H){t&&t();l||dc(a,b,H,d,e,m);g&&g();Ya(v)}var D=!1;f.preloadPlugins.forEach(function(H){!D&&H.canHandle(w)&&(H.handle(x,w,A,function(){k&&k();Ya(v)}),D=!0)});D||A(x)}hc();var w=b?jb(fb(a+"/"+b)):a,v="cp "+w;Xa(v);"string"==typeof c?vb(c,function(x){r(x)},k):r(c)}var ic={},Nb,Vb,jc=void 0;function kc(){jc+=4;return u[jc-4>>2]}function lc(a){a=yb[a];if(!a)throw new J(8);return a}
var mc=1,nc=[],oc={},O=[],pc=[],qc=[],rc=[],P=[],Q=[],sc=[],R=[],S=[],tc=[],uc=[],vc=[1,1,2,2,4,4,4,2,3,4,8],wc={},xc={};function T(a){yc||(yc=a)}function zc(a){for(var b=mc++,c=a.length;c<b;c++)a[c]=null;return b}function Ac(a){return 32-Math.clz32(0===a?0:a-1)}function Bc(a){a=Ac(a);var b=U.sf[a];if(b)return b;b=V.getParameter(34965);U.sf[a]=V.createBuffer();V.bindBuffer(34963,U.sf[a]);V.bufferData(34963,1<<a,35048);V.bindBuffer(34963,b);return U.sf[a]}
function Cc(a){Dc=!1;for(var b=0;b<U.pg;++b){var c=U.gf[b];if(c.uf&&c.enabled){Dc=!0;var d=c.Mf;d=0<d?a*d:c.size*vc[c.type-5120]*a;var e=Ac(d);var g=U.tf[e],k=U.lf[e];U.lf[e]=U.lf[e]+1&63;var l=g[k];l?e=l:(l=V.getParameter(34964),g[k]=V.createBuffer(),V.bindBuffer(34962,g[k]),V.bufferData(34962,1<<e,35048),V.bindBuffer(34962,l),e=g[k]);V.bindBuffer(34962,e);V.bufferSubData(34962,0,B.subarray(c.yf,c.yf+d));c.cg.call(V,b,c.size,c.type,c.Zf,c.Mf,0)}}}function Ec(){Dc&&V.bindBuffer(34962,nc[V.vf])}
function Fc(a,b){a.lg||(a.lg=a.getContext,a.getContext=function(d,e){e=a.lg(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Gc(c,b):0}
function Gc(a,b){var c=zc(sc),d={fh:c,attributes:b,version:b.Pg,Bf:a};a.canvas&&(a.canvas.Wg=d);sc[c]=d;("undefined"===typeof b.Ig||b.Ig)&&Hc(d);d.pg=d.Bf.getParameter(34921);d.gf=[];for(a=0;a<d.pg;a++)d.gf[a]={enabled:!1,uf:!1,size:0,type:0,Zf:0,Mf:0,yf:0,cg:null};a=Ac(2097152);d.lf=[];d.Nf=[];d.lf.length=d.Nf.length=a+1;d.tf=[];d.zf=[];d.tf.length=d.zf.length=a+1;d.sf=[];d.sf.length=a+1;for(b=0;b<=a;++b){d.sf[b]=null;d.lf[b]=d.Nf[b]=0;d.tf[b]=[];d.zf[b]=[];var e=d.tf[b],g=d.zf[b];e.length=g.length=
64;for(var k=0;64>k;++k)e[k]=g[k]=null}return c}
function Hc(a){a||(a=U);if(!a.Lg){a.Lg=!0;var b=a.Bf;b.ah=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.gh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.af=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.af)b.af=b.getExtension("EXT_disjoint_timer_query");b.jh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Ic={},yc,U,Dc,Jc=[];function Kc(a){switch(a){case 34962:a=34964;break;case 34963:a=34965;break;case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=V.getParameter(a))?a.name|0:0}function Lc(a){switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}}
function Mc(a,b,c,d){for(var e=0;e<a;e++){var g=V[c](),k=g&&zc(d);g?(g.name=k,d[k]=g):T(1282);u[b+4*e>>2]=k}}function Nc(a,b,c,d,e,g,k,l){b=O[b];if(a=V[a](b,c))d=l&&E(a.name,B,l,d),e&&(u[e>>2]=d),g&&(u[g>>2]=a.size),k&&(u[k>>2]=a.type)}function Oc(a,b){F[a>>2]=b;F[a+4>>2]=(b-F[a>>2])/4294967296}
function Pc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){T(1282);return}d=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>U.version){T(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){T(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:T(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Oc(b,d);break;case 0:u[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else T(1281)}
function Qc(a,b,c,d){if(c){b=V.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T(1280);return}break;default:T(1280);return}switch(d){case 1:Oc(c,a);break;case 0:u[c>>2]=a;break;case 2:z[c>>2]=a;break;case 4:q[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T(1281)}
function Rc(a){var b=Ha(a)+1,c=Ea(b);E(a,B,c,b);return c}function Sc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Tc(a){var b=a.Af,c=a.Ag,d;if(!b)for(a.Af=b={},a.zg={},d=0;d<V.getProgramParameter(a,35718);++d){var e=V.getActiveUniform(a,d);var g=e.name;e=e.size;var k=Sc(g);k=0<k?g.slice(0,k):g;var l=a.bg;a.bg+=e;c[k]=[e,l];for(g=0;g<e;++g)b[l]=g,a.zg[l++]=k}}
function W(a){var b=V.Hg;if(b){var c=b.Af[a];"number"===typeof c&&(b.Af[a]=c=V.getUniformLocation(b,b.zg[a]+(0<c?"["+c+"]":"")));return c}T(1282)}function Uc(a,b,c,d){if(c)if(a=O[a],Tc(a),a=V.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else T(1281)}
function Vc(a,b,c,d){if(c)if(U.gf[a].enabled&&h("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=V.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else T(1281)}
function Wc(a){a-=5120;return 0==a?q:1==a?B:2==a?wa:4==a?u:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?F:La}function Xc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Yc(a){if(!Sa&&!Aa)try{a()}catch(b){db(b)}}function Zc(a){setTimeout(function(){Yc(a)},1E4)}var $c=!1,ad=null,bd=0,cd=null,dd=0,ed=0,fd=0,gd=0,hd=[],jd={},kd,ld,md,nd=!1,od=!1,pd=[];
function hc(){function a(){od=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!qd){qd=!0;try{rd=!0}catch(c){rd=!1,p("warning: no blob constructor, cannot create blobs with mimetypes")}sd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rd?null:p("warning: no BlobBuilder");td="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.tg||"undefined"!==typeof td||(p("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.tg=!0);f.preloadPlugins.push({canHandle:function(c){return!f.tg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=null;if(rd)try{k=new Blob([c],{type:ud(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:ud(d)}))}catch(t){ra("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new sd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var l=td.createObjectURL(k),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=m.width;t.height=m.height;t.getContext("2d").drawImage(m,0,0);f.preloadedImages[d]=t;td.revokeObjectURL(l);e&&e(c)};m.onerror=function(){p("Image "+l+" could not be decoded");g&&g()};m.src=l}});f.preloadPlugins.push({canHandle:function(c){return!f.kh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function k(w){m||(m=!0,f.preloadedAudios[d]=w,e&&e(c))}function l(){m||(m=!0,f.preloadedAudios[d]=new Audio,g&&g())}var m=!1;if(rd){try{var t=new Blob([c],{type:ud(d)})}catch(w){return l()}t=td.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!m){p("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var w="",v=0,x=0,A=0;A<c.length;A++)for(v=
v<<8|c[A],x+=8;6<=x;){var D=v>>x-6&63;x-=6;w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==x?(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],w+="=="):4==x&&(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],w+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+w;k(r)}};r.src=t;Zc(function(){k(r)})}else return l()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
function(c){!od&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function vd(a,b,c,d){if(b&&f.nf&&a==f.canvas)return f.nf;var e;if(b){var g={antialias:!1,alpha:!1,Pg:2};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof Ic&&(e=Fc(a,g)))var l=sc[e].Bf}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof V,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.nf=l,b&&(U=sc[e],f.nf=V=U&&U.Bf),f.mh=b,pd.forEach(function(m){m()}),hc());return l}var wd=!1,xd=void 0,yd=void 0;
function zd(a,b){function c(){nd=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ad,xd&&d.requestPointerLock(),nd=!0,yd?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=F[SDL.screen>>2]|8388608),Bd(f.canvas),Cd()):Bd(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),yd?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=F[SDL.screen>>2]&
-8388609),Bd(f.canvas),Cd()):Bd(d));if(f.onFullScreen)f.onFullScreen(nd);if(f.onFullscreen)f.onFullscreen(nd)}xd=a;yd=b;"undefined"===typeof xd&&(xd=!0);"undefined"===typeof yd&&(yd=!1);var d=f.canvas;wd||(wd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Ad(){if(!nd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Dd=0;function Ed(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Dd)Dd=b+1E3/60;else for(;b+2>=Dd;)Dd+=1E3/60;setTimeout(a,Math.max(Dd-b,0))}}
function ud(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Fd=0,Gd=0,Hd=0,Id=0;
function Jd(a){if(od)"mousemove"!=a.type&&"mozMovementX"in a?Hd=Id=0:(Hd=a.movementX||a.mozMovementX||a.webkitMovementX||0,Id=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Fd=SDL.hh+Hd,Gd=SDL.ih+Id):(Fd+=Hd,Gd+=Id);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Hd=e-Fd,Id=a-Gd,Fd=e,Gd=a)}}var Kd=[];function Cd(){var a=f.canvas;Kd.forEach(function(b){b(a.width,a.height)})}function Ld(a,b,c){Bd(f.canvas,a,b);c||Cd()}
function Bd(a,b,c){b&&c?(a.Vg=b,a.Kg=c):(b=a.Vg,c=a.Kg);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}yd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qd,rd,sd,td;
function Md(a,b){ed=a;fd=b;if(cd)if($c||($c=!0),0==a)ad=function(){var d=Math.max(0,ld+b-Nd())|0;setTimeout(md,d)};else if(1==a)ad=function(){Ed(md)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ia?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}ad=function(){setImmediate(md)}}}var Nd;Nd=ja?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function Od(a,b,c,d,e){function g(){if(k<bd){if(!(noExitRuntime||0<qa))try{Pd(Ca)}catch(l){db(l)}return!1}return!0}assert(!cd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");cd=a;dd=d;var k=bd;$c=!1;md=function(){if(!Aa)if(0<hd.length){var l=Date.now(),m=hd.shift();m.Jg(m.Cf);if(kd){var t=kd,r=0==t%1?t-1:Math.floor(t);kd=m.$g?r:(8*t+(r+.5))/9}p('main loop blocker "'+
m.name+'" took '+(Date.now()-l)+" ms");f.setStatus&&(l=f.statusMessage||"Please wait...",m=kd,t=jd.bh,m?m<t?f.setStatus(l+" ("+(t-m)+"/"+t+")"):f.setStatus(l):f.setStatus(""));g()&&setTimeout(md,0)}else if(g())if(gd=gd+1|0,1==ed&&1<fd&&0!=gd%fd)ad();else{0==ed&&(ld=Nd());if(U)for(l=U.tf,U.tf=U.zf,U.zf=l,l=U.lf,U.lf=U.Nf,U.Nf=l,l=Ac(2097152),m=0;m<=l;++m)U.lf[m]=0;Aa||f.preMainLoop&&!1===f.preMainLoop()||(Yc(a),f.postMainLoop&&f.postMainLoop());g()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Rg&&
SDL.audio.Rg(),ad())}};e||(b&&0<b?Md(0,1E3/b):Md(1,1),ad());if(c)throw"unwind";}function Qd(a,b,c,d){this.id=a;this.y=this.x=0;this.Wf=!1;this.yg=this.xg=0;this.width=b;this.height=c;this.wg=b;this.vg=c;this.title=d;this.attributes=Rd;this.buttons=0;this.keys=[];this.Sf=[];this.Bg=this.gg=this.Ff=this.Tf=this.Lf=this.Df=this.Ef=this.Kf=this.kg=this.Of=this.Pf=this.title=null}function X(a){return 0>=a||!Y?null:Y[a-1]}
var Sd=null,Z=null,Y=null,Td=null,Ud=null,Rd=null,Vd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Wd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Xd(){var a=Z,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Yd(a){Z&&Z.gg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||I(Z.gg)(Z.id,a))}function Zd(a,b){if(Z){var c=Wd(a);if(-1!=c){var d=b&&Z.keys[c];Z.keys[c]=b;Z.Sf[a]=b;Z.Ff&&(d&&(b=2),I(Z.Ff)(Z.id,c,a,b,Xd()))}}}
function $d(){ae()}function be(){ae()}function ce(a){Zd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function de(a){Zd(a.keyCode,0)}function ee(){if(Z)for(var a=0;a<Z.Sf.length;++a)Z.Sf[a]&&Zd(a,0)}function fe(a){Z&&(Jd(a),a.target==f.canvas&&Z.Ef&&I(Z.Ef)(Z.id,Fd,Gd))}function ge(a){Z&&a.target==f.canvas&&Z.Df&&I(Z.Df)(Z.id,1)}function he(a){Z&&a.target==f.canvas&&Z.Df&&I(Z.Df)(Z.id,0)}
function ie(a,b){if(Z&&(Jd(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Z.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Z.buttons&=~(1<<c);Z.Kf&&I(Z.Kf)(Z.id,c,b,Xd())}}function je(a){Z&&ie(a,1)}function ke(a){Z&&ie(a,0)}
function le(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Z&&Z.Lf&&a.target==f.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;I(Z.Lf)(Z.id,b,c);a.preventDefault()}}
function ne(){Z&&Z.Pf&&Yc(function(){I(Z.Pf)(Z.id,Z.width,Z.height)})}function oe(){Z&&Z.kg&&Yc(function(){I(Z.kg)(Z.id,Z.width,Z.height)})}var pe={},qe=null,re=null;
function ae(){if(gd!==re||!gd){qe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;re=gd;for(var a=0;a<qe.length;++a){var b=qe[a];if(b){pe[a]||(p("glfw joystick connected:",a),pe[a]={id:Da(ob(b.id)),Zg:b.buttons.length,Yg:b.axes.length,buttons:Da(Array(b.buttons.length)),axes:Da(Array(4*b.axes.length))});for(var c=pe[a],d=0;d<b.buttons.length;++d)va(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)va(c.axes+4*d,b.axes[d],
"float")}else pe[a]&&(p("glfw joystick disconnected",a),se(pe[a].id),se(pe[a].buttons),se(pe[a].axes),delete pe[a])}}}
function te(a){function b(l){var m="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(w){if(2!=t.readyState)++g,p("failed to read dropped file: "+l.name+": "+t.error);else{var v=new Uint8Array(w.target.result);var x=x||{};x.flags=x.flags||577;w=Ub(m,x.flags,x.mode);if("string"===typeof v){var A=new Uint8Array(Ha(v)+1);v=E(v,A,0,A.length);Yb(w,A,0,v,void 0,x.Gg)}else if(ArrayBuffer.isView(v))Yb(w,v,0,v.byteLength,void 0,x.Gg);else throw Error("Unsupported data type");
Wb(w);if(++g===e){I(Z.Tf)(Z.id,e,c);for(x=0;x<d.length;++x)se(d[x]);se(c)}}};t.readAsArrayBuffer(l);var r=Da(ob(m));d.push(r);va(c+4*k,r,"i8*")}if(Z&&Z.Tf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Da(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,g=0;bc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function ue(a){if(Z&&Z.Tf)return a.preventDefault(),!1}
function Hb(a,b,c,d){a||(a=this);this.parent=a;this.ff=a.ff;this.xf=null;this.id=zb++;this.name=b;this.mode=c;this.Ye={};this.Ze={};this.rdev=d}Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Og:{get:function(){return 16384===(this.mode&61440)}},Ng:{get:function(){return 8192===(this.mode&61440)}}});Zb();
Ab=Array(4096);Ob(K,"/");L("/tmp");L("/home");L("/home/web_user");(function(){L("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Qb("/dev/null",259);lb(1280,pb);lb(1536,qb);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);var a=ib();M("/dev","random",a);M("/dev","urandom",a);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Ob({ff:function(){var b=sb(a,"fd",16895,73);b.Ye={lookup:function(c,d){var e=yb[+d];if(!e)throw new J(8);c={parent:null,ff:{rg:"fake"},Ye:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();f.FS_createPath=bc;f.FS_createDataFile=dc;f.FS_createPreloadedFile=gc;f.FS_createLazyFile=fc;f.FS_createDevice=M;f.FS_unlink=Sb;for(var V,ve=0;32>ve;++ve)Jc.push(Array(ve));
f.requestFullscreen=function(a,b){zd(a,b)};f.requestAnimationFrame=function(a){Ed(a)};f.setCanvasSize=function(a,b,c){Ld(a,b,c)};f.pauseMainLoop=function(){ad=null;bd++};f.resumeMainLoop=function(){bd++;var a=ed,b=fd,c=cd;cd=null;Od(c,0,!1,dd,!0);Md(a,b);ad()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return vd(a,b,c,d)};
function ob(a,b){var c=Array(Ha(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var xe={f:function(a,b,c){jc=c;try{var d=lc(a);switch(b){case 0:var e=kc();return 0>e?-28:Ub(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=kc(),d.flags|=e,0;case 5:return e=kc(),wa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return u[we()>>2]=28,-1;default:return-28}}catch(g){if("undefined"===typeof ic||!(g instanceof J))throw g;return-g.jf}},Ga:function(a,b,c){jc=c;try{var d=lc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=kc();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=kc();if(!d.Ze.Mg)throw new J(59);return d.Ze.Mg(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:ua("bad ioctl syscall "+b)}}catch(g){if("undefined"===typeof ic||!(g instanceof J))throw g;return-g.jf}},Ha:function(a,b,c){jc=c;try{var d=C(a),e=c?kc():0;return Ub(d,b,e).fd}catch(g){if("undefined"===typeof ic||!(g instanceof J))throw g;return-g.jf}},d:function(){ua("")},
la:function(a){V.activeTexture(a)},ka:function(a,b){V.attachShader(O[a],P[b])},Ic:function(a,b){V.beginQuery(a,R[b])},Ka:function(a,b){V.af.beginQueryEXT(a,R[b])},jc:function(a){V.beginTransformFeedback(a)},ja:function(a,b,c){V.bindAttribLocation(O[a],b,C(c))},ia:function(a,b){34962==a?V.vf=b:34963==a&&(V.hf=b);35051==a?V.Rf=b:35052==a&&(V.df=b);V.bindBuffer(a,nc[b])},gc:function(a,b,c){V.bindBufferBase(a,b,nc[c])},hc:function(a,b,c,d,e){V.bindBufferRange(a,b,nc[c],d,e)},ga:function(a,b){V.bindFramebuffer(a,
pc[b])},fa:function(a,b){V.bindRenderbuffer(a,qc[b])},lb:function(a,b){V.bindSampler(a,S[b])},ea:function(a,b){V.bindTexture(a,rc[b])},cb:function(a,b){V.bindTransformFeedback(a,tc[b])},oc:function(a){V.bindVertexArray(Q[a]);a=V.getParameter(34965);V.hf=a?a.name|0:0},ua:function(a){V.bindVertexArray(Q[a]);a=V.getParameter(34965);V.hf=a?a.name|0:0},da:function(a,b,c,d){V.blendColor(a,b,c,d)},ca:function(a){V.blendEquation(a)},ba:function(a,b){V.blendEquationSeparate(a,b)},aa:function(a,b){V.blendFunc(a,
b)},$:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},uc:function(a,b,c,d,e,g,k,l,m,t){V.blitFramebuffer(a,b,c,d,e,g,k,l,m,t)},_:function(a,b,c,d){c?V.bufferData(a,B,d,c,b):V.bufferData(a,b,d)},Z:function(a,b,c,d){V.bufferSubData(a,b,B,d,c)},Y:function(a){return V.checkFramebufferStatus(a)},X:function(a){V.clear(a)},Kb:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},Lb:function(a,b,c){V.clearBufferfv(a,b,z,c>>2)},Nb:function(a,b,c){V.clearBufferiv(a,b,u,c>>2)},Mb:function(a,b,c){V.clearBufferuiv(a,b,
F,c>>2)},W:function(a,b,c,d){V.clearColor(a,b,c,d)},V:function(a){V.clearDepth(a)},U:function(a){V.clearStencil(a)},vb:function(a,b,c,d){return V.clientWaitSync(uc[a],b,(c>>>0)+4294967296*d)},T:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},S:function(a){V.compileShader(P[a])},R:function(a,b,c,d,e,g,k,l){V.df?V.compressedTexImage2D(a,b,c,d,e,g,k,l):V.compressedTexImage2D(a,b,c,d,e,g,B,l,k)},Pc:function(a,b,c,d,e,g,k,l,m){V.df?V.compressedTexImage3D(a,b,c,d,e,g,k,l,m):V.compressedTexImage3D(a,b,c,
d,e,g,k,B,m,l)},Q:function(a,b,c,d,e,g,k,l,m){V.df?V.compressedTexSubImage2D(a,b,c,d,e,g,k,l,m):V.compressedTexSubImage2D(a,b,c,d,e,g,k,B,m,l)},Oc:function(a,b,c,d,e,g,k,l,m,t,r){V.df?V.compressedTexSubImage3D(a,b,c,d,e,g,k,l,m,t,r):V.compressedTexSubImage3D(a,b,c,d,e,g,k,l,m,B,r,t)},Ib:function(a,b,c,d,e){V.copyBufferSubData(a,b,c,d,e)},P:function(a,b,c,d,e,g,k,l){V.copyTexImage2D(a,b,c,d,e,g,k,l)},N:function(a,b,c,d,e,g,k,l){V.copyTexSubImage2D(a,b,c,d,e,g,k,l)},Qc:function(a,b,c,d,e,g,k,l,m){V.copyTexSubImage3D(a,
b,c,d,e,g,k,l,m)},M:function(){var a=zc(O),b=V.createProgram();b.name=a;b.If=b.Gf=b.Hf=0;b.bg=1;O[a]=b;return a},L:function(a){var b=zc(P);P[b]=V.createShader(a);return b},K:function(a){V.cullFace(a)},J:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=nc[d];e&&(V.deleteBuffer(e),e.name=0,nc[d]=null,d==V.vf&&(V.vf=0),d==V.hf&&(V.hf=0),d==V.Rf&&(V.Rf=0),d==V.df&&(V.df=0))}},I:function(a,b){for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=pc[d];e&&(V.deleteFramebuffer(e),e.name=0,pc[d]=null)}},H:function(a){if(a){var b=
O[a];b?(V.deleteProgram(b),b.name=0,O[a]=null):T(1281)}},Kc:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=R[d];e&&(V.deleteQuery(e),R[d]=null)}},fb:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=R[d];e&&(V.af.deleteQueryEXT(e),R[d]=null)}},G:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=qc[d];e&&(V.deleteRenderbuffer(e),e.name=0,qc[d]=null)}},nb:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(V.deleteSampler(e),e.name=0,S[d]=null)}},F:function(a){if(a){var b=
P[a];b?(V.deleteShader(b),P[a]=null):T(1281)}},wb:function(a){if(a){var b=uc[a];b?(V.deleteSync(b),b.name=0,uc[a]=null):T(1281)}},E:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=rc[d];e&&(V.deleteTexture(e),e.name=0,rc[d]=null)}},bb:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=tc[d];e&&(V.deleteTransformFeedback(e),e.name=0,tc[d]=null)}},nc:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];V.deleteVertexArray(Q[d]);Q[d]=null}},ta:function(a,b){for(var c=0;c<a;c++){var d=u[b+
4*c>>2];V.deleteVertexArray(Q[d]);Q[d]=null}},C:function(a){V.depthFunc(a)},B:function(a){V.depthMask(!!a)},A:function(a,b){V.depthRange(a,b)},z:function(a,b){V.detachShader(O[a],P[b])},y:function(a){V.disable(a)},x:function(a){U.gf[a].enabled=!1;V.disableVertexAttribArray(a)},w:function(a,b,c){Cc(b+c);V.drawArrays(a,b,c);Ec()},Ab:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},oa:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Ma:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Yc:function(a,
b,c,d){V.drawArraysInstanced(a,b,c,d)},Na:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Cc:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];V.drawBuffers(c)},Vc:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];V.drawBuffers(c)},pa:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];V.drawBuffers(c)},v:function(a,b,c,d){if(!V.hf){var e=1*vc[c-5120]*b;var g=Bc(e);V.bindBuffer(34963,g);V.bufferSubData(34963,0,B.subarray(d,d+e));d=0}Cc(b);V.drawElements(a,b,c,d);Ec();V.hf||
V.bindBuffer(34963,null)},zb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},na:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Ia:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Ja:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Tc:function(a,b,c,d,e,g){b=g;V.hf||(g=1*vc[e-5120]*d,c=Bc(g),V.bindBuffer(34963,c),V.bufferSubData(34963,0,B.subarray(b,b+g)),b=0);Cc(d);V.drawElements(a,d,e,b);Ec();V.hf||V.bindBuffer(34963,
null)},u:function(a){V.enable(a)},t:function(a){U.gf[a].enabled=!0;V.enableVertexAttribArray(a)},Hc:function(a){V.endQuery(a)},Ca:function(a){V.af.endQueryEXT(a)},ic:function(){V.endTransformFeedback()},yb:function(a,b){return(a=V.fenceSync(a,b))?(b=zc(uc),a.name=b,uc[b]=a,b):0},r:function(){V.finish()},q:function(){V.flush()},qc:function(a,b,c){if(Lc(a)){var d=oc[Kc(a)];d?d.dg&16?0>b||0>c||b+c>d.length?(T(1281),h("invalid range in glFlushMappedBufferRange")):V.bufferSubData(a,d.offset,B.subarray(d.wf+
b,d.wf+b+c)):(T(1282),h("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(T(1282),h("buffer was never mapped in glFlushMappedBufferRange"))}else T(1280),h("GL_INVALID_ENUM in glFlushMappedBufferRange")},p:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,qc[d])},o:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,rc[d],e)},sc:function(a,b,c,d,e){V.framebufferTextureLayer(a,b,rc[c],d,e)},n:function(a){V.frontFace(a)},m:function(a,b){Mc(a,b,"createBuffer",nc)},k:function(a,
b){Mc(a,b,"createFramebuffer",pc)},Nc:function(a,b){Mc(a,b,"createQuery",R)},qb:function(a,b){for(var c=0;c<a;c++){var d=V.af.createQueryEXT();if(!d){for(T(1282);c<a;)u[b+4*c++>>2]=0;break}var e=zc(R);d.name=e;R[e]=d;u[b+4*c>>2]=e}},j:function(a,b){Mc(a,b,"createRenderbuffer",qc)},ob:function(a,b){Mc(a,b,"createSampler",S)},i:function(a,b){Mc(a,b,"createTexture",rc)},ab:function(a,b){Mc(a,b,"createTransformFeedback",tc)},mc:function(a,b){Mc(a,b,"createVertexArray",Q)},ra:function(a,b){Mc(a,b,"createVertexArray",
Q)},l:function(a){V.generateMipmap(a)},Ne:function(a,b,c,d,e,g,k){Nc("getActiveAttrib",a,b,c,d,e,g,k)},Me:function(a,b,c,d,e,g,k){Nc("getActiveUniform",a,b,c,d,e,g,k)},Db:function(a,b,c,d,e){a=O[a];if(a=V.getActiveUniformBlockName(a,b))e&&0<c?(c=E(a,B,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},Eb:function(a,b,c,d){if(d)if(a=O[a],35393==c)c=V.getActiveUniformBlockName(a,b),u[d>>2]=c.length+1;else{if(a=V.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)u[d+4*c>>2]=a[c];else u[d>>
2]=a}else T(1281)},Gb:function(a,b,c,d,e){if(e)if(0<b&&0==c)T(1281);else{a=O[a];for(var g=[],k=0;k<b;k++)g.push(u[c+4*k>>2]);if(a=V.getActiveUniforms(a,g,d))for(b=a.length,k=0;k<b;k++)u[e+4*k>>2]=a[k]}else T(1281)},Le:function(a,b,c,d){a=V.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=P.indexOf(a[b])},Ke:function(a,b){return V.getAttribLocation(O[a],C(b))},Je:function(a,b){Pc(a,b,4)},pb:function(a,b,c){c?Oc(c,V.getBufferParameter(a,b)):T(1281)},Ie:function(a,
b,c){c?u[c>>2]=V.getBufferParameter(a,b):T(1281)},Dc:function(a,b,c){if(35005==b){b=0;if(a=oc[Kc(a)])b=a.wf;u[c>>2]=b}else T(1280),h("GL_INVALID_ENUM in glGetBufferPointerv")},He:function(){var a=V.getError()||yc;yc=0;return a},Ge:function(a,b){Pc(a,b,2)},Wb:function(a,b){return V.getFragDataLocation(O[a],C(b))},Fe:function(a,b,c,d){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},rb:function(a,b,c){Qc(a,b,c,1)},tb:function(a,
b){Pc(a,b,1)},kc:function(a,b,c){Qc(a,b,c,0)},Ee:function(a,b){Pc(a,b,0)},Qa:function(a,b,c,d,e){if(0>d)T(1281);else if(e){if(a=V.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+4*b>>2]=a[b]}else T(1281)},Ya:function(){T(1282)},Be:function(a,b,c,d){a=V.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,B,d,b):0;c&&(u[c>>2]=b)},Ce:function(a,b,c){if(c)if(a>=mc)T(1281);else if(a=O[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>
2]=a.length+1;else if(35719==b){if(!a.If)for(b=0;b<V.getProgramParameter(a,35718);++b)a.If=Math.max(a.If,V.getActiveUniform(a,b).name.length+1);u[c>>2]=a.If}else if(35722==b){if(!a.Gf)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Gf=Math.max(a.Gf,V.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Gf}else if(35381==b){if(!a.Hf)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Hf=Math.max(a.Hf,V.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Hf}else u[c>>2]=V.getProgramParameter(a,b);else T(1281)},wa:function(a,
b,c){if(c){a=R[a];b=2>U.version?V.af.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Oc(c,d)}else T(1281)},ya:function(a,b,c){if(c){a=V.af.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T(1281)},va:function(a,b,c){if(c){a=R[a];b=2>U.version?V.af.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Oc(c,d)}else T(1281)},Fc:function(a,b,c){if(c){a=V.getQueryParameter(R[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;u[c>>2]=d}else T(1281)},xa:function(a,b,c){if(c){a=V.af.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T(1281)},Gc:function(a,b,c){c?u[c>>2]=V.getQuery(a,b):T(1281)},za:function(a,b,c){c?u[c>>2]=V.af.getQueryEXT(a,b):T(1281)},Ae:function(a,b,c){c?u[c>>2]=V.getRenderbufferParameter(a,b):T(1281)},eb:function(a,b,c){c?z[c>>2]=V.getSamplerParameter(S[a],b):T(1281)},gb:function(a,b,c){c?u[c>>2]=V.getSamplerParameter(S[a],b):T(1281)},ye:function(a,b,c,d){a=V.getShaderInfoLog(P[a]);
null===a&&(a="(unknown error)");b=0<b&&d?E(a,B,d,b):0;c&&(u[c>>2]=b)},xe:function(a,b,c,d){a=V.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},we:function(a,b,c,d){if(a=V.getShaderSource(P[a]))b=0<b&&d?E(a,B,d,b):0,c&&(u[c>>2]=b)},ze:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(P[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=V.getShaderParameter(P[a],b):T(1281)},ve:function(a){var b=
wc[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Rc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||T(1280);b=b&&Rc(b);break;case 7938:b=Rc("OpenGL ES 3.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Rc(b);break;default:T(1280)}wc[a]=
b}return b},Jb:function(a,b){if(2>U.version)return T(1282),0;var c=xc[a];if(c)return 0>b||b>=c.length?(T(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Rc(d)}),c=xc[a]=c,0>b||b>=c.length?(T(1281),0):c[b];default:return T(1280),0}},sb:function(a,b,c,d,e){0>c?T(1281):e?(a=V.getSyncParameter(uc[a],b),null!==a&&(u[e>>2]=a,d&&(u[d>>2]=1))):T(1281)},ue:function(a,b,c){c?z[c>>2]=V.getTexParameter(a,b):T(1281)},
te:function(a,b,c){c?u[c>>2]=V.getTexParameter(a,b):T(1281)},dc:function(a,b,c,d,e,g,k){a=O[a];if(a=V.getTransformFeedbackVarying(a,b))k&&0<c?(c=E(a.name,B,k,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),g&&(u[g>>2]=a.type)},Fb:function(a,b){return V.getUniformBlockIndex(O[a],C(b))},Hb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))T(1281);else{a=O[a];for(var e=[],g=0;g<b;g++)e.push(C(u[c+4*g>>2]));if(a=V.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)u[d+4*g>>2]=a[g]}else T(1281)},pe:function(a,
b){b=C(b);if(a=O[a]){Tc(a);var c=a.Af,d=0,e=b,g=Sc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Ag[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else T(1281);return-1},re:function(a,b,c){Uc(a,b,c,2)},qe:function(a,b,c){Uc(a,b,c,0)},Xb:function(a,b,c){Uc(a,b,c,0)},bc:function(a,b,c){Vc(a,b,c,0)},ac:function(a,b,c){Vc(a,b,c,0)},me:function(a,b,c){c?(U.gf[a].enabled&&h("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),u[c>>2]=V.getVertexAttribOffset(a,
b)):T(1281)},oe:function(a,b,c){Vc(a,b,c,2)},ne:function(a,b,c){Vc(a,b,c,5)},le:function(a,b){V.hint(a,b)},Ua:function(a,b,c){for(var d=Jc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];V.invalidateFramebuffer(a,d)},Ta:function(a,b,c,d,e,g,k){for(var l=Jc[b],m=0;m<b;m++)l[m]=u[c+4*m>>2];V.invalidateSubFramebuffer(a,l,d,e,g,k)},ke:function(a){return(a=nc[a])?V.isBuffer(a):0},je:function(a){return V.isEnabled(a)},ie:function(a){return(a=pc[a])?V.isFramebuffer(a):0},ge:function(a){return(a=O[a])?V.isProgram(a):0},
Jc:function(a){return(a=R[a])?V.isQuery(a):0},Wa:function(a){return(a=R[a])?V.af.isQueryEXT(a):0},fe:function(a){return(a=qc[a])?V.isRenderbuffer(a):0},mb:function(a){return(a=S[a])?V.isSampler(a):0},ee:function(a){return(a=P[a])?V.isShader(a):0},xb:function(a){return V.isSync(uc[a])},de:function(a){return(a=rc[a])?V.isTexture(a):0},$a:function(a){return V.isTransformFeedback(tc[a])},lc:function(a){return(a=Q[a])?V.isVertexArray(a):0},qa:function(a){return(a=Q[a])?V.isVertexArray(a):0},ce:function(a){V.lineWidth(a)},
be:function(a){a=O[a];V.linkProgram(a);a.Af=0;a.Ag={}},rc:function(a,b,c,d){if(26!=d&&10!=d)return h("glMapBufferRange is only supported when access is MAP_WRITE|INVALIDATE_BUFFER"),0;if(!Lc(a))return T(1280),h("GL_INVALID_ENUM in glMapBufferRange"),0;var e=Ea(c);if(!e)return 0;oc[Kc(a)]={offset:b,length:c,wf:e,dg:d};return e},_a:function(){V.pauseTransformFeedback()},ae:function(a,b){V.pixelStorei(a,b)},$d:function(a,b){V.polygonOffset(a,b)},Xa:function(){T(1280)},Va:function(){T(1280)},Aa:function(a,
b){V.af.queryCounterEXT(R[a],b)},Uc:function(a){V.readBuffer(a)},_d:function(a,b,c,d,e,g,k){if(V.Rf)V.readPixels(a,b,c,d,e,g,k);else{var l=Wc(g);V.readPixels(a,b,c,d,e,g,l,k>>Xc(l))}},Zd:function(){},Xd:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},tc:function(a,b,c,d,e){V.renderbufferStorageMultisample(a,b,c,d,e)},Za:function(){V.resumeTransformFeedback()},Wd:function(a,b){V.sampleCoverage(a,!!b)},ib:function(a,b,c){V.samplerParameterf(S[a],b,c)},hb:function(a,b,c){V.samplerParameterf(S[a],b,
z[c>>2])},kb:function(a,b,c){V.samplerParameteri(S[a],b,c)},jb:function(a,b,c){V.samplerParameteri(S[a],b,u[c>>2])},Vd:function(a,b,c,d){V.scissor(a,b,c,d)},Ud:function(){T(1280)},Td:function(a,b,c,d){for(var e="",g=0;g<b;++g){var k=d?u[d+4*g>>2]:-1;e+=C(u[c+4*g>>2],0>k?void 0:k)}V.shaderSource(P[a],e)},Sd:function(a,b,c){V.stencilFunc(a,b,c)},Rd:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},Qd:function(a){V.stencilMask(a)},Pd:function(a,b){V.stencilMaskSeparate(a,b)},Od:function(a,b,c){V.stencilOp(a,
b,c)},Md:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Ld:function(a,b,c,d,e,g,k,l,m){if(V.df)V.texImage2D(a,b,c,d,e,g,k,l,m);else if(m){var t=Wc(l);V.texImage2D(a,b,c,d,e,g,k,l,t,m>>Xc(t))}else V.texImage2D(a,b,c,d,e,g,k,l,null)},Sc:function(a,b,c,d,e,g,k,l,m,t){if(V.df)V.texImage3D(a,b,c,d,e,g,k,l,m,t);else if(t){var r=Wc(m);V.texImage3D(a,b,c,d,e,g,k,l,m,r,t>>Xc(r))}else V.texImage3D(a,b,c,d,e,g,k,l,m,null)},Kd:function(a,b,c){V.texParameterf(a,b,c)},Jd:function(a,b,c){V.texParameterf(a,b,z[c>>
2])},Id:function(a,b,c){V.texParameteri(a,b,c)},Hd:function(a,b,c){V.texParameteri(a,b,u[c>>2])},Sa:function(a,b,c,d,e){V.texStorage2D(a,b,c,d,e)},Ra:function(a,b,c,d,e,g){V.texStorage3D(a,b,c,d,e,g)},Gd:function(a,b,c,d,e,g,k,l,m){if(V.df)V.texSubImage2D(a,b,c,d,e,g,k,l,m);else if(m){var t=Wc(l);V.texSubImage2D(a,b,c,d,e,g,k,l,t,m>>Xc(t))}else V.texSubImage2D(a,b,c,d,e,g,k,l,null)},Rc:function(a,b,c,d,e,g,k,l,m,t,r){if(V.df)V.texSubImage3D(a,b,c,d,e,g,k,l,m,t,r);else if(r){var w=Wc(t);V.texSubImage3D(a,
b,c,d,e,g,k,l,m,t,w,r>>Xc(w))}else V.texSubImage3D(a,b,c,d,e,g,k,l,m,t,null)},fc:function(a,b,c,d){a=O[a];for(var e=[],g=0;g<b;g++)e.push(C(u[c+4*g>>2]));V.transformFeedbackVaryings(a,e,d)},Fd:function(a,b){V.uniform1f(W(a),b)},Ed:function(a,b,c){V.uniform1fv(W(a),z,c>>2,b)},Dd:function(a,b){V.uniform1i(W(a),b)},Bd:function(a,b,c){V.uniform1iv(W(a),u,c>>2,b)},Vb:function(a,b){V.uniform1ui(W(a),b)},Rb:function(a,b,c){V.uniform1uiv(W(a),F,c>>2,b)},Ad:function(a,b,c){V.uniform2f(W(a),b,c)},zd:function(a,
b,c){V.uniform2fv(W(a),z,c>>2,2*b)},yd:function(a,b,c){V.uniform2i(W(a),b,c)},xd:function(a,b,c){V.uniform2iv(W(a),u,c>>2,2*b)},Ub:function(a,b,c){V.uniform2ui(W(a),b,c)},Qb:function(a,b,c){V.uniform2uiv(W(a),F,c>>2,2*b)},wd:function(a,b,c,d){V.uniform3f(W(a),b,c,d)},vd:function(a,b,c){V.uniform3fv(W(a),z,c>>2,3*b)},ud:function(a,b,c,d){V.uniform3i(W(a),b,c,d)},td:function(a,b,c){V.uniform3iv(W(a),u,c>>2,3*b)},Tb:function(a,b,c,d){V.uniform3ui(W(a),b,c,d)},Pb:function(a,b,c){V.uniform3uiv(W(a),F,
c>>2,3*b)},sd:function(a,b,c,d,e){V.uniform4f(W(a),b,c,d,e)},qd:function(a,b,c){V.uniform4fv(W(a),z,c>>2,4*b)},pd:function(a,b,c,d,e){V.uniform4i(W(a),b,c,d,e)},od:function(a,b,c){V.uniform4iv(W(a),u,c>>2,4*b)},Sb:function(a,b,c,d,e){V.uniform4ui(W(a),b,c,d,e)},Ob:function(a,b,c){V.uniform4uiv(W(a),F,c>>2,4*b)},Cb:function(a,b,c){a=O[a];V.uniformBlockBinding(a,b,c)},nd:function(a,b,c,d){V.uniformMatrix2fv(W(a),!!c,z,d>>2,4*b)},Bc:function(a,b,c,d){V.uniformMatrix2x3fv(W(a),!!c,z,d>>2,6*b)},yc:function(a,
b,c,d){V.uniformMatrix2x4fv(W(a),!!c,z,d>>2,8*b)},md:function(a,b,c,d){V.uniformMatrix3fv(W(a),!!c,z,d>>2,9*b)},zc:function(a,b,c,d){V.uniformMatrix3x2fv(W(a),!!c,z,d>>2,6*b)},wc:function(a,b,c,d){V.uniformMatrix3x4fv(W(a),!!c,z,d>>2,12*b)},ld:function(a,b,c,d){V.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b)},xc:function(a,b,c,d){V.uniformMatrix4x2fv(W(a),!!c,z,d>>2,8*b)},vc:function(a,b,c,d){V.uniformMatrix4x3fv(W(a),!!c,z,d>>2,12*b)},Ec:function(a){if(!Lc(a))return T(1280),h("GL_INVALID_ENUM in glUnmapBuffer"),
0;var b=Kc(a),c=oc[b];if(!c)return T(1282),h("buffer was never mapped in glUnmapBuffer"),0;oc[b]=null;c.dg&16||V.bufferSubData(a,c.offset,B,c.wf,c.length);se(c.wf);return 1},kd:function(a){a=O[a];V.useProgram(a);V.Hg=a},jd:function(a){V.validateProgram(O[a])},id:function(a,b){V.vertexAttrib1f(a,b)},hd:function(a,b){V.vertexAttrib1f(a,z[b>>2])},fd:function(a,b,c){V.vertexAttrib2f(a,b,c)},ed:function(a,b){V.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},dd:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},cd:function(a,
b){V.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},bd:function(a,b,c,d,e){V.vertexAttrib4f(a,b,c,d,e)},ad:function(a,b){V.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},db:function(a,b){V.vertexAttribDivisor(a,b)},ma:function(a,b){V.vertexAttribDivisor(a,b)},Oa:function(a,b){V.vertexAttribDivisor(a,b)},Zc:function(a,b){V.vertexAttribDivisor(a,b)},Pa:function(a,b){V.vertexAttribDivisor(a,b)},$b:function(a,b,c,d,e){V.vertexAttribI4i(a,b,c,d,e)},Zb:function(a,b){V.vertexAttribI4i(a,u[b>>
2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},_b:function(a,b,c,d,e){V.vertexAttribI4ui(a,b,c,d,e)},Yb:function(a,b){V.vertexAttribI4ui(a,F[b>>2],F[b+4>>2],F[b+8>>2],F[b+12>>2])},cc:function(a,b,c,d,e){var g=U.gf[a];V.vf?(g.uf=!1,V.vertexAttribIPointer(a,b,c,d,e)):(g.size=b,g.type=c,g.Zf=!1,g.Mf=d,g.yf=e,g.uf=!0,g.cg=function(k,l,m,t,r,w){this.vertexAttribIPointer(k,l,m,r,w)})},$c:function(a,b,c,d,e,g){var k=U.gf[a];V.vf?(k.uf=!1,V.vertexAttribPointer(a,b,c,!!d,e,g)):(k.size=b,k.type=c,k.Zf=d,k.Mf=e,k.yf=g,
k.uf=!0,k.cg=function(l,m,t,r,w,v){this.vertexAttribPointer(l,m,t,r,w,v)})},_c:function(a,b,c,d){V.viewport(a,b,c,d)},ub:function(a,b,c,d){V.waitSync(uc[a],b,(c>>>0)+4294967296*d)},Da:function(a,b,c){B.copyWithin(a,b,b+c)},Ea:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{za.grow(Math.min(2147483648,d)-Ka.byteLength+65535>>>16);Ma();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},
Bb:function(a,b,c){a=I(a);Od(a,b,c)},a:function(a){Pd(a)},g:function(a){try{var b=lc(a);Wb(b);return 0}catch(c){if("undefined"===typeof ic||!(c instanceof J))throw c;return c.jf}},Fa:function(a,b,c,d){try{a:{for(var e=lc(a),g=a=0;g<c;g++){var k=u[b+(8*g+4)>>2],l=e,m=u[b+8*g>>2],t=k,r=void 0,w=q;if(0>t||0>r)throw new J(28);if(null===l.fd)throw new J(8);if(1===(l.flags&2097155))throw new J(8);if(16384===(l.node.mode&61440))throw new J(31);if(!l.Ze.read)throw new J(28);var v="undefined"!==typeof r;if(!v)r=
l.position;else if(!l.seekable)throw new J(70);var x=l.Ze.read(l,w,m,t,r);v||(l.position+=x);var A=x;if(0>A){var D=-1;break a}a+=A;if(A<k)break}D=a}u[d>>2]=D;return 0}catch(H){if("undefined"===typeof ic||!(H instanceof J))throw H;return H.jf}},Ba:function(a,b,c,d,e){try{var g=lc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Xb(g,a,d);xa=[g.position>>>0,(y=g.position,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>
0))/4294967296)>>>0:0)];u[e>>2]=xa[0];u[e+4>>2]=xa[1];g.Xf&&0===a&&0===d&&(g.Xf=null);return 0}catch(k){if("undefined"===typeof ic||!(k instanceof J))throw k;return k.jf}},e:function(a,b,c,d){try{a:{for(var e=lc(a),g=a=0;g<c;g++){var k=Yb(e,q,u[b+8*g>>2],u[b+(8*g+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}u[d>>2]=l;return 0}catch(m){if("undefined"===typeof ic||!(m instanceof J))throw m;return m.jf}},O:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";
var g=e+1;if(0>=a||0>=b)g=0;else{d?zd():Ld(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<Rd[139265];e==Y.length&&(d?f.nf=vd(f.canvas,!0,!0,{antialias:1<Rd[135181],depth:0<Rd[135173],stencil:0<Rd[135174],alpha:0<Rd[135172]}):hc());!f.nf&&d?g=0:(a=new Qd(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,Z=a,g=a.id)}return g},Ac:function(a){a:{if(a=X(a)){a.Of&&I(a.Of)(a.id);Y[a.id-1]=null;Z.id==a.id&&(Z=null);for(a=0;a<Y.length;a++)if(null!==Y[a]){a=void 0;break a}f.nf=void 0}a=void 0}return a},Cd:function(){return 1},
h:function(){return Nd()/1E3-Ud},La:function(){Td||(Td=Da(ob("3.2.1 JS WebGL Emscripten")));return Td},rd:function(){return 0},b:function(a){return(a=X(a))?a.Bg:0},sa:function(){if(Y)return 1;Ud=Nd()/1E3;Rd=Vd;Y=[];Z=null;window.addEventListener("gamepadconnected",$d,!0);window.addEventListener("gamepaddisconnected",be,!0);window.addEventListener("keydown",ce,!0);window.addEventListener("keypress",Yd,!0);window.addEventListener("keyup",de,!0);window.addEventListener("blur",ee,!0);f.canvas.addEventListener("touchmove",
fe,!0);f.canvas.addEventListener("touchstart",je,!0);f.canvas.addEventListener("touchcancel",ke,!0);f.canvas.addEventListener("touchend",ke,!0);f.canvas.addEventListener("mousemove",fe,!0);f.canvas.addEventListener("mousedown",je,!0);f.canvas.addEventListener("mouseup",ke,!0);f.canvas.addEventListener("wheel",le,!0);f.canvas.addEventListener("mousewheel",le,!0);f.canvas.addEventListener("mouseenter",ge,!0);f.canvas.addEventListener("mouseleave",he,!0);f.canvas.addEventListener("drop",te,!0);f.canvas.addEventListener("dragover",
ue,!0);Kd.push(function(a,b){if(Z){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Z.xg=Z.x,Z.yg=Z.y,Z.wg=Z.width,Z.vg=Z.height,Z.x=Z.y=0,Z.width=screen.width,Z.height=screen.height,Z.Wf=!0):1==Z.Wf?(Z.x=Z.xg,Z.y=Z.yg,Z.width=Z.wg,Z.height=Z.vg,Z.Wf=!1):Z.width!=a||Z.height!=b?(Z.width=a,Z.height=b):c=!1;c&&(Ld(Z.width,Z.height,!0),ne(),oe())}});return 1},D:function(){},Xc:function(){},Nd:function(a,b){if(a=X(a)){var c=a.Ef;a.Ef=b;b=c}else b=
null;return b},Mc:function(a){var b=Sd;Sd=a;return b},se:function(a,b){if(a=X(a)){var c=a.Ff;a.Ff=b;b=c}else b=null;return b},he:function(a,b){if(a=X(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},Yd:function(a,b){if(a=X(a)){var c=a.Lf;a.Lf=b;b=c}else b=null;return b},De:function(a,b){if(a=X(a)){var c=a.Of;a.Of=b;b=c}else b=null;return b},gd:function(a,b,c){if(a=X(a))a.x=b,a.y=c},Oe:function(a,b){if(a=X(a)){var c=a.Pf;a.Pf=b;b=c}else b=null;return b},ec:function(a,b){if(a=X(a))a.title=C(b),Z.id==
a.id&&(document.title=a.title)},s:function(a,b){if(a=X(a))a.Bg=b},Lc:function(){},pc:function(a){a=Math.abs(a);0==a?Md(0,0):Md(1,a)},ha:function(){window.removeEventListener("gamepadconnected",$d,!0);window.removeEventListener("gamepaddisconnected",be,!0);window.removeEventListener("keydown",ce,!0);window.removeEventListener("keypress",Yd,!0);window.removeEventListener("keyup",de,!0);window.removeEventListener("blur",ee,!0);f.canvas.removeEventListener("touchmove",fe,!0);f.canvas.removeEventListener("touchstart",
je,!0);f.canvas.removeEventListener("touchcancel",ke,!0);f.canvas.removeEventListener("touchend",ke,!0);f.canvas.removeEventListener("mousemove",fe,!0);f.canvas.removeEventListener("mousedown",je,!0);f.canvas.removeEventListener("mouseup",ke,!0);f.canvas.removeEventListener("wheel",le,!0);f.canvas.removeEventListener("mousewheel",le,!0);f.canvas.removeEventListener("mouseenter",ge,!0);f.canvas.removeEventListener("mouseleave",he,!0);f.canvas.removeEventListener("drop",te,!0);f.canvas.removeEventListener("dragover",
ue,!0);f.canvas.width=f.canvas.height=1;Z=Y=null},c:function(a,b){Rd[a]=b}};
(function(){function a(e){f.asm=e.exports;za=f.asm.Pe;Ma();Na=f.asm.Te;Pa.unshift(f.asm.Qe);Ya("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return bb().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){h("failed to asynchronously prepare wasm: "+g);ua(g)})}var d={a:xe};Xa("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ta||
"function"!==typeof WebAssembly.instantiateStreaming||Za()||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Qe).apply(null,arguments)};
var we=f.___errno_location=function(){return(we=f.___errno_location=f.asm.Re).apply(null,arguments)},Ea=f._malloc=function(){return(Ea=f._malloc=f.asm.Se).apply(null,arguments)},se=f._free=function(){return(se=f._free=f.asm.Ue).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Ve).apply(null,arguments)};var Ja=f.stackAlloc=function(){return(Ja=f.stackAlloc=f.asm.We).apply(null,arguments)};f.addRunDependency=Xa;f.removeRunDependency=Ya;f.FS_createPath=bc;f.FS_createDataFile=dc;
f.FS_createPreloadedFile=gc;f.FS_createLazyFile=fc;f.FS_createDevice=M;f.FS_unlink=Sb;var ye;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Wa=function ze(){ye||Ae();ye||(Wa=ze)};
function Ae(a){function b(){if(!ye&&(ye=!0,f.calledRun=!0,!Aa)){f.noFSInit||$b||($b=!0,Zb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?M("/dev","stdin",f.stdin):Rb("/dev/tty","/dev/stdin"),f.stdout?M("/dev","stdout",null,f.stdout):Rb("/dev/tty","/dev/stdout"),f.stderr?M("/dev","stderr",null,f.stderr):Rb("/dev/tty1","/dev/stderr"),Ub("/dev/stdin",0),Ub("/dev/stdout",1),Ub("/dev/stderr",1));Bb=!1;cb(Pa);cb(Qa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Be){var c=a,d=f._main;
c=c||[];var e=c.length+1,g=Ja(4*(e+1));u[g>>2]=Ia(ea);for(var k=1;k<e;k++)u[(g>>2)+k]=Ia(c[k-1]);u[(g>>2)+e]=0;try{var l=d(e,g);Pd(l)}catch(m){db(m)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ra.unshift(c);cb(Ra)}}a=a||ca;if(!(0<Ua)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ta();cb(Oa);0<Ua||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=Ae;function Pd(a){Ca=a;noExitRuntime||0<qa||(Sa=!0);Ca=a;if(!(noExitRuntime||0<qa)){if(f.onExit)f.onExit(a);Aa=!0}fa(a,new pa(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Be=!0;f.noInitialRun&&(Be=!1);Ae();
