
var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.cg||(f.cg=0);f.cg++;
(function(a){function b(p,t,r,y){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(p,function(l,v){l?y(l):r(v.buffer)});else{var w=new XMLHttpRequest;w.open("GET",p,!0);w.responseType="arraybuffer";w.onprogress=function(l){var v=t;l.total&&(v=l.total);if(l.loaded){w.gf?f.tf[p].loaded=l.loaded:(w.gf=!0,f.tf||(f.tf={}),f.tf[p]={loaded:l.loaded,total:v});var z=v=l=0,F;for(F in f.tf){var T=f.tf[F];l+=T.total;v+=T.loaded;z++}l=
Math.ceil(l*f.cg/z);f.setStatus&&f.setStatus("Downloading data... ("+v+"/"+l+")")}else!f.tf&&f.setStatus&&f.setStatus("Downloading data...")};w.onerror=function(){throw Error("NetworkError for: "+p);};w.onload=function(){if(200==w.status||304==w.status||206==w.status||0==w.status&&w.response)r(w.response);else throw Error(w.statusText+" : "+w.responseURL);};w.send(null)}}function c(p){console.error("package error:",p)}function d(){function p(w,l,v){this.start=w;this.end=l;this.audio=v}function t(w){if(!w)throw"Loading data file failed."+
Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);p.prototype.Ng=w;w=a.files;for(var l=0;l<w.length;++l)p.prototype.gf[w[l].filename].onload();f.removeRunDependency("datafile_gate.data")}f.FS_createPath("/","assets",!0,!0);f.FS_createPath("/assets","themes",!0,!0);f.FS_createPath("/assets","shaders",!0,!0);f.FS_createPath("/assets/shaders","renderer",!0,!0);f.FS_createPath("/assets","textures",!0,!0);p.prototype={gf:{},open:function(w,
l){this.name=l;this.gf[l]=this;f.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Zf(this.Ng.subarray(this.start,this.end))},Zf:function(w){f.FS_createDataFile(this.name,null,w,!0,!0,!0);f.removeRunDependency("fp "+this.name);this.gf[this.name]=null}};for(var r=a.files,y=0;y<r.length;++y)(new p(r[y].start,r[y].end,r[y].audio||0)).open("GET",r[y].filename);f.addRunDependency("datafile_gate.data");f.Dg||(f.Dg={});f.Dg["gate.data"]={qh:!1};m?(t(m),m=null):k=t}"object"===typeof window?
window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof f.locateFilePackage||f.locateFile||(f.locateFile=f.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=f.locateFile?f.locateFile("gate.data",""):"gate.data",g=a.remote_package_size,k=null,m=f.getPreloadedPackage?f.getPreloadedPackage(e,g):null;m||b(e,g,function(p){k?(k(p),k=null):m=p},c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/assets/themes/default.json",start:0,end:208},{filename:"/assets/shaders/Outline.glsl",start:208,end:985},{filename:"/assets/shaders/FlatColor.glsl",start:985,end:1216},{filename:"/assets/shaders/renderer/Quad.glsl",start:1216,end:3844},
{filename:"/assets/shaders/renderer/Circle.glsl",start:3844,end:4818},{filename:"/assets/textures/PixelFont_7x9_112x54.png",start:4818,end:5805}],remote_package_size:5805,package_uuid:"3c3576b3-f1d8-4f16-a044-cca13392a5a2"});var aa={},ba;for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}
var fa="object"===typeof window,ha="function"===typeof importScripts,ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,n="",ja,ka,la,ma,na;
if(ia)n=ha?require("path").dirname(n)+"/":__dirname+"/",ja=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ka=function(a,b,c){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);ma.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==
typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ea=function(a,b){if(noExitRuntime||0<pa)throw process.exitCode=a,b;b instanceof oa||h("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(fa||ha)ha?n=self.location.href:"undefined"!==typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?
n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var q=f.print||console.log.bind(console),h=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);function qa(a){ra||(ra={});ra[a]||(ra[a]=1,h(a))}var ra,sa;f.wasmBinary&&(sa=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&ta("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":wa=[b>>>0,(A=b,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[a>>2]=wa[0];x[a+4>>2]=wa[1];break;case "float":B[a>>2]=b;break;case "double":xa[a>>3]=b;break;default:ta("invalid type for setValue: "+c)}}var ya,za=!1,Aa;
function assert(a,b){a||ta("Assertion failed: "+b)}function Ca(a){var b=Da(a.length);a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b}var Ea="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Fa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ea)return Ea.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?Fa(C,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a){var b=Ga(a)+1,c=Ia(b);E(a,u,c,b);return c}var Ja,u,C,va,Ka,x,G,B,xa;
function La(){var a=ya.buffer;Ja=a;f.HEAP8=u=new Int8Array(a);f.HEAP16=va=new Int16Array(a);f.HEAP32=x=new Int32Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=Ka=new Uint16Array(a);f.HEAPU32=G=new Uint32Array(a);f.HEAPF32=B=new Float32Array(a);f.HEAPF64=xa=new Float64Array(a)}var Ma,Na=[],Oa=[],Pa=[],Qa=[],Ra=!1,pa=0;function Sa(){var a=f.preRun.shift();Na.unshift(a)}var Ta=0,Ua=null,Va=null;function Wa(){Ta++;f.monitorRunDependencies&&f.monitorRunDependencies(Ta)}
function Xa(){Ta--;f.monitorRunDependencies&&f.monitorRunDependencies(Ta);if(0==Ta&&(null!==Ua&&(clearInterval(Ua),Ua=null),Va)){var a=Va;Va=null;a()}}f.preloadedImages={};f.preloadedAudios={};function ta(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";h(a);za=!0;Aa=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ya(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="gate.wasm";
if(!Ya()){var Za=H;H=f.locateFile?f.locateFile(Za,n):n+Za}function $a(){var a=H;try{if(a==H&&sa)return new Uint8Array(sa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){ta(b)}}
function ab(){if(!sa&&(fa||ha)){if("function"===typeof fetch&&!H.startsWith("file://"))return fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return $a()});if(ka)return new Promise(function(a,b){ka(H,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return $a()})}var A,wa;
function bb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Sg;"number"===typeof c?void 0===b.If?I(c)():I(c)(b.If):c(void 0===b.If?null:b.If)}}}function I(a){return Ma.get(a)}function cb(a){a instanceof oa||"unwind"==a||ea(1,a)}function db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function gb(a){if("/"===a)return"/";a=eb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function hb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){ta("randomDevice")}}
function ib(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var jb=[];function kb(a,b){jb[a]={input:[],output:[],vf:b};lb(a,mb)}
var mb={open:function(a){var b=jb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.vf.flush(a.tty)},flush:function(a){a.tty.vf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.vf.vg)throw new J(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.vf.vg(a.tty)}catch(m){throw new J(29);}if(void 0===k&&0===e)throw new J(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.vf.ig)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.vf.ig(a.tty,b[c+e])}catch(g){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},ob={vg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.alloc(256),d=0;try{d=ma.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},ig:function(a,b){null===b||10===b?(q(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(q(Fa(a.output,0)),a.output=[])}},pb={ig:function(a,b){null===b||10===b?(h(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Fa(a.output,0)),a.output=[])}},K={jf:null,kf:function(){return K.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.jf||(K.jf={dir:{node:{pf:K.af.pf,ff:K.af.ff,lookup:K.af.lookup,Pf:K.af.Pf,rename:K.af.rename,unlink:K.af.unlink,rmdir:K.af.rmdir,readdir:K.af.readdir,symlink:K.af.symlink},stream:{rf:K.bf.rf}},file:{node:{pf:K.af.pf,ff:K.af.ff},stream:{rf:K.bf.rf,read:K.bf.read,write:K.bf.write,ng:K.bf.ng,zg:K.bf.zg,Bg:K.bf.Bg}},link:{node:{pf:K.af.pf,ff:K.af.ff,readlink:K.af.readlink},stream:{}},qg:{node:{pf:K.af.pf,ff:K.af.ff},
stream:qb}});c=rb(a,b,c,d);16384===(c.mode&61440)?(c.af=K.jf.dir.node,c.bf=K.jf.dir.stream,c.$e={}):32768===(c.mode&61440)?(c.af=K.jf.file.node,c.bf=K.jf.file.stream,c.cf=0,c.$e=null):40960===(c.mode&61440)?(c.af=K.jf.link.node,c.bf=K.jf.link.stream):8192===(c.mode&61440)&&(c.af=K.jf.qg.node,c.bf=K.jf.qg.stream);c.timestamp=Date.now();a&&(a.$e[b]=c,a.timestamp=c.timestamp);return c},rh:function(a){return a.$e?a.$e.subarray?a.$e.subarray(0,a.cf):new Uint8Array(a.$e):new Uint8Array(0)},rg:function(a,
b){var c=a.$e?a.$e.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.$e,a.$e=new Uint8Array(b),0<a.cf&&a.$e.set(c.subarray(0,a.cf),0))},ah:function(a,b){if(a.cf!=b)if(0==b)a.$e=null,a.cf=0;else{var c=a.$e;a.$e=new Uint8Array(b);c&&a.$e.set(c.subarray(0,Math.min(b,a.cf)));a.cf=b}},af:{pf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.cf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Og=4096;b.blocks=Math.ceil(b.size/b.Og);return b},ff:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.ah(a,b.size)},lookup:function(){throw sb[44];},Pf:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tb(b,c)}catch(g){}if(d)for(var e in d.$e)throw new J(55);
}delete a.parent.$e[a.name];a.parent.timestamp=Date.now();a.name=c;b.$e[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.$e[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=tb(a,b),d;for(d in c.$e)throw new J(55);delete a.$e[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.$e)a.$e.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},bf:{read:function(a,b,c,d,e){var g=a.node.$e;if(e>=a.node.cf)return 0;a=Math.min(a.node.cf-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.$e||a.$e.subarray)){if(g)return a.$e=b.subarray(c,c+d),a.cf=d;if(0===a.cf&&0===e)return a.$e=b.slice(c,c+d),a.cf=d;if(e+d<=a.cf)return a.$e.set(b.subarray(c,c+d),e),d}K.rg(a,e+
d);if(a.$e.subarray&&b.subarray)a.$e.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.$e[e+g]=b[c+g];a.cf=Math.max(a.cf,e+d);return d},rf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.cf);if(0>b)throw new J(28);return b},ng:function(a,b,c){K.rg(a.node,b+c);a.node.cf=Math.max(a.node.cf,b+c)},zg:function(a,b,c,d,e,g){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.$e;if(g&2||a.buffer!==Ja){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;ta();c=void 0;if(!c)throw new J(48);u.set(a,c)}else d=!1,c=a.byteOffset;return{Df:c,kh:d}},Bg:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.bf.write(a,b,0,d,c,!1);return 0}}};function ub(a,b,c){var d="al "+a;ka(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Xa(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Wa(d)}
var vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,J=null,sb={};
function Bb(a,b){a=ib("/",a);b=b||{};if(!a)return{path:"",node:null};var c={sg:!0,jg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.jg)throw new J(32);a=db(a.split("/").filter(function(k){return!!k}),!1);var e=vb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=tb(e,a[d]);c=eb(c+"/"+a[d]);e.Cf&&(!g||g&&b.sg)&&(e=e.Cf.root);if(!g||b.dg)for(g=0;40960===(e.mode&61440);)if(e=Cb(c),c=ib(fb(c),e),e=Bb(c,{jg:b.jg}).node,40<g++)throw new J(32);}return{path:c,node:e}}
function Db(a){for(var b;;){if(a===a.parent)return a=a.kf.Ag,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function tb(a,b){var c;if(c=(c=Fb(a,"x"))?c:a.af.lookup?0:2)throw new J(c,a);for(c=zb[Eb(a.id,b)];c;c=c.uf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.af.lookup(a,b)}
function rb(a,b,c,d){a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.uf=zb[b];return zb[b]=a}var Hb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Fb(a,b){if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Jb(a,b){try{return tb(a,b),20}catch(c){}return Fb(a,"wx")}
function Kb(a){var b=4096;for(a=a||0;a<=b;a++)if(!xb[a])return a;throw new J(33);}function Lb(a,b){Mb||(Mb=function(){},Mb.prototype={});var c=new Mb,d;for(d in a)c[d]=a[d];a=c;b=Kb(b);a.fd=b;return xb[b]=a}var qb={open:function(a){a.bf=wb[a.node.rdev].bf;a.bf.open&&a.bf.open(a)},rf:function(){throw new J(70);}};function lb(a,b){wb[a]={bf:b}}
function Nb(a,b){var c="/"===b,d=!b;if(c&&vb)throw new J(10);if(!c&&!d){var e=Bb(b,{sg:!1});b=e.path;e=e.node;if(e.Cf)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,yh:{},Ag:b,Zg:[]};a=a.kf(b);a.kf=b;b.root=a;c?vb=a:e&&(e.Cf=b,e.kf&&e.kf.Zg.push(b))}function Ob(a,b,c){var d=Bb(a,{parent:!0}).node;a=gb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Jb(d,a);if(e)throw new J(e);if(!d.af.Pf)throw new J(63);return d.af.Pf(d,a,b,c)}function L(a){return Ob(a,16895,0)}
function Pb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Ob(a,b|8192,c)}function Qb(a,b){if(!ib(a))throw new J(44);var c=Bb(b,{parent:!0}).node;if(!c)throw new J(44);b=gb(b);var d=Jb(c,b);if(d)throw new J(d);if(!c.af.symlink)throw new J(63);c.af.symlink(c,b,a)}
function Rb(a){var b=Bb(a,{parent:!0}).node,c=gb(a);a=tb(b,c);a:{try{var d=tb(b,c)}catch(g){d=g.nf;break a}var e=Fb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new J(d);if(!b.af.unlink)throw new J(63);if(a.Cf)throw new J(10);b.af.unlink(b,c);b=Eb(a.parent.id,a.name);if(zb[b]===a)zb[b]=a.uf;else for(b=zb[b];b;){if(b.uf===a){b.uf=a.uf;break}b=b.uf}}function Cb(a){a=Bb(a).node;if(!a)throw new J(44);if(!a.af.readlink)throw new J(28);return ib(Db(a.parent),a.af.readlink(a))}
function Sb(a,b){a="string"===typeof a?Bb(a,{dg:!0}).node:a;if(!a.af.ff)throw new J(63);a.af.ff(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Tb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Hb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=eb(a);try{g=Bb(a,{dg:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new J(20);}else g=Ob(a,c,0),e=!0;if(!g)throw new J(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new J(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(g,Ib(b)):44))throw new J(c);if(b&512){c=g;c="string"===typeof c?Bb(c,{dg:!0}).node:c;if(!c.af.ff)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Fb(c,"w"))throw new J(e);c.af.ff(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Lb({node:g,path:Db(g),id:g.id,flags:b,mode:g.mode,seekable:!0,position:0,bf:g.bf,af:g.af,hh:[],error:!1},d);d.bf.open&&d.bf.open(d);!f.logReadFiles||b&1||(Ub||(Ub={}),
a in Ub||(Ub[a]=1));return d}function Vb(a){if(null===a.fd)throw new J(8);a.fg&&(a.fg=null);try{a.bf.close&&a.bf.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null}function Wb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.bf.rf)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.bf.rf(a,b,c);a.hh=[]}
function Xb(a,b,c,d,e,g){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.bf.write)throw new J(28);a.seekable&&a.flags&1024&&Wb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new J(70);b=a.bf.write(a,b,c,d,e,g);k||(a.position+=b);return b}
function Yb(){J||(J=function(a,b){this.node=b;this.bh=function(c){this.nf=c};this.bh(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){sb[a]=new J(a);sb[a].stack="<generic error, no stack>"}))}var Zb;function $b(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function ac(a,b){a="string"===typeof a?a:Db(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=eb(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}
function bc(a,b,c,d){a=eb(("string"===typeof a?a:Db(a))+"/"+b);c=$b(c,d);return Ob(a,(void 0!==c?c:438)&4095|32768,0)}function cc(a,b,c,d,e,g){a=b?eb(("string"===typeof a?a:Db(a))+"/"+b):a;d=$b(d,e);e=Ob(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Sb(e,d|146);a=Tb(e,577);Xb(a,c,0,c.length,0,g);Vb(a);Sb(e,d)}return e}
function M(a,b,c,d){a=eb(("string"===typeof a?a:Db(a))+"/"+b);b=$b(!!c,!!d);M.xg||(M.xg=64);var e=M.xg++<<8|0;lb(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,p){for(var t=0,r=0;r<p;r++){try{var y=c()}catch(w){throw new J(29);}if(void 0===y&&0===t)throw new J(6);if(null===y||void 0===y)break;t++;k[m+r]=y}t&&(g.node.timestamp=Date.now());return t},write:function(g,k,m,p){for(var t=0;t<p;t++)try{d(k[m+t])}catch(r){throw new J(29);}p&&(g.node.timestamp=
Date.now());return t}});return Pb(a,b,e)}function dc(a){if(!(a.Wg||a.Xg||a.link||a.$e)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.$e=nb(ja(a.url),!0),a.cf=a.$e.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ec(a,b,c,d,e){function g(){this.gg=!1;this.gf=[]}g.prototype.get=function(r){if(!(r>this.length-1||0>r)){var y=r%this.chunkSize;return this.wg(r/this.chunkSize|0)[y]}};g.prototype.Zf=function(r){this.wg=r};g.prototype.og=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var y=Number(r.getResponseHeader("Content-length")),w,l=(w=r.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;r=(w=r.getResponseHeader("Content-Encoding"))&&"gzip"===w;var v=1048576;l||(v=y);var z=this;z.Zf(function(F){var T=F*v,Ba=(F+1)*v-1;Ba=Math.min(Ba,y-1);if("undefined"===typeof z.gf[F]){var ue=z.gf;if(T>Ba)throw Error("invalid range ("+T+", "+Ba+") or no bytes requested!");if(Ba>y-1)throw Error("only "+y+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);y!==v&&O.setRequestHeader("Range","bytes="+T+"-"+Ba);"undefined"!=typeof Uint8Array&&(O.responseType=
"arraybuffer");O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);T=void 0!==O.response?new Uint8Array(O.response||[]):nb(O.responseText||"",!0);ue[F]=T}if("undefined"===typeof z.gf[F])throw Error("doXHR failed!");return z.gf[F]});if(r||!y)v=y=1,v=y=this.wg(0).length,q("LazyFiles on gzip forces download of the whole file when length is accessed");this.Mg=y;
this.Lg=v;this.gg=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.gg||this.og();return this.Mg}},chunkSize:{get:function(){this.gg||this.og();return this.Lg}}});var m=void 0}else m=c,k=void 0;var p=bc(a,b,d,e);k?p.$e=k:m&&(p.$e=null,p.url=m);Object.defineProperties(p,{cf:{get:function(){return this.$e.length}}});
var t={};Object.keys(p.bf).forEach(function(r){var y=p.bf[r];t[r]=function(){dc(p);return y.apply(null,arguments)}});t.read=function(r,y,w,l,v){dc(p);r=r.node.$e;if(v>=r.length)return 0;l=Math.min(r.length-v,l);if(r.slice)for(var z=0;z<l;z++)y[w+z]=r[v+z];else for(z=0;z<l;z++)y[w+z]=r.get(v+z);return l};p.bf=t;return p}
function fc(a,b,c,d,e,g,k,m,p,t){function r(l){function v(F){t&&t();m||cc(a,b,F,d,e,p);g&&g();Xa(w)}var z=!1;f.preloadPlugins.forEach(function(F){!z&&F.canHandle(y)&&(F.handle(l,y,v,function(){k&&k();Xa(w)}),z=!0)});z||v(l)}gc();var y=b?ib(eb(a+"/"+b)):a,w="cp "+y;Wa(w);"string"==typeof c?ub(c,function(l){r(l)},k):r(c)}var hc={},Mb,Ub,ic=void 0;function jc(){ic+=4;return x[ic-4>>2]}function kc(a){a=xb[a];if(!a)throw new J(8);return a}
var lc=1,mc=[],nc={},N=[],oc=[],pc=[],qc=[],P=[],rc=[],sc=[],Q=[],R=[],tc=[],uc=[],vc=[1,1,2,2,4,4,4,2,3,4,8],wc={},xc={};function S(a){yc||(yc=a)}function zc(a){for(var b=lc++,c=a.length;c<b;c++)a[c]=null;return b}function Ac(a){return 32-Math.clz32(0===a?0:a-1)}function Bc(a){a=Ac(a);var b=U.wf[a];if(b)return b;b=V.getParameter(34965);U.wf[a]=V.createBuffer();V.bindBuffer(34963,U.wf[a]);V.bufferData(34963,1<<a,35048);V.bindBuffer(34963,b);return U.wf[a]}
function Cc(a){Dc=!1;for(var b=0;b<U.yg;++b){var c=U.lf[b];if(c.zf&&c.enabled){Dc=!0;var d=c.Sf;d=0<d?a*d:c.size*vc[c.type-5120]*a;var e=Ac(d);var g=U.xf[e],k=U.qf[e];U.qf[e]=U.qf[e]+1&63;var m=g[k];m?e=m:(m=V.getParameter(34964),g[k]=V.createBuffer(),V.bindBuffer(34962,g[k]),V.bufferData(34962,1<<e,35048),V.bindBuffer(34962,m),e=g[k]);V.bindBuffer(34962,e);V.bufferSubData(34962,0,C.subarray(c.Df,c.Df+d));c.lg.call(V,b,c.size,c.type,c.hg,c.Sf,0)}}}function Ec(){Dc&&V.bindBuffer(34962,mc[V.Af])}
function Fc(a,b){a.ug||(a.ug=a.getContext,a.getContext=function(d,e){e=a.ug(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Gc(c,b):0}
function Gc(a,b){var c=zc(sc),d={sh:c,attributes:b,version:b.Yg,Hf:a};a.canvas&&(a.canvas.jh=d);sc[c]=d;("undefined"===typeof b.Rg||b.Rg)&&Hc(d);d.yg=d.Hf.getParameter(34921);d.lf=[];for(a=0;a<d.yg;a++)d.lf[a]={enabled:!1,zf:!1,size:0,type:0,hg:0,Sf:0,Df:0,lg:null};a=Ac(2097152);d.qf=[];d.Tf=[];d.qf.length=d.Tf.length=a+1;d.xf=[];d.Ef=[];d.xf.length=d.Ef.length=a+1;d.wf=[];d.wf.length=a+1;for(b=0;b<=a;++b){d.wf[b]=null;d.qf[b]=d.Tf[b]=0;d.xf[b]=[];d.Ef[b]=[];var e=d.xf[b],g=d.Ef[b];e.length=g.length=
64;for(var k=0;64>k;++k)e[k]=g[k]=null}return c}
function Hc(a){a||(a=U);if(!a.Ug){a.Ug=!0;var b=a.Hf;b.oh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.th=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.df=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.df)b.df=b.getExtension("EXT_disjoint_timer_query");b.wh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Ic={},yc,U,Dc,Jc=[];function Kc(a){switch(a){case 34962:a=34964;break;case 34963:a=34965;break;case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=V.getParameter(a))?a.name|0:0}function Lc(a){switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}}
function Mc(a,b,c,d){for(var e=0;e<a;e++){var g=V[c](),k=g&&zc(d);g?(g.name=k,d[k]=g):S(1282);x[b+4*e>>2]=k}}function Nc(a,b,c,d,e,g,k,m){b=N[b];if(a=V[a](b,c))d=m&&E(a.name,C,m,d),e&&(x[e>>2]=d),g&&(x[g>>2]=a.size),k&&(x[k>>2]=a.type)}function Oc(a,b){G[a>>2]=b;G[a+4>>2]=(b-G[a>>2])/4294967296}
function Pc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&S(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){S(1282);return}d=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>U.version){S(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":S(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:S(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){S(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:S(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Oc(b,d);break;case 0:x[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else S(1281)}
function Qc(a,b,c,d){if(c){b=V.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:S(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{S(1280);return}break;default:S(1280);return}switch(d){case 1:Oc(c,a);break;case 0:x[c>>2]=a;break;case 2:B[c>>2]=a;break;case 4:u[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else S(1281)}
function Rc(a){var b=Ga(a)+1,c=Da(b);E(a,C,c,b);return c}function Sc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Tc(a){var b=a.Gf,c=a.Jg,d;if(!b)for(a.Gf=b={},a.Ig={},d=0;d<V.getProgramParameter(a,35718);++d){var e=V.getActiveUniform(a,d);var g=e.name;e=e.size;var k=Sc(g);k=0<k?g.slice(0,k):g;var m=a.kg;a.kg+=e;c[k]=[e,m];for(g=0;g<e;++g)b[m]=g,a.Ig[m++]=k}}
function W(a){var b=V.Qg;if(b){var c=b.Gf[a];"number"===typeof c&&(b.Gf[a]=c=V.getUniformLocation(b,b.Ig[a]+(0<c?"["+c+"]":"")));return c}S(1282)}function Uc(a,b,c,d){if(c)if(a=N[a],Tc(a),a=V.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else S(1281)}
function Vc(a,b,c,d){if(c)if(U.lf[a].enabled&&h("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=V.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else S(1281)}
function Wc(a){a-=5120;return 0==a?u:1==a?C:2==a?va:4==a?x:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?G:Ka}function Xc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Yc(a){if(!Ra&&!za)try{a()}catch(b){cb(b)}}function Zc(a){setTimeout(function(){Yc(a)},1E4)}var $c=!1,ad=null,bd=0,cd=null,dd=0,ed=0,fd=0,gd=0,hd=[],jd={},kd,ld,md,nd=!1,od=!1,pd=[];
function gc(){function a(){od=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!qd){qd=!0;try{rd=!0}catch(c){rd=!1,q("warning: no blob constructor, cannot create blobs with mimetypes")}sd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rd?null:q("warning: no BlobBuilder");td="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Cg||"undefined"!==typeof td||(q("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Cg=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Cg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=null;if(rd)try{k=new Blob([c],{type:ud(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:ud(d)}))}catch(t){qa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new sd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=td.createObjectURL(k),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=p.width;t.height=p.height;t.getContext("2d").drawImage(p,0,0);f.preloadedImages[d]=t;td.revokeObjectURL(m);e&&e(c)};p.onerror=function(){q("Image "+m+" could not be decoded");g&&g()};p.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.xh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function k(y){p||(p=!0,f.preloadedAudios[d]=y,e&&e(c))}function m(){p||(p=!0,f.preloadedAudios[d]=new Audio,g&&g())}var p=!1;if(rd){try{var t=new Blob([c],{type:ud(d)})}catch(y){return m()}t=td.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!p){q("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var y="",w=0,l=0,v=0;v<c.length;v++)for(w=
w<<8|c[v],l+=8;6<=l;){var z=w>>l-6&63;l-=6;y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[z]}2==l?(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],y+="=="):4==l&&(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],y+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+y;k(r)}};r.src=t;Zc(function(){k(r)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
function(c){!od&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function vd(a,b,c,d){if(b&&f.sf&&a==f.canvas)return f.sf;var e;if(b){var g={antialias:!1,alpha:!1,Yg:2};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof Ic&&(e=Fc(a,g)))var m=sc[e].Hf}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof V,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.sf=m,b&&(U=sc[e],f.sf=V=U&&U.Hf),f.Ah=b,pd.forEach(function(p){p()}),gc());return m}var wd=!1,xd=void 0,yd=void 0;
function zd(a,b){function c(){nd=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ad,xd&&d.requestPointerLock(),nd=!0,yd?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=G[SDL.screen>>2]|8388608),Bd(f.canvas),Cd()):Bd(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),yd?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=G[SDL.screen>>2]&
-8388609),Bd(f.canvas),Cd()):Bd(d));if(f.onFullScreen)f.onFullScreen(nd);if(f.onFullscreen)f.onFullscreen(nd)}xd=a;yd=b;"undefined"===typeof xd&&(xd=!0);"undefined"===typeof yd&&(yd=!1);var d=f.canvas;wd||(wd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Ad(){if(!nd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Dd=0;function Ed(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Dd)Dd=b+1E3/60;else for(;b+2>=Dd;)Dd+=1E3/60;setTimeout(a,Math.max(Dd-b,0))}}
function ud(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Fd=0,Gd=0,Hd=0,Id=0;
function Jd(a){if(od)"mousemove"!=a.type&&"mozMovementX"in a?Hd=Id=0:(Hd=a.movementX||a.mozMovementX||a.webkitMovementX||0,Id=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Fd=SDL.uh+Hd,Gd=SDL.vh+Id):(Fd+=Hd,Gd+=Id);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Hd=e-Fd,Id=a-Gd,Fd=e,Gd=a)}}var Kd=[];function Cd(){var a=f.canvas;Kd.forEach(function(b){b(a.width,a.height)})}function Ld(a,b,c){Bd(f.canvas,a,b);c||Cd()}
function Bd(a,b,c){b&&c?(a.ih=b,a.Tg=c):(b=a.ih,c=a.Tg);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}yd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qd,rd,sd,td;
function Md(a,b){ed=a;fd=b;if(cd)if($c||($c=!0),0==a)ad=function(){var d=Math.max(0,ld+b-Nd())|0;setTimeout(md,d)};else if(1==a)ad=function(){Ed(md)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}ad=function(){setImmediate(md)}}}var Nd;Nd=ia?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function Od(a,b,c,d,e){function g(){if(k<bd){if(!(noExitRuntime||0<pa))try{Pd(Aa)}catch(m){cb(m)}return!1}return!0}assert(!cd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");cd=a;dd=d;var k=bd;$c=!1;md=function(){if(!za)if(0<hd.length){var m=Date.now(),p=hd.shift();p.Sg(p.If);if(kd){var t=kd,r=0==t%1?t-1:Math.floor(t);kd=p.nh?r:(8*t+(r+.5))/9}q('main loop blocker "'+
p.name+'" took '+(Date.now()-m)+" ms");f.setStatus&&(m=f.statusMessage||"Please wait...",p=kd,t=jd.ph,p?p<t?f.setStatus(m+" ("+(t-p)+"/"+t+")"):f.setStatus(m):f.setStatus(""));g()&&setTimeout(md,0)}else if(g())if(gd=gd+1|0,1==ed&&1<fd&&0!=gd%fd)ad();else{0==ed&&(ld=Nd());if(U)for(m=U.xf,U.xf=U.Ef,U.Ef=m,m=U.qf,U.qf=U.Tf,U.Tf=m,m=Ac(2097152),p=0;p<=m;++p)U.qf[p]=0;za||f.preMainLoop&&!1===f.preMainLoop()||(Yc(a),f.postMainLoop&&f.postMainLoop());g()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.$g&&
SDL.audio.$g(),ad())}};e||(b&&0<b?Md(0,1E3/b):Md(1,1),ad());if(c)throw"unwind";}var Qd={};function Rd(){if(!Sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Qd)void 0===Qd[b]?delete a[b]:a[b]=Qd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Sd=c}return Sd}var Sd;
function Td(a,b,c,d){this.id=a;this.y=this.x=0;this.eg=!1;this.Hg=this.Gg=0;this.width=b;this.height=c;this.Fg=b;this.Eg=c;this.title=d;this.attributes=Ud;this.buttons=0;this.keys=[];this.ag=[];this.Kg=this.pg=this.Lf=this.bg=this.Rf=this.Jf=this.Kf=this.Qf=this.tg=this.Xf=this.Yf=this.title=null}function X(a){return 0>=a||!Y?null:Y[a-1]}
var Vd=null,Z=null,Y=null,Wd=null,Xd=null,Ud=null,Yd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Zd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function $d(){var a=Z,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ae(a){Z&&Z.pg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||I(Z.pg)(Z.id,a))}function be(a,b){if(Z){var c=Zd(a);if(-1!=c){var d=b&&Z.keys[c];Z.keys[c]=b;Z.ag[a]=b;Z.Lf&&(d&&(b=2),I(Z.Lf)(Z.id,c,a,b,$d()))}}}
function ce(){de()}function ee(){de()}function fe(a){be(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ge(a){be(a.keyCode,0)}function he(){if(Z)for(var a=0;a<Z.ag.length;++a)Z.ag[a]&&be(a,0)}function ie(a){Z&&(Jd(a),a.target==f.canvas&&Z.Kf&&I(Z.Kf)(Z.id,Fd,Gd))}function je(a){Z&&a.target==f.canvas&&Z.Jf&&I(Z.Jf)(Z.id,1)}function ke(a){Z&&a.target==f.canvas&&Z.Jf&&I(Z.Jf)(Z.id,0)}
function le(a,b){if(Z&&(Jd(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Z.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Z.buttons&=~(1<<c);Z.Qf&&I(Z.Qf)(Z.id,c,b,$d())}}function me(a){Z&&le(a,1)}function ne(a){Z&&le(a,0)}
function oe(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Z&&Z.Rf&&a.target==f.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;I(Z.Rf)(Z.id,b,c);a.preventDefault()}}
function pe(){Z&&Z.Yf&&Yc(function(){I(Z.Yf)(Z.id,Z.width,Z.height)})}function qe(){Z&&Z.tg&&Yc(function(){I(Z.tg)(Z.id,Z.width,Z.height)})}var re={},se=null,te=null;
function de(){if(gd!==te||!gd){se=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;te=gd;for(var a=0;a<se.length;++a){var b=se[a];if(b){re[a]||(q("glfw joystick connected:",a),re[a]={id:Ca(nb(b.id)),mh:b.buttons.length,lh:b.axes.length,buttons:Ca(Array(b.buttons.length)),axes:Ca(Array(4*b.axes.length))});for(var c=re[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,b.axes[d],
"float")}else re[a]&&(q("glfw joystick disconnected",a),ve(re[a].id),ve(re[a].buttons),ve(re[a].axes),delete re[a])}}}
function we(a){function b(m){var p="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(y){if(2!=t.readyState)++g,q("failed to read dropped file: "+m.name+": "+t.error);else{var w=new Uint8Array(y.target.result);var l=l||{};l.flags=l.flags||577;y=Tb(p,l.flags,l.mode);if("string"===typeof w){var v=new Uint8Array(Ga(w)+1);w=E(w,v,0,v.length);Xb(y,v,0,w,void 0,l.Pg)}else if(ArrayBuffer.isView(w))Xb(y,w,0,w.byteLength,void 0,l.Pg);else throw Error("Unsupported data type");
Vb(y);if(++g===e){I(Z.bg)(Z.id,e,c);for(l=0;l<d.length;++l)ve(d[l]);ve(c)}}};t.readAsArrayBuffer(m);var r=Ca(nb(p));d.push(r);ua(c+4*k,r,"i8*")}if(Z&&Z.bg&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ca(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,g=0;ac("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function xe(a){if(Z&&Z.bg)return a.preventDefault(),!1}
function ye(a){return 0===a%4&&(0!==a%100||0===a%400)}function ze(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ae=[31,29,31,30,31,30,31,31,30,31,30,31],Be=[31,28,31,30,31,30,31,31,30,31,30,31];function Ce(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(ye(a.getFullYear())?Ae:Be)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function De(a,b,c,d){function e(l,v,z){for(l="number"===typeof l?l.toString():l||"";l.length<v;)l=z[0]+l;return l}function g(l,v){return e(l,v,"0")}function k(l,v){function z(T){return 0>T?-1:0<T?1:0}var F;0===(F=z(l.getFullYear()-v.getFullYear()))&&0===(F=z(l.getMonth()-v.getMonth()))&&(F=z(l.getDate()-v.getDate()));return F}function m(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function p(l){l=Ce(new Date(l.ef+1900,0,1),l.Wf);var v=new Date(l.getFullYear()+1,0,4),z=m(new Date(l.getFullYear(),0,4));v=m(v);return 0>=k(z,l)?0>=k(v,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var t=x[d+40>>2];d={fh:x[d>>2],eh:x[d+4>>2],Uf:x[d+8>>2],Ff:x[d+12>>2],yf:x[d+16>>2],ef:x[d+20>>2],Vf:x[d+24>>2],Wf:x[d+28>>2],zh:x[d+32>>2],dh:x[d+
36>>2],gh:t?D(t):""};c=D(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");t={"%a":function(l){return y[l.Vf].substring(0,3)},"%A":function(l){return y[l.Vf]},"%b":function(l){return w[l.yf].substring(0,3)},"%B":function(l){return w[l.yf]},"%C":function(l){return g((l.ef+1900)/100|0,2)},"%d":function(l){return g(l.Ff,2)},"%e":function(l){return e(l.Ff,2," ")},"%g":function(l){return p(l).toString().substring(2)},"%G":function(l){return p(l)},"%H":function(l){return g(l.Uf,
2)},"%I":function(l){l=l.Uf;0==l?l=12:12<l&&(l-=12);return g(l,2)},"%j":function(l){return g(l.Ff+ze(ye(l.ef+1900)?Ae:Be,l.yf-1),3)},"%m":function(l){return g(l.yf+1,2)},"%M":function(l){return g(l.eh,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.Uf&&12>l.Uf?"AM":"PM"},"%S":function(l){return g(l.fh,2)},"%t":function(){return"\t"},"%u":function(l){return l.Vf||7},"%U":function(l){var v=new Date(l.ef+1900,0,1),z=0===v.getDay()?v:Ce(v,7-v.getDay());l=new Date(l.ef+1900,l.yf,l.Ff);return 0>
k(z,l)?g(Math.ceil((31-z.getDate()+(ze(ye(l.getFullYear())?Ae:Be,l.getMonth()-1)-31)+l.getDate())/7),2):0===k(z,v)?"01":"00"},"%V":function(l){var v=new Date(l.ef+1901,0,4),z=m(new Date(l.ef+1900,0,4));v=m(v);var F=Ce(new Date(l.ef+1900,0,1),l.Wf);return 0>k(F,z)?"53":0>=k(v,F)?"01":g(Math.ceil((z.getFullYear()<l.ef+1900?l.Wf+32-z.getDate():l.Wf+1-z.getDate())/7),2)},"%w":function(l){return l.Vf},"%W":function(l){var v=new Date(l.ef,0,1),z=1===v.getDay()?v:Ce(v,0===v.getDay()?1:7-v.getDay()+1);l=
new Date(l.ef+1900,l.yf,l.Ff);return 0>k(z,l)?g(Math.ceil((31-z.getDate()+(ze(ye(l.getFullYear())?Ae:Be,l.getMonth()-1)-31)+l.getDate())/7),2):0===k(z,v)?"01":"00"},"%y":function(l){return(l.ef+1900).toString().substring(2)},"%Y":function(l){return l.ef+1900},"%z":function(l){l=l.dh;var v=0<=l;l=Math.abs(l)/60;return(v?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.gh},"%%":function(){return"%"}};for(r in t)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=nb(c,
!1);if(r.length>b)return 0;u.set(r,a);return r.length-1}function Gb(a,b,c,d){a||(a=this);this.parent=a;this.kf=a.kf;this.Cf=null;this.id=yb++;this.name=b;this.mode=c;this.af={};this.bf={};this.rdev=d}
Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Xg:{get:function(){return 16384===(this.mode&61440)}},Wg:{get:function(){return 8192===(this.mode&61440)}}});Yb();zb=Array(4096);Nb(K,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");lb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Pb("/dev/null",259);kb(1280,ob);kb(1536,pb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);var a=hb();M("/dev","random",a);M("/dev","urandom",a);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Nb({kf:function(){var b=rb(a,"fd",16895,73);b.af={lookup:function(c,d){var e=xb[+d];if(!e)throw new J(8);c={parent:null,kf:{Ag:"fake"},af:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();f.FS_createPath=ac;f.FS_createDataFile=cc;f.FS_createPreloadedFile=fc;f.FS_createLazyFile=ec;f.FS_createDevice=M;f.FS_unlink=Rb;for(var V,Ee=0;32>Ee;++Ee)Jc.push(Array(Ee));
f.requestFullscreen=function(a,b){zd(a,b)};f.requestAnimationFrame=function(a){Ed(a)};f.setCanvasSize=function(a,b,c){Ld(a,b,c)};f.pauseMainLoop=function(){ad=null;bd++};f.resumeMainLoop=function(){bd++;var a=ed,b=fd,c=cd;cd=null;Od(c,0,!1,dd,!0);Md(a,b);ad()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return vd(a,b,c,d)};
function nb(a,b){var c=Array(Ga(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var Ge={e:function(a,b,c){ic=c;try{var d=kc(a);switch(b){case 0:var e=jc();return 0>e?-28:Tb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=jc(),d.flags|=e,0;case 5:return e=jc(),va[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return x[Fe()>>2]=28,-1;default:return-28}}catch(g){if("undefined"===typeof hc||!(g instanceof J))throw g;return-g.nf}},Ja:function(a,b,c){ic=c;try{var d=kc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=jc();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=jc();if(!d.bf.Vg)throw new J(59);return d.bf.Vg(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:ta("bad ioctl syscall "+b)}}catch(g){if("undefined"===typeof hc||!(g instanceof J))throw g;return-g.nf}},Ka:function(a,b,c){ic=c;try{var d=D(a),e=c?jc():0;return Tb(d,b,e).fd}catch(g){if("undefined"===typeof hc||!(g instanceof J))throw g;return-g.nf}},h:function(){ta("")},
la:function(a){V.activeTexture(a)},ka:function(a,b){V.attachShader(N[a],P[b])},Lc:function(a,b){V.beginQuery(a,Q[b])},Na:function(a,b){V.df.beginQueryEXT(a,Q[b])},mc:function(a){V.beginTransformFeedback(a)},ja:function(a,b,c){V.bindAttribLocation(N[a],b,D(c))},ia:function(a,b){34962==a?V.Af=b:34963==a&&(V.mf=b);35051==a?V.$f=b:35052==a&&(V.hf=b);V.bindBuffer(a,mc[b])},jc:function(a,b,c){V.bindBufferBase(a,b,mc[c])},kc:function(a,b,c,d,e){V.bindBufferRange(a,b,mc[c],d,e)},ga:function(a,b){V.bindFramebuffer(a,
oc[b])},fa:function(a,b){V.bindRenderbuffer(a,pc[b])},ob:function(a,b){V.bindSampler(a,R[b])},ea:function(a,b){V.bindTexture(a,qc[b])},fb:function(a,b){V.bindTransformFeedback(a,tc[b])},rc:function(a){V.bindVertexArray(rc[a]);a=V.getParameter(34965);V.mf=a?a.name|0:0},ua:function(a){V.bindVertexArray(rc[a]);a=V.getParameter(34965);V.mf=a?a.name|0:0},da:function(a,b,c,d){V.blendColor(a,b,c,d)},ca:function(a){V.blendEquation(a)},ba:function(a,b){V.blendEquationSeparate(a,b)},aa:function(a,b){V.blendFunc(a,
b)},$:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},xc:function(a,b,c,d,e,g,k,m,p,t){V.blitFramebuffer(a,b,c,d,e,g,k,m,p,t)},_:function(a,b,c,d){c?V.bufferData(a,C,d,c,b):V.bufferData(a,b,d)},Z:function(a,b,c,d){V.bufferSubData(a,b,C,d,c)},Y:function(a){return V.checkFramebufferStatus(a)},X:function(a){V.clear(a)},Nb:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},Ob:function(a,b,c){V.clearBufferfv(a,b,B,c>>2)},Qb:function(a,b,c){V.clearBufferiv(a,b,x,c>>2)},Pb:function(a,b,c){V.clearBufferuiv(a,b,
G,c>>2)},W:function(a,b,c,d){V.clearColor(a,b,c,d)},V:function(a){V.clearDepth(a)},U:function(a){V.clearStencil(a)},yb:function(a,b,c,d){return V.clientWaitSync(uc[a],b,(c>>>0)+4294967296*d)},T:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},S:function(a){V.compileShader(P[a])},R:function(a,b,c,d,e,g,k,m){V.hf?V.compressedTexImage2D(a,b,c,d,e,g,k,m):V.compressedTexImage2D(a,b,c,d,e,g,C,m,k)},Sc:function(a,b,c,d,e,g,k,m,p){V.hf?V.compressedTexImage3D(a,b,c,d,e,g,k,m,p):V.compressedTexImage3D(a,b,c,
d,e,g,k,C,p,m)},Q:function(a,b,c,d,e,g,k,m,p){V.hf?V.compressedTexSubImage2D(a,b,c,d,e,g,k,m,p):V.compressedTexSubImage2D(a,b,c,d,e,g,k,C,p,m)},Rc:function(a,b,c,d,e,g,k,m,p,t,r){V.hf?V.compressedTexSubImage3D(a,b,c,d,e,g,k,m,p,t,r):V.compressedTexSubImage3D(a,b,c,d,e,g,k,m,p,C,r,t)},Lb:function(a,b,c,d,e){V.copyBufferSubData(a,b,c,d,e)},P:function(a,b,c,d,e,g,k,m){V.copyTexImage2D(a,b,c,d,e,g,k,m)},N:function(a,b,c,d,e,g,k,m){V.copyTexSubImage2D(a,b,c,d,e,g,k,m)},Tc:function(a,b,c,d,e,g,k,m,p){V.copyTexSubImage3D(a,
b,c,d,e,g,k,m,p)},M:function(){var a=zc(N),b=V.createProgram();b.name=a;b.Of=b.Mf=b.Nf=0;b.kg=1;N[a]=b;return a},L:function(a){var b=zc(P);P[b]=V.createShader(a);return b},K:function(a){V.cullFace(a)},J:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=mc[d];e&&(V.deleteBuffer(e),e.name=0,mc[d]=null,d==V.Af&&(V.Af=0),d==V.mf&&(V.mf=0),d==V.$f&&(V.$f=0),d==V.hf&&(V.hf=0))}},I:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=oc[d];e&&(V.deleteFramebuffer(e),e.name=0,oc[d]=null)}},H:function(a){if(a){var b=
N[a];b?(V.deleteProgram(b),b.name=0,N[a]=null):S(1281)}},Nc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(V.deleteQuery(e),Q[d]=null)}},ib:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(V.df.deleteQueryEXT(e),Q[d]=null)}},G:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=pc[d];e&&(V.deleteRenderbuffer(e),e.name=0,pc[d]=null)}},qb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=R[d];e&&(V.deleteSampler(e),e.name=0,R[d]=null)}},F:function(a){if(a){var b=
P[a];b?(V.deleteShader(b),P[a]=null):S(1281)}},zb:function(a){if(a){var b=uc[a];b?(V.deleteSync(b),b.name=0,uc[a]=null):S(1281)}},E:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=qc[d];e&&(V.deleteTexture(e),e.name=0,qc[d]=null)}},eb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=tc[d];e&&(V.deleteTransformFeedback(e),e.name=0,tc[d]=null)}},qc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];V.deleteVertexArray(rc[d]);rc[d]=null}},ta:function(a,b){for(var c=0;c<a;c++){var d=x[b+
4*c>>2];V.deleteVertexArray(rc[d]);rc[d]=null}},C:function(a){V.depthFunc(a)},B:function(a){V.depthMask(!!a)},A:function(a,b){V.depthRange(a,b)},z:function(a,b){V.detachShader(N[a],P[b])},y:function(a){V.disable(a)},x:function(a){U.lf[a].enabled=!1;V.disableVertexAttribArray(a)},w:function(a,b,c){Cc(b+c);V.drawArrays(a,b,c);Ec()},Db:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},oa:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Pa:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},$c:function(a,
b,c,d){V.drawArraysInstanced(a,b,c,d)},Qa:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Fc:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];V.drawBuffers(c)},Yc:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];V.drawBuffers(c)},pa:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];V.drawBuffers(c)},v:function(a,b,c,d){if(!V.mf){var e=1*vc[c-5120]*b;var g=Bc(e);V.bindBuffer(34963,g);V.bufferSubData(34963,0,C.subarray(d,d+e));d=0}Cc(b);V.drawElements(a,b,c,d);Ec();V.mf||
V.bindBuffer(34963,null)},Cb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},na:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},La:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Ma:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Zc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,b,c,d,e,g){b=g;V.mf||(g=1*vc[e-5120]*d,c=Bc(g),V.bindBuffer(34963,c),V.bufferSubData(34963,0,C.subarray(b,b+g)),b=0);Cc(d);V.drawElements(a,d,e,b);Ec();V.mf||V.bindBuffer(34963,
null)},u:function(a){V.enable(a)},t:function(a){U.lf[a].enabled=!0;V.enableVertexAttribArray(a)},Kc:function(a){V.endQuery(a)},Fa:function(a){V.df.endQueryEXT(a)},lc:function(){V.endTransformFeedback()},Bb:function(a,b){return(a=V.fenceSync(a,b))?(b=zc(uc),a.name=b,uc[b]=a,b):0},r:function(){V.finish()},q:function(){V.flush()},tc:function(a,b,c){if(Lc(a)){var d=nc[Kc(a)];d?d.mg&16?0>b||0>c||b+c>d.length?(S(1281),h("invalid range in glFlushMappedBufferRange")):V.bufferSubData(a,d.offset,C.subarray(d.Bf+
b,d.Bf+b+c)):(S(1282),h("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(S(1282),h("buffer was never mapped in glFlushMappedBufferRange"))}else S(1280),h("GL_INVALID_ENUM in glFlushMappedBufferRange")},p:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,pc[d])},o:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,qc[d],e)},vc:function(a,b,c,d,e){V.framebufferTextureLayer(a,b,qc[c],d,e)},n:function(a){V.frontFace(a)},m:function(a,b){Mc(a,b,"createBuffer",mc)},k:function(a,
b){Mc(a,b,"createFramebuffer",oc)},Qc:function(a,b){Mc(a,b,"createQuery",Q)},tb:function(a,b){for(var c=0;c<a;c++){var d=V.df.createQueryEXT();if(!d){for(S(1282);c<a;)x[b+4*c++>>2]=0;break}var e=zc(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},j:function(a,b){Mc(a,b,"createRenderbuffer",pc)},rb:function(a,b){Mc(a,b,"createSampler",R)},i:function(a,b){Mc(a,b,"createTexture",qc)},db:function(a,b){Mc(a,b,"createTransformFeedback",tc)},pc:function(a,b){Mc(a,b,"createVertexArray",rc)},ra:function(a,b){Mc(a,b,"createVertexArray",
rc)},l:function(a){V.generateMipmap(a)},Qe:function(a,b,c,d,e,g,k){Nc("getActiveAttrib",a,b,c,d,e,g,k)},Pe:function(a,b,c,d,e,g,k){Nc("getActiveUniform",a,b,c,d,e,g,k)},Gb:function(a,b,c,d,e){a=N[a];if(a=V.getActiveUniformBlockName(a,b))e&&0<c?(c=E(a,C,e,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0)},Hb:function(a,b,c,d){if(d)if(a=N[a],35393==c)c=V.getActiveUniformBlockName(a,b),x[d>>2]=c.length+1;else{if(a=V.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)x[d+4*c>>2]=a[c];else x[d>>
2]=a}else S(1281)},Jb:function(a,b,c,d,e){if(e)if(0<b&&0==c)S(1281);else{a=N[a];for(var g=[],k=0;k<b;k++)g.push(x[c+4*k>>2]);if(a=V.getActiveUniforms(a,g,d))for(b=a.length,k=0;k<b;k++)x[e+4*k>>2]=a[k]}else S(1281)},Oe:function(a,b,c,d){a=V.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=P.indexOf(a[b])},Ne:function(a,b){return V.getAttribLocation(N[a],D(b))},Me:function(a,b){Pc(a,b,4)},sb:function(a,b,c){c?Oc(c,V.getBufferParameter(a,b)):S(1281)},Le:function(a,
b,c){c?x[c>>2]=V.getBufferParameter(a,b):S(1281)},Gc:function(a,b,c){if(35005==b){b=0;if(a=nc[Kc(a)])b=a.Bf;x[c>>2]=b}else S(1280),h("GL_INVALID_ENUM in glGetBufferPointerv")},Ke:function(){var a=V.getError()||yc;yc=0;return a},Je:function(a,b){Pc(a,b,2)},Zb:function(a,b){return V.getFragDataLocation(N[a],D(b))},Ie:function(a,b,c,d){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},ub:function(a,b,c){Qc(a,b,c,1)},wb:function(a,
b){Pc(a,b,1)},nc:function(a,b,c){Qc(a,b,c,0)},He:function(a,b){Pc(a,b,0)},Ta:function(a,b,c,d,e){if(0>d)S(1281);else if(e){if(a=V.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)x[e+4*b>>2]=a[b]}else S(1281)},$a:function(){S(1282)},Ee:function(a,b,c,d){a=V.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,C,d,b):0;c&&(x[c>>2]=b)},Fe:function(a,b,c){if(c)if(a>=lc)S(1281);else if(a=N[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>
2]=a.length+1;else if(35719==b){if(!a.Of)for(b=0;b<V.getProgramParameter(a,35718);++b)a.Of=Math.max(a.Of,V.getActiveUniform(a,b).name.length+1);x[c>>2]=a.Of}else if(35722==b){if(!a.Mf)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Mf=Math.max(a.Mf,V.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.Mf}else if(35381==b){if(!a.Nf)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Nf=Math.max(a.Nf,V.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.Nf}else x[c>>2]=V.getProgramParameter(a,b);else S(1281)},wa:function(a,
b,c){if(c){a=Q[a];b=2>U.version?V.df.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Oc(c,d)}else S(1281)},ya:function(a,b,c){if(c){a=V.df.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else S(1281)},va:function(a,b,c){if(c){a=Q[a];b=2>U.version?V.df.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Oc(c,d)}else S(1281)},Ic:function(a,b,c){if(c){a=V.getQueryParameter(Q[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;x[c>>2]=d}else S(1281)},xa:function(a,b,c){if(c){a=V.df.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else S(1281)},Jc:function(a,b,c){c?x[c>>2]=V.getQuery(a,b):S(1281)},za:function(a,b,c){c?x[c>>2]=V.df.getQueryEXT(a,b):S(1281)},De:function(a,b,c){c?x[c>>2]=V.getRenderbufferParameter(a,b):S(1281)},hb:function(a,b,c){c?B[c>>2]=V.getSamplerParameter(R[a],b):S(1281)},jb:function(a,b,c){c?x[c>>2]=V.getSamplerParameter(R[a],b):S(1281)},Be:function(a,b,c,d){a=V.getShaderInfoLog(P[a]);
null===a&&(a="(unknown error)");b=0<b&&d?E(a,C,d,b):0;c&&(x[c>>2]=b)},Ae:function(a,b,c,d){a=V.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},ze:function(a,b,c,d){if(a=V.getShaderSource(P[a]))b=0<b&&d?E(a,C,d,b):0,c&&(x[c>>2]=b)},Ce:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(P[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=V.getShaderParameter(P[a],b):S(1281)},ye:function(a){var b=
wc[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Rc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||S(1280);b=b&&Rc(b);break;case 7938:b=Rc("OpenGL ES 3.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Rc(b);break;default:S(1280)}wc[a]=
b}return b},Mb:function(a,b){if(2>U.version)return S(1282),0;var c=xc[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Rc(d)}),c=xc[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},vb:function(a,b,c,d,e){0>c?S(1281):e?(a=V.getSyncParameter(uc[a],b),null!==a&&(x[e>>2]=a,d&&(x[d>>2]=1))):S(1281)},xe:function(a,b,c){c?B[c>>2]=V.getTexParameter(a,b):S(1281)},
we:function(a,b,c){c?x[c>>2]=V.getTexParameter(a,b):S(1281)},gc:function(a,b,c,d,e,g,k){a=N[a];if(a=V.getTransformFeedbackVarying(a,b))k&&0<c?(c=E(a.name,C,k,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0),e&&(x[e>>2]=a.size),g&&(x[g>>2]=a.type)},Ib:function(a,b){return V.getUniformBlockIndex(N[a],D(b))},Kb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))S(1281);else{a=N[a];for(var e=[],g=0;g<b;g++)e.push(D(x[c+4*g>>2]));if(a=V.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)x[d+4*g>>2]=a[g]}else S(1281)},se:function(a,
b){b=D(b);if(a=N[a]){Tc(a);var c=a.Gf,d=0,e=b,g=Sc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Jg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else S(1281);return-1},ue:function(a,b,c){Uc(a,b,c,2)},te:function(a,b,c){Uc(a,b,c,0)},_b:function(a,b,c){Uc(a,b,c,0)},ec:function(a,b,c){Vc(a,b,c,0)},dc:function(a,b,c){Vc(a,b,c,0)},pe:function(a,b,c){c?(U.lf[a].enabled&&h("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),x[c>>2]=V.getVertexAttribOffset(a,
b)):S(1281)},re:function(a,b,c){Vc(a,b,c,2)},qe:function(a,b,c){Vc(a,b,c,5)},oe:function(a,b){V.hint(a,b)},Xa:function(a,b,c){for(var d=Jc[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];V.invalidateFramebuffer(a,d)},Wa:function(a,b,c,d,e,g,k){for(var m=Jc[b],p=0;p<b;p++)m[p]=x[c+4*p>>2];V.invalidateSubFramebuffer(a,m,d,e,g,k)},ne:function(a){return(a=mc[a])?V.isBuffer(a):0},me:function(a){return V.isEnabled(a)},le:function(a){return(a=oc[a])?V.isFramebuffer(a):0},je:function(a){return(a=N[a])?V.isProgram(a):0},
Mc:function(a){return(a=Q[a])?V.isQuery(a):0},Za:function(a){return(a=Q[a])?V.df.isQueryEXT(a):0},ie:function(a){return(a=pc[a])?V.isRenderbuffer(a):0},pb:function(a){return(a=R[a])?V.isSampler(a):0},he:function(a){return(a=P[a])?V.isShader(a):0},Ab:function(a){return V.isSync(uc[a])},ge:function(a){return(a=qc[a])?V.isTexture(a):0},cb:function(a){return V.isTransformFeedback(tc[a])},oc:function(a){return(a=rc[a])?V.isVertexArray(a):0},qa:function(a){return(a=rc[a])?V.isVertexArray(a):0},fe:function(a){V.lineWidth(a)},
ee:function(a){a=N[a];V.linkProgram(a);a.Gf=0;a.Jg={}},uc:function(a,b,c,d){if(26!=d&&10!=d)return h("glMapBufferRange is only supported when access is MAP_WRITE|INVALIDATE_BUFFER"),0;if(!Lc(a))return S(1280),h("GL_INVALID_ENUM in glMapBufferRange"),0;var e=Da(c);if(!e)return 0;nc[Kc(a)]={offset:b,length:c,Bf:e,mg:d};return e},bb:function(){V.pauseTransformFeedback()},de:function(a,b){V.pixelStorei(a,b)},ce:function(a,b){V.polygonOffset(a,b)},_a:function(){S(1280)},Ya:function(){S(1280)},Aa:function(a,
b){V.df.queryCounterEXT(Q[a],b)},Xc:function(a){V.readBuffer(a)},be:function(a,b,c,d,e,g,k){if(V.$f)V.readPixels(a,b,c,d,e,g,k);else{var m=Wc(g);V.readPixels(a,b,c,d,e,g,m,k>>Xc(m))}},ae:function(){},_d:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},wc:function(a,b,c,d,e){V.renderbufferStorageMultisample(a,b,c,d,e)},ab:function(){V.resumeTransformFeedback()},Zd:function(a,b){V.sampleCoverage(a,!!b)},lb:function(a,b,c){V.samplerParameterf(R[a],b,c)},kb:function(a,b,c){V.samplerParameterf(R[a],b,
B[c>>2])},nb:function(a,b,c){V.samplerParameteri(R[a],b,c)},mb:function(a,b,c){V.samplerParameteri(R[a],b,x[c>>2])},Yd:function(a,b,c,d){V.scissor(a,b,c,d)},Xd:function(){S(1280)},Wd:function(a,b,c,d){for(var e="",g=0;g<b;++g){var k=d?x[d+4*g>>2]:-1;e+=D(x[c+4*g>>2],0>k?void 0:k)}V.shaderSource(P[a],e)},Vd:function(a,b,c){V.stencilFunc(a,b,c)},Ud:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},Td:function(a){V.stencilMask(a)},Sd:function(a,b){V.stencilMaskSeparate(a,b)},Rd:function(a,b,c){V.stencilOp(a,
b,c)},Pd:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Od:function(a,b,c,d,e,g,k,m,p){if(V.hf)V.texImage2D(a,b,c,d,e,g,k,m,p);else if(p){var t=Wc(m);V.texImage2D(a,b,c,d,e,g,k,m,t,p>>Xc(t))}else V.texImage2D(a,b,c,d,e,g,k,m,null)},Vc:function(a,b,c,d,e,g,k,m,p,t){if(V.hf)V.texImage3D(a,b,c,d,e,g,k,m,p,t);else if(t){var r=Wc(p);V.texImage3D(a,b,c,d,e,g,k,m,p,r,t>>Xc(r))}else V.texImage3D(a,b,c,d,e,g,k,m,p,null)},Nd:function(a,b,c){V.texParameterf(a,b,c)},Md:function(a,b,c){V.texParameterf(a,b,B[c>>
2])},Ld:function(a,b,c){V.texParameteri(a,b,c)},Kd:function(a,b,c){V.texParameteri(a,b,x[c>>2])},Va:function(a,b,c,d,e){V.texStorage2D(a,b,c,d,e)},Ua:function(a,b,c,d,e,g){V.texStorage3D(a,b,c,d,e,g)},Jd:function(a,b,c,d,e,g,k,m,p){if(V.hf)V.texSubImage2D(a,b,c,d,e,g,k,m,p);else if(p){var t=Wc(m);V.texSubImage2D(a,b,c,d,e,g,k,m,t,p>>Xc(t))}else V.texSubImage2D(a,b,c,d,e,g,k,m,null)},Uc:function(a,b,c,d,e,g,k,m,p,t,r){if(V.hf)V.texSubImage3D(a,b,c,d,e,g,k,m,p,t,r);else if(r){var y=Wc(t);V.texSubImage3D(a,
b,c,d,e,g,k,m,p,t,y,r>>Xc(y))}else V.texSubImage3D(a,b,c,d,e,g,k,m,p,t,null)},ic:function(a,b,c,d){a=N[a];for(var e=[],g=0;g<b;g++)e.push(D(x[c+4*g>>2]));V.transformFeedbackVaryings(a,e,d)},Id:function(a,b){V.uniform1f(W(a),b)},Hd:function(a,b,c){V.uniform1fv(W(a),B,c>>2,b)},Gd:function(a,b){V.uniform1i(W(a),b)},Ed:function(a,b,c){V.uniform1iv(W(a),x,c>>2,b)},Yb:function(a,b){V.uniform1ui(W(a),b)},Ub:function(a,b,c){V.uniform1uiv(W(a),G,c>>2,b)},Dd:function(a,b,c){V.uniform2f(W(a),b,c)},Cd:function(a,
b,c){V.uniform2fv(W(a),B,c>>2,2*b)},Bd:function(a,b,c){V.uniform2i(W(a),b,c)},Ad:function(a,b,c){V.uniform2iv(W(a),x,c>>2,2*b)},Xb:function(a,b,c){V.uniform2ui(W(a),b,c)},Tb:function(a,b,c){V.uniform2uiv(W(a),G,c>>2,2*b)},zd:function(a,b,c,d){V.uniform3f(W(a),b,c,d)},yd:function(a,b,c){V.uniform3fv(W(a),B,c>>2,3*b)},xd:function(a,b,c,d){V.uniform3i(W(a),b,c,d)},wd:function(a,b,c){V.uniform3iv(W(a),x,c>>2,3*b)},Wb:function(a,b,c,d){V.uniform3ui(W(a),b,c,d)},Sb:function(a,b,c){V.uniform3uiv(W(a),G,
c>>2,3*b)},vd:function(a,b,c,d,e){V.uniform4f(W(a),b,c,d,e)},td:function(a,b,c){V.uniform4fv(W(a),B,c>>2,4*b)},sd:function(a,b,c,d,e){V.uniform4i(W(a),b,c,d,e)},rd:function(a,b,c){V.uniform4iv(W(a),x,c>>2,4*b)},Vb:function(a,b,c,d,e){V.uniform4ui(W(a),b,c,d,e)},Rb:function(a,b,c){V.uniform4uiv(W(a),G,c>>2,4*b)},Fb:function(a,b,c){a=N[a];V.uniformBlockBinding(a,b,c)},qd:function(a,b,c,d){V.uniformMatrix2fv(W(a),!!c,B,d>>2,4*b)},Ec:function(a,b,c,d){V.uniformMatrix2x3fv(W(a),!!c,B,d>>2,6*b)},Bc:function(a,
b,c,d){V.uniformMatrix2x4fv(W(a),!!c,B,d>>2,8*b)},pd:function(a,b,c,d){V.uniformMatrix3fv(W(a),!!c,B,d>>2,9*b)},Cc:function(a,b,c,d){V.uniformMatrix3x2fv(W(a),!!c,B,d>>2,6*b)},zc:function(a,b,c,d){V.uniformMatrix3x4fv(W(a),!!c,B,d>>2,12*b)},od:function(a,b,c,d){V.uniformMatrix4fv(W(a),!!c,B,d>>2,16*b)},Ac:function(a,b,c,d){V.uniformMatrix4x2fv(W(a),!!c,B,d>>2,8*b)},yc:function(a,b,c,d){V.uniformMatrix4x3fv(W(a),!!c,B,d>>2,12*b)},Hc:function(a){if(!Lc(a))return S(1280),h("GL_INVALID_ENUM in glUnmapBuffer"),
0;var b=Kc(a),c=nc[b];if(!c)return S(1282),h("buffer was never mapped in glUnmapBuffer"),0;nc[b]=null;c.mg&16||V.bufferSubData(a,c.offset,C,c.Bf,c.length);ve(c.Bf);return 1},nd:function(a){a=N[a];V.useProgram(a);V.Qg=a},md:function(a){V.validateProgram(N[a])},ld:function(a,b){V.vertexAttrib1f(a,b)},kd:function(a,b){V.vertexAttrib1f(a,B[b>>2])},id:function(a,b,c){V.vertexAttrib2f(a,b,c)},hd:function(a,b){V.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},gd:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},fd:function(a,
b){V.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},ed:function(a,b,c,d,e){V.vertexAttrib4f(a,b,c,d,e)},dd:function(a,b){V.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},gb:function(a,b){V.vertexAttribDivisor(a,b)},ma:function(a,b){V.vertexAttribDivisor(a,b)},Ra:function(a,b){V.vertexAttribDivisor(a,b)},ad:function(a,b){V.vertexAttribDivisor(a,b)},Sa:function(a,b){V.vertexAttribDivisor(a,b)},cc:function(a,b,c,d,e){V.vertexAttribI4i(a,b,c,d,e)},ac:function(a,b){V.vertexAttribI4i(a,x[b>>
2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},bc:function(a,b,c,d,e){V.vertexAttribI4ui(a,b,c,d,e)},$b:function(a,b){V.vertexAttribI4ui(a,G[b>>2],G[b+4>>2],G[b+8>>2],G[b+12>>2])},fc:function(a,b,c,d,e){var g=U.lf[a];V.Af?(g.zf=!1,V.vertexAttribIPointer(a,b,c,d,e)):(g.size=b,g.type=c,g.hg=!1,g.Sf=d,g.Df=e,g.zf=!0,g.lg=function(k,m,p,t,r,y){this.vertexAttribIPointer(k,m,p,r,y)})},cd:function(a,b,c,d,e,g){var k=U.lf[a];V.Af?(k.zf=!1,V.vertexAttribPointer(a,b,c,!!d,e,g)):(k.size=b,k.type=c,k.hg=d,k.Sf=e,k.Df=g,
k.zf=!0,k.lg=function(m,p,t,r,y,w){this.vertexAttribPointer(m,p,t,r,y,w)})},bd:function(a,b,c,d){V.viewport(a,b,c,d)},xb:function(a,b,c,d){V.waitSync(uc[a],b,(c>>>0)+4294967296*d)},Ca:function(a,b,c){C.copyWithin(a,b,b+c)},Da:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ya.grow(Math.min(2147483648,d)-Ja.byteLength+65535>>>16);La();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},
Eb:function(a,b,c){a=I(a);Od(a,b,c)},Ga:function(a,b){var c=0;Rd().forEach(function(d,e){var g=b+c;e=x[a+4*e>>2]=g;for(g=0;g<d.length;++g)u[e++>>0]=d.charCodeAt(g);u[e>>0]=0;c+=d.length+1});return 0},Ha:function(a,b){var c=Rd();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0},a:function(a){Pd(a)},f:function(a){try{var b=kc(a);Vb(b);return 0}catch(c){if("undefined"===typeof hc||!(c instanceof J))throw c;return c.nf}},Ia:function(a,b,c,d){try{a:{for(var e=kc(a),g=a=
0;g<c;g++){var k=x[b+(8*g+4)>>2],m=e,p=x[b+8*g>>2],t=k,r=void 0,y=u;if(0>t||0>r)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(16384===(m.node.mode&61440))throw new J(31);if(!m.bf.read)throw new J(28);var w="undefined"!==typeof r;if(!w)r=m.position;else if(!m.seekable)throw new J(70);var l=m.bf.read(m,y,p,t,r);w||(m.position+=l);var v=l;if(0>v){var z=-1;break a}a+=v;if(v<k)break}z=a}x[d>>2]=z;return 0}catch(F){if("undefined"===typeof hc||!(F instanceof J))throw F;
return F.nf}},Ba:function(a,b,c,d,e){try{var g=kc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Wb(g,a,d);wa=[g.position>>>0,(A=g.position,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[e>>2]=wa[0];x[e+4>>2]=wa[1];g.fg&&0===a&&0===d&&(g.fg=null);return 0}catch(k){if("undefined"===typeof hc||!(k instanceof J))throw k;return k.nf}},d:function(a,b,c,d){try{a:{for(var e=kc(a),g=a=0;g<c;g++){var k=
Xb(e,u,x[b+8*g>>2],x[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}x[d>>2]=m;return 0}catch(p){if("undefined"===typeof hc||!(p instanceof J))throw p;return p.nf}},O:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?zd():Ld(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<Ud[139265];e==Y.length&&(d?f.sf=vd(f.canvas,!0,!0,{antialias:1<Ud[135181],depth:0<Ud[135173],stencil:0<
Ud[135174],alpha:0<Ud[135172]}):gc());!f.sf&&d?g=0:(a=new Td(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,Z=a,g=a.id)}return g},Dc:function(a){a:{if(a=X(a)){a.Xf&&I(a.Xf)(a.id);Y[a.id-1]=null;Z.id==a.id&&(Z=null);for(a=0;a<Y.length;a++)if(null!==Y[a]){a=void 0;break a}f.sf=void 0}a=void 0}return a},Fd:function(){return 1},g:function(){return Nd()/1E3-Xd},Oa:function(){Wd||(Wd=Ca(nb("3.2.1 JS WebGL Emscripten")));return Wd},ud:function(){return 0},b:function(a){return(a=X(a))?a.Kg:0},sa:function(){if(Y)return 1;
Xd=Nd()/1E3;Ud=Yd;Y=[];Z=null;window.addEventListener("gamepadconnected",ce,!0);window.addEventListener("gamepaddisconnected",ee,!0);window.addEventListener("keydown",fe,!0);window.addEventListener("keypress",ae,!0);window.addEventListener("keyup",ge,!0);window.addEventListener("blur",he,!0);f.canvas.addEventListener("touchmove",ie,!0);f.canvas.addEventListener("touchstart",me,!0);f.canvas.addEventListener("touchcancel",ne,!0);f.canvas.addEventListener("touchend",ne,!0);f.canvas.addEventListener("mousemove",
ie,!0);f.canvas.addEventListener("mousedown",me,!0);f.canvas.addEventListener("mouseup",ne,!0);f.canvas.addEventListener("wheel",oe,!0);f.canvas.addEventListener("mousewheel",oe,!0);f.canvas.addEventListener("mouseenter",je,!0);f.canvas.addEventListener("mouseleave",ke,!0);f.canvas.addEventListener("drop",we,!0);f.canvas.addEventListener("dragover",xe,!0);Kd.push(function(a,b){if(Z){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Z.Gg=Z.x,Z.Hg=
Z.y,Z.Fg=Z.width,Z.Eg=Z.height,Z.x=Z.y=0,Z.width=screen.width,Z.height=screen.height,Z.eg=!0):1==Z.eg?(Z.x=Z.Gg,Z.y=Z.Hg,Z.width=Z.Fg,Z.height=Z.Eg,Z.eg=!1):Z.width!=a||Z.height!=b?(Z.width=a,Z.height=b):c=!1;c&&(Ld(Z.width,Z.height,!0),pe(),qe())}});return 1},D:function(){},_c:function(){},Qd:function(a,b){if(a=X(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},Pc:function(a){var b=Vd;Vd=a;return b},ve:function(a,b){if(a=X(a)){var c=a.Lf;a.Lf=b;b=c}else b=null;return b},ke:function(a,b){if(a=X(a)){var c=
a.Qf;a.Qf=b;b=c}else b=null;return b},$d:function(a,b){if(a=X(a)){var c=a.Rf;a.Rf=b;b=c}else b=null;return b},Ge:function(a,b){if(a=X(a)){var c=a.Xf;a.Xf=b;b=c}else b=null;return b},jd:function(a,b,c){if(a=X(a))a.x=b,a.y=c},Re:function(a,b){if(a=X(a)){var c=a.Yf;a.Yf=b;b=c}else b=null;return b},hc:function(a,b){if(a=X(a))a.title=D(b),Z.id==a.id&&(document.title=a.title)},s:function(a,b){if(a=X(a))a.Kg=b},Oc:function(){},sc:function(a){a=Math.abs(a);0==a?Md(0,0):Md(1,a)},ha:function(){window.removeEventListener("gamepadconnected",
ce,!0);window.removeEventListener("gamepaddisconnected",ee,!0);window.removeEventListener("keydown",fe,!0);window.removeEventListener("keypress",ae,!0);window.removeEventListener("keyup",ge,!0);window.removeEventListener("blur",he,!0);f.canvas.removeEventListener("touchmove",ie,!0);f.canvas.removeEventListener("touchstart",me,!0);f.canvas.removeEventListener("touchcancel",ne,!0);f.canvas.removeEventListener("touchend",ne,!0);f.canvas.removeEventListener("mousemove",ie,!0);f.canvas.removeEventListener("mousedown",
me,!0);f.canvas.removeEventListener("mouseup",ne,!0);f.canvas.removeEventListener("wheel",oe,!0);f.canvas.removeEventListener("mousewheel",oe,!0);f.canvas.removeEventListener("mouseenter",je,!0);f.canvas.removeEventListener("mouseleave",ke,!0);f.canvas.removeEventListener("drop",we,!0);f.canvas.removeEventListener("dragover",xe,!0);f.canvas.width=f.canvas.height=1;Z=Y=null},c:function(a,b){Ud[a]=b},Ea:function(a,b,c,d){return De(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;ya=f.asm.Se;La();Ma=f.asm.We;Oa.unshift(f.asm.Te);Xa("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return ab().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){h("failed to asynchronously prepare wasm: "+g);ta(g)})}var d={a:Ge};Wa("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return sa||
"function"!==typeof WebAssembly.instantiateStreaming||Ya()||H.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Te).apply(null,arguments)};
var Fe=f.___errno_location=function(){return(Fe=f.___errno_location=f.asm.Ue).apply(null,arguments)},Da=f._malloc=function(){return(Da=f._malloc=f.asm.Ve).apply(null,arguments)},ve=f._free=function(){return(ve=f._free=f.asm.Xe).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Ye).apply(null,arguments)};var Ia=f.stackAlloc=function(){return(Ia=f.stackAlloc=f.asm.Ze).apply(null,arguments)};f.addRunDependency=Wa;f.removeRunDependency=Xa;f.FS_createPath=ac;f.FS_createDataFile=cc;
f.FS_createPreloadedFile=fc;f.FS_createLazyFile=ec;f.FS_createDevice=M;f.FS_unlink=Rb;var He;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Va=function Ie(){He||Je();He||(Va=Ie)};
function Je(a){function b(){if(!He&&(He=!0,f.calledRun=!0,!za)){f.noFSInit||Zb||(Zb=!0,Yb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?M("/dev","stdin",f.stdin):Qb("/dev/tty","/dev/stdin"),f.stdout?M("/dev","stdout",null,f.stdout):Qb("/dev/tty","/dev/stdout"),f.stderr?M("/dev","stderr",null,f.stderr):Qb("/dev/tty1","/dev/stderr"),Tb("/dev/stdin",0),Tb("/dev/stdout",1),Tb("/dev/stderr",1));Ab=!1;bb(Oa);bb(Pa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Ke){var c=a,d=f._main;
c=c||[];var e=c.length+1,g=Ia(4*(e+1));x[g>>2]=Ha(da);for(var k=1;k<e;k++)x[(g>>2)+k]=Ha(c[k-1]);x[(g>>2)+e]=0;try{var m=d(e,g);Pd(m)}catch(p){cb(p)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Qa.unshift(c);bb(Qa)}}a=a||ca;if(!(0<Ta)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Sa();bb(Na);0<Ta||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=Je;function Pd(a){Aa=a;noExitRuntime||0<pa||(Ra=!0);Aa=a;if(!(noExitRuntime||0<pa)){if(f.onExit)f.onExit(a);za=!0}ea(a,new oa(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ke=!0;f.noInitialRun&&(Ke=!1);Je();
