
var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.Zb||(f.Zb=0);f.Zb++;
(function(a){function b(m,q,r,v){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(m,function(u,y){u?v(u):r(y.buffer)});else{var t=new XMLHttpRequest;t.open("GET",m,!0);t.responseType="arraybuffer";t.onprogress=function(u){var y=q;u.total&&(y=u.total);if(u.loaded){t.mb?f.vb[m].loaded=u.loaded:(t.mb=!0,f.vb||(f.vb={}),f.vb[m]={loaded:u.loaded,total:y});var z=y=u=0,B;for(B in f.vb){var U=f.vb[B];u+=U.total;y+=U.loaded;z++}u=
Math.ceil(u*f.Zb/z);f.setStatus&&f.setStatus("Downloading data... ("+y+"/"+u+")")}else!f.vb&&f.setStatus&&f.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+m);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)r(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}}function c(m){console.error("package error:",m)}function d(){function m(t,u,y){this.start=t;this.end=u;this.audio=y}function q(t){if(!t)throw"Loading data file failed."+
Error().stack;if(!(t instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;t=new Uint8Array(t);m.prototype.Wc=t;t=a.files;for(var u=0;u<t.length;++u)m.prototype.mb[t[u].filename].onload();f.removeRunDependency("datafile_gate.data")}f.FS_createPath("/","assets",!0,!0);f.FS_createPath("/assets","themes",!0,!0);f.FS_createPath("/assets","3D",!0,!0);f.FS_createPath("/assets/3D","shaders",!0,!0);f.FS_createPath("/assets/3D","textures",!0,!0);f.FS_createPath("/assets/3D/textures",
"skybox",!0,!0);f.FS_createPath("/assets","2D",!0,!0);f.FS_createPath("/assets/2D","shaders",!0,!0);f.FS_createPath("/assets/2D","textures",!0,!0);m.prototype={mb:{},open:function(t,u){this.name=u;this.mb[u]=this;f.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.cc(this.Wc.subarray(this.start,this.end))},cc:function(t){f.FS_createDataFile(this.name,null,t,!0,!0,!0);f.removeRunDependency("fp "+this.name);this.mb[this.name]=null}};for(var r=a.files,v=0;v<r.length;++v)(new m(r[v].start,
r[v].end,r[v].audio||0)).open("GET",r[v].filename);f.addRunDependency("datafile_gate.data");f.Cc||(f.Cc={});f.Cc["gate.data"]={md:!1};n?(q(n),n=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof f.locateFilePackage||
f.locateFile||(f.locateFile=f.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=f.locateFile?f.locateFile("gate.data",""):"gate.data",g=a.remote_package_size,h=null,n=f.getPreloadedPackage?f.getPreloadedPackage(e,g):null;n||b(e,g,function(m){h?(h(m),h=null):n=m},c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/assets/themes/default.json",start:0,end:208},
{filename:"/assets/3D/materials.json",start:208,end:419},{filename:"/assets/3D/shaders/Skybox.glsl",start:419,end:1224},{filename:"/assets/3D/shaders/SpotLight.glsl",start:1224,end:12357},{filename:"/assets/3D/shaders/PostProcessing.glsl",start:12357,end:14552},{filename:"/assets/3D/shaders/Outline.glsl",start:14552,end:15309},{filename:"/assets/3D/shaders/FlatColor.glsl",start:15309,end:15540},{filename:"/assets/3D/textures/skybox/bottom.jpg",start:15540,end:296129},{filename:"/assets/3D/textures/skybox/front.jpg",
start:296129,end:769458},{filename:"/assets/3D/textures/skybox/left.jpg",start:769458,end:1371343},{filename:"/assets/3D/textures/skybox/right.jpg",start:1371343,end:1909381},{filename:"/assets/3D/textures/skybox/top.jpg",start:1909381,end:2255520},{filename:"/assets/3D/textures/skybox/back.jpg",start:2255520,end:2995588},{filename:"/assets/2D/shaders/Quad.glsl",start:2995588,end:2998886},{filename:"/assets/2D/shaders/Circle.glsl",start:2998886,end:2999860},{filename:"/assets/2D/textures/PixelFont_7x9_112x54.png",
start:2999860,end:3000847}],remote_package_size:3000847,package_uuid:"b432c528-43bf-40f4-a89f-80ea4cdbc812"});var aa={},l;for(l in f)f.hasOwnProperty(l)&&(aa[l]=f[l]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea="object"===typeof window,fa="function"===typeof importScripts,ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,p="",ia,ja,ka,la,ma;
if(ha)p=fa?require("path").dirname(p)+"/":__dirname+"/",ia=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ja=function(a,b,c){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);la.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==
typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof na))throw a;}),process.on("unhandledRejection",function(a){throw a;}),da=function(a,b){if(noExitRuntime||0<oa)throw process.exitCode=a,b;b instanceof na||k("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ea||fa)fa?p=self.location.href:"undefined"!==typeof document&&document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?
p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var w=f.print||console.log.bind(console),k=f.printErr||console.warn.bind(console);for(l in aa)aa.hasOwnProperty(l)&&(f[l]=aa[l]);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);function pa(a){qa||(qa={});qa[a]||(qa[a]=1,k(a))}var qa,sa;f.wasmBinary&&(sa=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");
function ta(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":A[a>>0]=b;break;case "i8":A[a>>0]=b;break;case "i16":ua[a>>1]=b;break;case "i32":C[a>>2]=b;break;case "i64":va=[b>>>0,(D=b,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];C[a>>2]=va[0];C[a+4>>2]=va[1];break;case "float":wa[a>>2]=b;break;case "double":xa[a>>3]=b;break;default:x("invalid type for setValue: "+c)}}var ya,za=!1,Aa;
function assert(a,b){a||x("Assertion failed: "+b)}function Ba(a){var b=Ca(a.length);a.subarray||a.slice?E.set(a,b):E.set(new Uint8Array(a),b);return b}var Da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ea(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Fa(a,b){return a?Ea(E,a,b):""}
function Ga(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ia(a){var b=Ha(a)+1,c=Ja(b);Ga(a,A,c,b);return c}var Ka,A,E,ua,La,C,Ma,wa,xa;
function Na(){var a=ya.buffer;Ka=a;f.HEAP8=A=new Int8Array(a);f.HEAP16=ua=new Int16Array(a);f.HEAP32=C=new Int32Array(a);f.HEAPU8=E=new Uint8Array(a);f.HEAPU16=La=new Uint16Array(a);f.HEAPU32=Ma=new Uint32Array(a);f.HEAPF32=wa=new Float32Array(a);f.HEAPF64=xa=new Float64Array(a)}var Oa,Pa=[],Qa=[],Ra=[],Sa=[],Ta=!1,oa=0;function Ua(){var a=f.preRun.shift();Pa.unshift(a)}var Va=0,Wa=null,Xa=null;function Ya(){Va++;f.monitorRunDependencies&&f.monitorRunDependencies(Va)}
function Za(){Va--;f.monitorRunDependencies&&f.monitorRunDependencies(Va);if(0==Va&&(null!==Wa&&(clearInterval(Wa),Wa=null),Xa)){var a=Xa;Xa=null;a()}}f.preloadedImages={};f.preloadedAudios={};function x(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";k(a);za=!0;Aa=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function $a(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="gate.wasm";
if(!$a()){var ab=G;G=f.locateFile?f.locateFile(ab,p):p+ab}function bb(){var a=G;try{if(a==G&&sa)return new Uint8Array(sa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function cb(){if(!sa&&(ea||fa)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return bb()});if(ja)return new Promise(function(a,b){ja(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return bb()})}var D,va;
function db(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Qc;"number"===typeof c?void 0===b.Jb?H(c)():H(c)(b.Jb):c(void 0===b.Jb?null:b.Jb)}}}function H(a){return Oa.get(a)}function eb(a){a instanceof na||"unwind"==a||da(1,a)}function fb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function I(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=I(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){x("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],xb:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.xb.flush(a.tty)},flush:function(a){a.tty.xb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.xb.uc)throw new J(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.xb.uc(a.tty)}catch(n){throw new J(29);}if(void 0===h&&0===e)throw new J(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.xb.fc)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.xb.fc(a.tty,b[c+e])}catch(g){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},pb={uc:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},fc:function(a,b){null===b||10===b?(w(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(w(Ea(a.output,0)),a.output=[])}},qb={fc:function(a,b){null===b||10===b?(k(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ea(a.output,0)),a.output=[])}},K={nb:null,ob:function(){return K.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.nb||(K.nb={dir:{node:{qb:K.ib.qb,lb:K.ib.lb,lookup:K.ib.lookup,Qb:K.ib.Qb,rename:K.ib.rename,unlink:K.ib.unlink,rmdir:K.ib.rmdir,readdir:K.ib.readdir,symlink:K.ib.symlink},stream:{sb:K.jb.sb}},file:{node:{qb:K.ib.qb,lb:K.ib.lb},stream:{sb:K.jb.sb,read:K.jb.read,write:K.jb.write,kc:K.jb.kc,yc:K.jb.yc,Ac:K.jb.Ac}},link:{node:{qb:K.ib.qb,lb:K.ib.lb,readlink:K.ib.readlink},stream:{}},nc:{node:{qb:K.ib.qb,lb:K.ib.lb},
stream:rb}});c=sb(a,b,c,d);16384===(c.mode&61440)?(c.ib=K.nb.dir.node,c.jb=K.nb.dir.stream,c.hb={}):32768===(c.mode&61440)?(c.ib=K.nb.file.node,c.jb=K.nb.file.stream,c.kb=0,c.hb=null):40960===(c.mode&61440)?(c.ib=K.nb.link.node,c.jb=K.nb.link.stream):8192===(c.mode&61440)&&(c.ib=K.nb.nc.node,c.jb=K.nb.nc.stream);c.timestamp=Date.now();a&&(a.hb[b]=c,a.timestamp=c.timestamp);return c},nd:function(a){return a.hb?a.hb.subarray?a.hb.subarray(0,a.kb):new Uint8Array(a.hb):new Uint8Array(0)},qc:function(a,
b){var c=a.hb?a.hb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.hb,a.hb=new Uint8Array(b),0<a.kb&&a.hb.set(c.subarray(0,a.kb),0))},$c:function(a,b){if(a.kb!=b)if(0==b)a.hb=null,a.kb=0;else{var c=a.hb;a.hb=new Uint8Array(b);c&&a.hb.set(c.subarray(0,Math.min(b,a.kb)));a.kb=b}},ib:{qb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.kb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Mc=4096;b.blocks=Math.ceil(b.size/b.Mc);return b},lb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.$c(a,b.size)},lookup:function(){throw tb[44];},Qb:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ub(b,c)}catch(g){}if(d)for(var e in d.hb)throw new J(55);
}delete a.parent.hb[a.name];a.parent.timestamp=Date.now();a.name=c;b.hb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.hb[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ub(a,b),d;for(d in c.hb)throw new J(55);delete a.hb[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.hb)a.hb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},jb:{read:function(a,b,c,d,e){var g=a.node.hb;if(e>=a.node.kb)return 0;a=Math.min(a.node.kb-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===A.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.hb||a.hb.subarray)){if(g)return a.hb=b.subarray(c,c+d),a.kb=d;if(0===a.kb&&0===e)return a.hb=b.slice(c,c+d),a.kb=d;if(e+d<=a.kb)return a.hb.set(b.subarray(c,c+d),e),d}K.qc(a,e+
d);if(a.hb.subarray&&b.subarray)a.hb.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.hb[e+g]=b[c+g];a.kb=Math.max(a.kb,e+d);return d},sb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kb);if(0>b)throw new J(28);return b},kc:function(a,b,c){K.qc(a.node,b+c);a.node.kb=Math.max(a.node.kb,b+c)},yc:function(a,b,c,d,e,g){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.hb;if(g&2||a.buffer!==Ka){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;x();c=void 0;if(!c)throw new J(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{Fb:c,ed:d}},Ac:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.jb.write(a,b,0,d,c,!1);return 0}}};function vb(a,b,c){var d="al "+a;ja(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Za(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ya(d)}
var wb=null,xb={},yb=[],zb=1,L=null,Ab=!0,J=null,tb={};
function M(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={rc:!0,hc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.hc)throw new J(32);a=fb(a.split("/").filter(function(h){return!!h}),!1);var e=wb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=ub(e,a[d]);c=I(c+"/"+a[d]);e.Eb&&(!g||g&&b.rc)&&(e=e.Eb.root);if(!g||b.$b)for(g=0;40960===(e.mode&61440);)if(e=Bb(c),c=jb(gb(c),e),e=M(c,{hc:b.hc}).node,40<g++)throw new J(32);}return{path:c,node:e}}
function Cb(a){for(var b;;){if(a===a.parent)return a=a.ob.zc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Db(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%L.length}function ub(a,b){var c;if(c=(c=Eb(a,"x"))?c:a.ib.lookup?0:2)throw new J(c,a);for(c=L[Db(a.id,b)];c;c=c.wb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ib.lookup(a,b)}
function sb(a,b,c,d){a=new Fb(a,b,c,d);b=Db(a.parent.id,a.name);a.wb=L[b];return L[b]=a}var Gb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Hb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Eb(a,b){if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ib(a,b){try{return ub(a,b),20}catch(c){}return Eb(a,"wx")}
function Jb(a){var b=4096;for(a=a||0;a<=b;a++)if(!yb[a])return a;throw new J(33);}function Kb(a,b){Lb||(Lb=function(){},Lb.prototype={});var c=new Lb,d;for(d in a)c[d]=a[d];a=c;b=Jb(b);a.fd=b;return yb[b]=a}var rb={open:function(a){a.jb=xb[a.node.rdev].jb;a.jb.open&&a.jb.open(a)},sb:function(){throw new J(70);}};function mb(a,b){xb[a]={jb:b}}
function Mb(a,b){var c="/"===b,d=!b;if(c&&wb)throw new J(10);if(!c&&!d){var e=M(b,{rc:!1});b=e.path;e=e.node;if(e.Eb)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,ud:{},zc:b,Yc:[]};a=a.ob(b);a.ob=b;b.root=a;c?wb=a:e&&(e.Eb=b,e.ob&&e.ob.Yc.push(b))}function Nb(a,b,c){var d=M(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Ib(d,a);if(e)throw new J(e);if(!d.ib.Qb)throw new J(63);return d.ib.Qb(d,a,b,c)}function N(a){return Nb(a,16895,0)}
function Ob(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Nb(a,b|8192,c)}function Pb(a,b){if(!jb(a))throw new J(44);var c=M(b,{parent:!0}).node;if(!c)throw new J(44);b=hb(b);var d=Ib(c,b);if(d)throw new J(d);if(!c.ib.symlink)throw new J(63);c.ib.symlink(c,b,a)}
function Qb(a){var b=M(a,{parent:!0}).node,c=hb(a);a=ub(b,c);a:{try{var d=ub(b,c)}catch(g){d=g.pb;break a}var e=Eb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new J(d);if(!b.ib.unlink)throw new J(63);if(a.Eb)throw new J(10);b.ib.unlink(b,c);b=Db(a.parent.id,a.name);if(L[b]===a)L[b]=a.wb;else for(b=L[b];b;){if(b.wb===a){b.wb=a.wb;break}b=b.wb}}function Bb(a){a=M(a).node;if(!a)throw new J(44);if(!a.ib.readlink)throw new J(28);return jb(Cb(a.parent),a.ib.readlink(a))}
function Rb(a,b){a="string"===typeof a?M(a,{$b:!0}).node:a;if(!a.ib.lb)throw new J(63);a.ib.lb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Sb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Gb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=I(a);try{g=M(a,{$b:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(g){if(b&128)throw new J(20);}else g=Nb(a,c,0),e=!0;if(!g)throw new J(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new J(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Hb(b)||b&512)?31:Eb(g,Hb(b)):44))throw new J(c);if(b&512){c=g;c="string"===typeof c?M(c,{$b:!0}).node:c;if(!c.ib.lb)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Eb(c,"w"))throw new J(e);c.ib.lb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Kb({node:g,path:Cb(g),id:g.id,flags:b,mode:g.mode,seekable:!0,position:0,jb:g.jb,ib:g.ib,bd:[],error:!1},d);d.jb.open&&d.jb.open(d);!f.logReadFiles||b&1||(Tb||(Tb={}),
a in Tb||(Tb[a]=1));return d}function Ub(a){if(null===a.fd)throw new J(8);a.bc&&(a.bc=null);try{a.jb.close&&a.jb.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null}function Vb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.jb.sb)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.jb.sb(a,b,c);a.bd=[]}
function Wb(a,b,c,d,e,g){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.jb.write)throw new J(28);a.seekable&&a.flags&1024&&Vb(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new J(70);b=a.jb.write(a,b,c,d,e,g);h||(a.position+=b);return b}
function Xb(){J||(J=function(a,b){this.node=b;this.ad=function(c){this.pb=c};this.ad(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){tb[a]=new J(a);tb[a].stack="<generic error, no stack>"}))}var Yb;function Zb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function $b(a,b){a="string"===typeof a?a:Cb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=I(a+"/"+c);try{N(d)}catch(e){}a=d}}return d}
function ac(a,b,c,d){a=I(("string"===typeof a?a:Cb(a))+"/"+b);c=Zb(c,d);return Nb(a,(void 0!==c?c:438)&4095|32768,0)}function bc(a,b,c,d,e,g){a=b?I(("string"===typeof a?a:Cb(a))+"/"+b):a;d=Zb(d,e);e=Nb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Rb(e,d|146);a=Sb(e,577);Wb(a,c,0,c.length,0,g);Ub(a);Rb(e,d)}return e}
function O(a,b,c,d){a=I(("string"===typeof a?a:Cb(a))+"/"+b);b=Zb(!!c,!!d);O.wc||(O.wc=64);var e=O.wc++<<8|0;mb(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,h,n,m){for(var q=0,r=0;r<m;r++){try{var v=c()}catch(t){throw new J(29);}if(void 0===v&&0===q)throw new J(6);if(null===v||void 0===v)break;q++;h[n+r]=v}q&&(g.node.timestamp=Date.now());return q},write:function(g,h,n,m){for(var q=0;q<m;q++)try{d(h[n+q])}catch(r){throw new J(29);}m&&(g.node.timestamp=
Date.now());return q}});return Ob(a,b,e)}function cc(a){if(!(a.Uc||a.Vc||a.link||a.hb)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.hb=ob(ia(a.url),!0),a.kb=a.hb.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function dc(a,b,c,d,e){function g(){this.dc=!1;this.mb=[]}g.prototype.get=function(r){if(!(r>this.length-1||0>r)){var v=r%this.chunkSize;return this.vc(r/this.chunkSize|0)[v]}};g.prototype.cc=function(r){this.vc=r};g.prototype.lc=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var v=Number(r.getResponseHeader("Content-length")),t,u=(t=r.getResponseHeader("Accept-Ranges"))&&
"bytes"===t;r=(t=r.getResponseHeader("Content-Encoding"))&&"gzip"===t;var y=1048576;u||(y=v);var z=this;z.cc(function(B){var U=B*y,ra=(B+1)*y-1;ra=Math.min(ra,v-1);if("undefined"===typeof z.mb[B]){var Vd=z.mb;if(U>ra)throw Error("invalid range ("+U+", "+ra+") or no bytes requested!");if(ra>v-1)throw Error("only "+v+" bytes available! programmer error!");var F=new XMLHttpRequest;F.open("GET",c,!1);v!==y&&F.setRequestHeader("Range","bytes="+U+"-"+ra);"undefined"!=typeof Uint8Array&&(F.responseType=
"arraybuffer");F.overrideMimeType&&F.overrideMimeType("text/plain; charset=x-user-defined");F.send(null);if(!(200<=F.status&&300>F.status||304===F.status))throw Error("Couldn't load "+c+". Status: "+F.status);U=void 0!==F.response?new Uint8Array(F.response||[]):ob(F.responseText||"",!0);Vd[B]=U}if("undefined"===typeof z.mb[B])throw Error("doXHR failed!");return z.mb[B]});if(r||!v)y=v=1,y=v=this.vc(0).length,w("LazyFiles on gzip forces download of the whole file when length is accessed");this.Lc=v;
this.Kc=y;this.dc=!0};if("undefined"!==typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.dc||this.lc();return this.Lc}},chunkSize:{get:function(){this.dc||this.lc();return this.Kc}}});var n=void 0}else n=c,h=void 0;var m=ac(a,b,d,e);h?m.hb=h:n&&(m.hb=null,m.url=n);Object.defineProperties(m,{kb:{get:function(){return this.hb.length}}});
var q={};Object.keys(m.jb).forEach(function(r){var v=m.jb[r];q[r]=function(){cc(m);return v.apply(null,arguments)}});q.read=function(r,v,t,u,y){cc(m);r=r.node.hb;if(y>=r.length)return 0;u=Math.min(r.length-y,u);if(r.slice)for(var z=0;z<u;z++)v[t+z]=r[y+z];else for(z=0;z<u;z++)v[t+z]=r.get(y+z);return u};m.jb=q;return m}
function ec(a,b,c,d,e,g,h,n,m,q){function r(u){function y(B){q&&q();n||bc(a,b,B,d,e,m);g&&g();Za(t)}var z=!1;f.preloadPlugins.forEach(function(B){!z&&B.canHandle(v)&&(B.handle(u,v,y,function(){h&&h();Za(t)}),z=!0)});z||y(u)}fc();var v=b?jb(I(a+"/"+b)):a,t="cp "+v;Ya(t);"string"==typeof c?vb(c,function(u){r(u)},h):r(c)}var gc={},Lb,Tb,hc=void 0;function ic(){hc+=4;return C[hc-4>>2]}function jc(a){a=yb[a];if(!a)throw new J(8);return a}function kc(a){if(!Ta&&!za)try{a()}catch(b){eb(b)}}
function lc(a){setTimeout(function(){kc(a)},1E4)}var mc=!1,P=null,nc=0,oc=null,pc=0,qc=0,rc=0,sc=0,tc=[],uc={},vc,wc,xc,yc=!1,zc=!1,Ac=[];
function fc(){function a(){zc=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Bc){Bc=!0;try{Cc=!0}catch(c){Cc=!1,w("warning: no blob constructor, cannot create blobs with mimetypes")}Dc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Cc?null:w("warning: no BlobBuilder");Ec="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Bc||"undefined"!==typeof Ec||(w("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Bc=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Bc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(Cc)try{h=new Blob([c],{type:Fc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Fc(d)}))}catch(q){pa("Blob constructor present but fails: "+
q+"; falling back to blob builder")}h||(h=new Dc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var n=Ec.createObjectURL(h),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=m.width;q.height=m.height;q.getContext("2d").drawImage(m,0,0);f.preloadedImages[d]=q;Ec.revokeObjectURL(n);e&&e(c)};m.onerror=function(){w("Image "+n+" could not be decoded");g&&g()};m.src=n}});f.preloadPlugins.push({canHandle:function(c){return!f.td&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(v){m||(m=!0,f.preloadedAudios[d]=v,e&&e(c))}function n(){m||(m=!0,f.preloadedAudios[d]=new Audio,g&&g())}var m=!1;if(Cc){try{var q=new Blob([c],{type:Fc(d)})}catch(v){return n()}q=Ec.createObjectURL(q);var r=new Audio;r.addEventListener("canplaythrough",function(){h(r)},!1);r.onerror=function(){if(!m){w("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var v="",t=0,u=0,y=0;y<c.length;y++)for(t=
t<<8|c[y],u+=8;6<=u;){var z=t>>u-6&63;u-=6;v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[z]}2==u?(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],v+="=="):4==u&&(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],v+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+v;h(r)}};r.src=q;lc(function(){h(r)})}else return n()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
function(c){!zc&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Gc(a,b,c,d){if(b&&f.tb&&a==f.canvas)return f.tb;var e;if(b){var g={antialias:!1,alpha:!1,Xc:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof Hc&&(e=Ic(a,g)))var n=Jc[e].Ib}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof Q,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.tb=n,b&&(R=Jc[e],f.tb=Q=R&&R.Ib),f.vd=b,Ac.forEach(function(m){m()}),fc());return n}var Kc=!1,Lc=void 0,Mc=void 0;
function Nc(a,b){function c(){yc=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Oc,Lc&&d.requestPointerLock(),yc=!0,Mc?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=Ma[SDL.screen>>2]|8388608),Pc(f.canvas),Qc()):Pc(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Mc?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=Ma[SDL.screen>>2]&
-8388609),Pc(f.canvas),Qc()):Pc(d));if(f.onFullScreen)f.onFullScreen(yc);if(f.onFullscreen)f.onFullscreen(yc)}Lc=a;Mc=b;"undefined"===typeof Lc&&(Lc=!0);"undefined"===typeof Mc&&(Mc=!1);var d=f.canvas;Kc||(Kc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Oc(){if(!yc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Rc=0;function Sc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Rc)Rc=b+1E3/60;else for(;b+2>=Rc;)Rc+=1E3/60;setTimeout(a,Math.max(Rc-b,0))}}
function Fc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Tc=0,Uc=0,Vc=0,Wc=0;
function Xc(a){if(zc)"mousemove"!=a.type&&"mozMovementX"in a?Vc=Wc=0:(Vc=a.movementX||a.mozMovementX||a.webkitMovementX||0,Wc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Tc=SDL.qd+Vc,Uc=SDL.rd+Wc):(Tc+=Vc,Uc+=Wc);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Vc=e-Tc,Wc=a-Uc,Tc=e,Uc=a)}}var Yc=[];function Qc(){var a=f.canvas;Yc.forEach(function(b){b(a.width,a.height)})}function Zc(a,b,c){Pc(f.canvas,a,b);c||Qc()}
function Pc(a,b,c){b&&c?(a.cd=b,a.Rc=c):(b=a.cd,c=a.Rc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Mc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Bc,Cc,Dc,Ec;
function $c(a,b){qc=a;rc=b;if(oc)if(mc||(mc=!0),0==a)P=function(){var d=Math.max(0,wc+b-ad())|0;setTimeout(xc,d)};else if(1==a)P=function(){Sc(xc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}P=function(){setImmediate(xc)}}}var ad;ad=ha?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function bd(a,b,c,d,e){function g(){if(h<nc){if(!(noExitRuntime||0<oa))try{cd(Aa)}catch(n){eb(n)}return!1}return!0}assert(!oc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");oc=a;pc=d;var h=nc;mc=!1;xc=function(){if(!za)if(0<tc.length){var n=Date.now(),m=tc.shift();m.Qc(m.Jb);if(vc){var q=vc,r=0==q%1?q-1:Math.floor(q);vc=m.jd?r:(8*q+(r+.5))/9}w('main loop blocker "'+
m.name+'" took '+(Date.now()-n)+" ms");f.setStatus&&(n=f.statusMessage||"Please wait...",m=vc,q=uc.ld,m?m<q?f.setStatus(n+" ("+(q-m)+"/"+q+")"):f.setStatus(n):f.setStatus(""));g()&&setTimeout(xc,0)}else if(g())if(sc=sc+1|0,1==qc&&1<rc&&0!=sc%rc)P();else{0==qc&&(wc=ad());if(R)for(n=R.zb,R.zb=R.Gb,R.Gb=n,n=R.rb,R.rb=R.Ub,R.Ub=n,n=dd(2097152),m=0;m<=n;++m)R.rb[m]=0;za||f.preMainLoop&&!1===f.preMainLoop()||(kc(a),f.postMainLoop&&f.postMainLoop());g()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Zc&&
SDL.audio.Zc(),P())}};e||(b&&0<b?$c(0,1E3/b):$c(1,1),P());if(c)throw"unwind";}var ed=1,fd=[],S=[],gd=[],hd=[],jd=[],T=[],kd=[],Jc=[],ld=[1,1,2,2,4,4,4,2,3,4,8],md={};function V(a){nd||(nd=a)}function od(a){for(var b=ed++,c=a.length;c<b;c++)a[c]=null;return b}function dd(a){return 32-Math.clz32(0===a?0:a-1)}
function pd(a){qd=!1;for(var b=0;b<R.xc;++b){var c=R.Bb[b];if(c.Cb&&c.enabled){qd=!0;var d=c.Tb;d=0<d?a*d:c.size*ld[c.type-5120]*a;var e=dd(d);var g=R.zb[e],h=R.rb[e];R.rb[e]=R.rb[e]+1&63;var n=g[h];n?e=n:(n=Q.getParameter(34964),g[h]=Q.createBuffer(),Q.bindBuffer(34962,g[h]),Q.bufferData(34962,1<<e,35048),Q.bindBuffer(34962,n),e=g[h]);Q.bindBuffer(34962,e);Q.bufferSubData(34962,0,E.subarray(c.Fb,c.Fb+d));c.jc.call(Q,b,c.size,c.type,c.ec,c.Tb,0)}}}
function Ic(a,b){a.tc||(a.tc=a.getContext,a.getContext=function(d,e){e=a.tc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?rd(c,b):0}
function rd(a,b){var c=od(Jc),d={od:c,attributes:b,version:b.Xc,Ib:a};a.canvas&&(a.canvas.dd=d);Jc[c]=d;("undefined"===typeof b.Pc||b.Pc)&&sd(d);d.xc=d.Ib.getParameter(34921);d.Bb=[];for(a=0;a<d.xc;a++)d.Bb[a]={enabled:!1,Cb:!1,size:0,type:0,ec:0,Tb:0,Fb:0,jc:null};a=dd(2097152);d.rb=[];d.Ub=[];d.rb.length=d.Ub.length=a+1;d.zb=[];d.Gb=[];d.zb.length=d.Gb.length=a+1;d.yb=[];d.yb.length=a+1;for(b=0;b<=a;++b){d.yb[b]=null;d.rb[b]=d.Ub[b]=0;d.zb[b]=[];d.Gb[b]=[];var e=d.zb[b],g=d.Gb[b];e.length=g.length=
64;for(var h=0;64>h;++h)e[h]=g[h]=null}return c}
function sd(a){a||(a=R);if(!a.Sc){a.Sc=!0;var b=a.Ib;b.kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.pd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.pc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.pc)b.pc=b.getExtension("EXT_disjoint_timer_query");b.sd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Hc={},nd,R,qd,td=[];function ud(a,b,c,d){for(var e=0;e<a;e++){var g=Q[c](),h=g&&od(d);g?(g.name=h,d[h]=g):V(1282);C[b+4*e>>2]=h}}function vd(a){var b=Ha(a)+1,c=Ca(b);Ga(a,E,c,b);return c}function wd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function xd(a){var b=Q.Oc;if(b){var c=b.Hb[a];"number"===typeof c&&(b.Hb[a]=c=Q.getUniformLocation(b,b.Hc[a]+(0<c?"["+c+"]":"")));return c}V(1282)}
function yd(a,b,c,d){this.id=a;this.y=this.x=0;this.ac=!1;this.Gc=this.Fc=0;this.width=b;this.height=c;this.Ec=b;this.Dc=c;this.title=d;this.attributes=W;this.buttons=0;this.keys=[];this.Xb=[];this.Jc=this.mc=this.Mb=this.Yb=this.Sb=this.Kb=this.Lb=this.Rb=this.sc=this.Vb=this.Ab=this.title=null}function X(a){return 0>=a||!Y?null:Y[a-1]}
var zd=null,Z=null,Y=null,Ad=null,Bd=null,W=null,Cd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Dd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Ed(){var a=Z,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Fd(a){Z&&Z.mc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||H(Z.mc)(Z.id,a))}function Gd(a,b){if(Z){var c=Dd(a);if(-1!=c){var d=b&&Z.keys[c];Z.keys[c]=b;Z.Xb[a]=b;Z.Mb&&(d&&(b=2),H(Z.Mb)(Z.id,c,a,b,Ed()))}}}
function Hd(){Id()}function Jd(){Id()}function Kd(a){Gd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Ld(a){Gd(a.keyCode,0)}function Md(){if(Z)for(var a=0;a<Z.Xb.length;++a)Z.Xb[a]&&Gd(a,0)}function Nd(a){Z&&(Xc(a),a.target==f.canvas&&Z.Lb&&H(Z.Lb)(Z.id,Tc,Uc))}function Od(a){Z&&a.target==f.canvas&&Z.Kb&&H(Z.Kb)(Z.id,1)}function Pd(a){Z&&a.target==f.canvas&&Z.Kb&&H(Z.Kb)(Z.id,0)}
function Qd(a,b){if(Z&&(Xc(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Z.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Z.buttons&=~(1<<c);Z.Rb&&H(Z.Rb)(Z.id,c,b,Ed())}}function Rd(a){Z&&Qd(a,1)}function Sd(a){Z&&Qd(a,0)}
function Td(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Z&&Z.Sb&&a.target==f.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;H(Z.Sb)(Z.id,b,c);a.preventDefault()}}
function Ud(){Z&&Z.Ab&&kc(function(){H(Z.Ab)(Z.id,Z.width,Z.height)})}function Wd(){Z&&Z.sc&&kc(function(){H(Z.sc)(Z.id,Z.width,Z.height)})}var Xd={},Yd=null,Zd=null;
function Id(){if(sc!==Zd||!sc){Yd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;Zd=sc;for(var a=0;a<Yd.length;++a){var b=Yd[a];if(b){Xd[a]||(w("glfw joystick connected:",a),Xd[a]={id:Ba(ob(b.id)),hd:b.buttons.length,gd:b.axes.length,buttons:Ba(Array(b.buttons.length)),axes:Ba(Array(4*b.axes.length))});for(var c=Xd[a],d=0;d<b.buttons.length;++d)ta(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ta(c.axes+4*d,b.axes[d],
"float")}else Xd[a]&&(w("glfw joystick disconnected",a),$d(Xd[a].id),$d(Xd[a].buttons),$d(Xd[a].axes),delete Xd[a])}}}
function ae(a){function b(n){var m="/.glfw_dropped_files/"+n.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=function(v){if(2!=q.readyState)++g,w("failed to read dropped file: "+n.name+": "+q.error);else{var t=new Uint8Array(v.target.result);var u=u||{};u.flags=u.flags||577;v=Sb(m,u.flags,u.mode);if("string"===typeof t){var y=new Uint8Array(Ha(t)+1);t=Ga(t,y,0,y.length);Wb(v,y,0,t,void 0,u.Nc)}else if(ArrayBuffer.isView(t))Wb(v,t,0,t.byteLength,void 0,u.Nc);else throw Error("Unsupported data type");
Ub(v);if(++g===e){H(Z.Yb)(Z.id,e,c);for(u=0;u<d.length;++u)$d(d[u]);$d(c)}}};q.readAsArrayBuffer(n);var r=Ba(ob(m));d.push(r);ta(c+4*h,r,"i8*")}if(Z&&Z.Yb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ba(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,g=0;$b("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function be(a){if(Z&&Z.Yb)return a.preventDefault(),!1}
function Fb(a,b,c,d){a||(a=this);this.parent=a;this.ob=a.ob;this.Eb=null;this.id=zb++;this.name=b;this.mode=c;this.ib={};this.jb={};this.rdev=d}Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vc:{get:function(){return 16384===(this.mode&61440)}},Uc:{get:function(){return 8192===(this.mode&61440)}}});Xb();
L=Array(4096);Mb(K,"/");N("/tmp");N("/home");N("/home/web_user");(function(){N("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Ob("/dev/null",259);lb(1280,pb);lb(1536,qb);Ob("/dev/tty",1280);Ob("/dev/tty1",1536);var a=ib();O("/dev","random",a);O("/dev","urandom",a);N("/dev/shm");N("/dev/shm/tmp")})();
(function(){N("/proc");var a=N("/proc/self");N("/proc/self/fd");Mb({ob:function(){var b=sb(a,"fd",16895,73);b.ib={lookup:function(c,d){var e=yb[+d];if(!e)throw new J(8);c={parent:null,ob:{zc:"fake"},ib:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();f.FS_createPath=$b;f.FS_createDataFile=bc;f.FS_createPreloadedFile=ec;f.FS_createLazyFile=dc;f.FS_createDevice=O;f.FS_unlink=Qb;f.requestFullscreen=function(a,b){Nc(a,b)};f.requestAnimationFrame=function(a){Sc(a)};
f.setCanvasSize=function(a,b,c){Zc(a,b,c)};f.pauseMainLoop=function(){P=null;nc++};f.resumeMainLoop=function(){nc++;var a=qc,b=rc,c=oc;oc=null;bd(c,0,!1,pc,!0);$c(a,b);P()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Gc(a,b,c,d)};for(var Q,ce=0;32>ce;++ce)td.push(Array(ce));
function ob(a,b){var c=Array(Ha(a)+1);a=Ga(a,c,0,c.length);b&&(c.length=a);return c}
var ee={u:function(a,b,c){hc=c;try{var d=jc(a);switch(b){case 0:var e=ic();return 0>e?-28:Sb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ic(),d.flags|=e,0;case 5:return e=ic(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return C[de()>>2]=28,-1;default:return-28}}catch(g){if("undefined"===typeof gc||!(g instanceof J))throw g;return-g.pb}},Ya:function(a,b,c){hc=c;try{var d=jc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=ic();return C[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=ic();if(!d.jb.Tc)throw new J(59);return d.jb.Tc(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:x("bad ioctl syscall "+b)}}catch(g){if("undefined"===typeof gc||!(g instanceof J))throw g;return-g.pb}},H:function(a,b,c){hc=c;try{var d=Fa(a),e=c?ic():0;return Sb(d,b,e).fd}catch(g){if("undefined"===typeof gc||!(g instanceof J))throw g;return-g.pb}},t:function(){x("")},
I:function(){return f.canvas.height},J:function(){return f.canvas.width},Va:function(a,b,c){E.copyWithin(a,b,b+c)},Wa:function(a){var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ya.grow(Math.min(2147483648,d)-Ka.byteLength+65535>>>16);Na();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},L:function(a,b,c){a=H(a);bd(a,b,c)},a:function(a){cd(a)},v:function(a){try{var b=jc(a);
Ub(b);return 0}catch(c){if("undefined"===typeof gc||!(c instanceof J))throw c;return c.pb}},Xa:function(a,b,c,d){try{a:{for(var e=jc(a),g=a=0;g<c;g++){var h=C[b+(8*g+4)>>2],n=e,m=C[b+8*g>>2],q=h,r=void 0,v=A;if(0>q||0>r)throw new J(28);if(null===n.fd)throw new J(8);if(1===(n.flags&2097155))throw new J(8);if(16384===(n.node.mode&61440))throw new J(31);if(!n.jb.read)throw new J(28);var t="undefined"!==typeof r;if(!t)r=n.position;else if(!n.seekable)throw new J(70);var u=n.jb.read(n,v,m,q,r);t||(n.position+=
u);var y=u;if(0>y){var z=-1;break a}a+=y;if(y<h)break}z=a}C[d>>2]=z;return 0}catch(B){if("undefined"===typeof gc||!(B instanceof J))throw B;return B.pb}},Ua:function(a,b,c,d,e){try{var g=jc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Vb(g,a,d);va=[g.position>>>0,(D=g.position,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];C[e>>2]=va[0];C[e+4>>2]=va[1];g.bc&&0===a&&0===d&&(g.bc=null);return 0}catch(h){if("undefined"===
typeof gc||!(h instanceof J))throw h;return h.pb}},G:function(a,b,c,d){try{a:{for(var e=jc(a),g=a=0;g<c;g++){var h=Wb(e,A,C[b+8*g>>2],C[b+(8*g+4)>>2],void 0);if(0>h){var n=-1;break a}a+=h}n=a}C[d>>2]=n;return 0}catch(m){if("undefined"===typeof gc||!(m instanceof J))throw m;return m.pb}},j:function(a){Q.activeTexture(a)},Ta:function(a,b){Q.attachShader(S[a],T[b])},d:function(a,b){34962==a?Q.ub=b:34963==a&&(Q.Db=b);35051==a?Q.oc=b:35052==a&&(Q.Wb=b);Q.bindBuffer(a,fd[b])},ka:function(a,b,c){Q.bindBufferBase(a,
b,fd[c])},i:function(a,b){Q.bindFramebuffer(a,gd[b])},ta:function(a,b){Q.bindRenderbuffer(a,hd[b])},g:function(a,b){Q.bindTexture(a,jd[b])},c:function(a){Q.bindVertexArray(kd[a]);a=Q.getParameter(34965);Q.Db=a?a.name|0:0},k:function(a,b){Q.blendFunc(a,b)},f:function(a,b,c,d){c?Q.bufferData(a,E,d,c,b):Q.bufferData(a,b,d)},C:function(a,b,c,d){Q.bufferSubData(a,b,E,d,c)},qa:function(a){return Q.checkFramebufferStatus(a)},n:function(a){Q.clear(a)},ma:function(a,b,c,d){Q.clearColor(a,b,c,d)},Ma:function(a){Q.compileShader(T[a])},
Za:function(){var a=od(S),b=Q.createProgram();b.name=a;b.Pb=b.Nb=b.Ob=0;b.ic=1;S[a]=b;return a},Oa:function(a){var b=od(T);T[b]=Q.createShader(a);return b},D:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=fd[d];e&&(Q.deleteBuffer(e),e.name=0,fd[d]=null,d==Q.ub&&(Q.ub=0),d==Q.Db&&(Q.Db=0),d==Q.oc&&(Q.oc=0),d==Q.Wb&&(Q.Wb=0))}},oa:function(a,b){for(var c=0;c<a;++c){var d=C[b+4*c>>2],e=gd[d];e&&(Q.deleteFramebuffer(e),e.name=0,gd[d]=null)}},F:function(a){if(a){var b=S[a];b?(Q.deleteProgram(b),
b.name=0,S[a]=null):V(1281)}},na:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=hd[d];e&&(Q.deleteRenderbuffer(e),e.name=0,hd[d]=null)}},w:function(a){if(a){var b=T[a];b?(Q.deleteShader(b),T[a]=null):V(1281)}},x:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=jd[d];e&&(Q.deleteTexture(e),e.name=0,jd[d]=null)}},za:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2];Q.deleteVertexArray(kd[d]);kd[d]=null}},y:function(a){Q.depthFunc(a)},Pa:function(a,b){Q.detachShader(S[a],T[b])},ja:function(a){Q.disable(a)},
wa:function(a,b,c){pd(b+c);Q.drawArrays(a,b,c);qd&&Q.bindBuffer(34962,fd[Q.ub])},pa:function(a,b){for(var c=td[a],d=0;d<a;d++)c[d]=C[b+4*d>>2];Q.drawBuffers(c)},xa:function(a,b,c,d){if(!Q.Db){var e=1*ld[c-5120]*b;var g=dd(e);var h=R.yb[g];h?g=h:(h=Q.getParameter(34965),R.yb[g]=Q.createBuffer(),Q.bindBuffer(34963,R.yb[g]),Q.bufferData(34963,1<<g,35048),Q.bindBuffer(34963,h),g=R.yb[g]);Q.bindBuffer(34963,g);Q.bufferSubData(34963,0,E.subarray(d,d+e));d=0}pd(b);Q.drawElements(a,b,c,d);qd&&Q.bindBuffer(34962,
fd[Q.ub]);Q.Db||Q.bindBuffer(34963,null)},ia:function(a,b,c,d,e){Q.drawElementsInstanced(a,b,c,d,e)},l:function(a){Q.enable(a)},p:function(a){R.Bb[a].enabled=!0;Q.enableVertexAttribArray(a)},ra:function(a,b,c,d){Q.framebufferRenderbuffer(a,b,c,hd[d])},z:function(a,b,c,d,e){Q.framebufferTexture2D(a,b,c,jd[d],e)},q:function(a,b){ud(a,b,"createBuffer",fd)},va:function(a,b){ud(a,b,"createFramebuffer",gd)},ua:function(a,b){ud(a,b,"createRenderbuffer",hd)},E:function(a,b){ud(a,b,"createTexture",jd)},Aa:function(a,
b){ud(a,b,"createVertexArray",kd)},la:function(a){Q.generateMipmap(a)},Qa:function(a,b,c,d){a=Q.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ga(a,E,d,b):0;c&&(C[c>>2]=b)},Ra:function(a,b,c){if(c)if(a>=ed)V(1281);else if(a=S[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1;else if(35719==b){if(!a.Pb)for(b=0;b<Q.getProgramParameter(a,35718);++b)a.Pb=Math.max(a.Pb,Q.getActiveUniform(a,b).name.length+1);C[c>>2]=a.Pb}else if(35722==b){if(!a.Nb)for(b=
0;b<Q.getProgramParameter(a,35721);++b)a.Nb=Math.max(a.Nb,Q.getActiveAttrib(a,b).name.length+1);C[c>>2]=a.Nb}else if(35381==b){if(!a.Ob)for(b=0;b<Q.getProgramParameter(a,35382);++b)a.Ob=Math.max(a.Ob,Q.getActiveUniformBlockName(a,b).length+1);C[c>>2]=a.Ob}else C[c>>2]=Q.getProgramParameter(a,b);else V(1281)},Ka:function(a,b,c,d){a=Q.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ga(a,E,d,b):0;c&&(C[c>>2]=b)},La:function(a,b,c){c?35716==b?(a=Q.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),
C[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(T[a]),C[c>>2]=a?a.length+1:0):C[c>>2]=Q.getShaderParameter(T[a],b):V(1281)},ba:function(a){var b=md[a];if(!b){switch(a){case 7939:b=Q.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=vd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||V(1280);b=b&&vd(b);break;case 7938:b=vd("OpenGL ES 3.0 ("+Q.getParameter(7938)+")");break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=vd(b);break;default:V(1280)}md[a]=b}return b},s:function(a,b){return Q.getUniformBlockIndex(S[a],Fa(b))},Ia:function(a,b){b=Fa(b);if(a=S[a]){var c=a,d=c.Hb,e=c.Ic,g;if(!d)for(c.Hb=d={},c.Hc={},g=0;g<Q.getProgramParameter(c,35718);++g){var h=Q.getActiveUniform(c,g);var n=h.name;h=h.size;var m=wd(n);m=0<m?n.slice(0,m):n;var q=c.ic;c.ic+=h;e[m]=[h,q];for(n=0;n<h;++n)d[q]=n,c.Hc[q++]=m}c=a.Hb;d=0;e=b;g=wd(b);0<g&&(d=parseInt(b.slice(g+
1))>>>0,e=b.slice(0,g));if((e=a.Ic[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else V(1281);return-1},Sa:function(a){a=S[a];Q.linkProgram(a);a.Hb=0;a.Ic={}},sa:function(a,b,c,d){Q.renderbufferStorage(a,b,c,d)},Na:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?C[d+4*g>>2]:-1;e+=Fa(C[c+4*g>>2],0>h?void 0:h)}Q.shaderSource(T[a],e)},o:function(a,b,c,d,e,g,h,n,m){if(Q.Wb)Q.texImage2D(a,b,c,d,e,g,h,n,m);else if(m){var q=n-5120;q=0==q?A:1==q?E:2==q?ua:4==q?C:6==q?wa:5==q||28922==
q||28520==q||30779==q||30782==q?Ma:La;Q.texImage2D(a,b,c,d,e,g,h,n,q,m>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else Q.texImage2D(a,b,c,d,e,g,h,n,null)},b:function(a,b,c){Q.texParameteri(a,b,c)},Ha:function(a,b){Q.uniform1f(xd(a),b)},Ca:function(a,b){Q.uniform1i(xd(a),b)},Ba:function(a,b,c){Q.uniform1iv(xd(a),C,c>>2,b)},Ga:function(a,b,c){Q.uniform2f(xd(a),b,c)},Fa:function(a,b,c,d){Q.uniform3f(xd(a),b,c,d)},Ea:function(a,b,c,d,e){Q.uniform4f(xd(a),b,c,d,e)},r:function(a,b,c){a=S[a];Q.uniformBlockBinding(a,
b,c)},Da:function(a,b,c,d){Q.uniformMatrix4fv(xd(a),!!c,wa,d>>2,16*b)},Ja:function(a){a=S[a];Q.useProgram(a);Q.Oc=a},A:function(a,b){Q.vertexAttribDivisor(a,b)},ya:function(a,b,c,d,e){var g=R.Bb[a];Q.ub?(g.Cb=!1,Q.vertexAttribIPointer(a,b,c,d,e)):(g.size=b,g.type=c,g.ec=!1,g.Tb=d,g.Fb=e,g.Cb=!0,g.jc=function(h,n,m,q,r,v){this.vertexAttribIPointer(h,n,m,r,v)})},B:function(a,b,c,d,e,g){var h=R.Bb[a];Q.ub?(h.Cb=!1,Q.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.ec=d,h.Tb=e,h.Fb=g,h.Cb=!0,
h.jc=function(n,m,q,r,v,t){this.vertexAttribPointer(n,m,q,r,v,t)})},K:function(a,b,c,d){Q.viewport(a,b,c,d)},da:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?Nc():Zc(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<W[139265];e==Y.length&&(d?f.tb=Gc(f.canvas,!0,!0,{antialias:1<W[135181],depth:0<W[135173],stencil:0<W[135174],alpha:0<W[135172]}):fc());!f.tb&&d?g=0:(a=new yd(g,a,b,c),
g-1==Y.length?Y.push(a):Y[g-1]=a,Z=a,g=a.id)}return g},P:function(a){a:{if(a=X(a)){a.Vb&&H(a.Vb)(a.id);Y[a.id-1]=null;Z.id==a.id&&(Z=null);for(a=0;a<Y.length;a++)if(null!==Y[a]){a=void 0;break a}f.tb=void 0}a=void 0}return a},M:function(a,b){return(a=X(a))?a.keys[b]:0},V:function(){return 1},m:function(){return ad()/1E3-Bd},ga:function(){Ad||(Ad=Ba(ob("3.2.1 JS WebGL Emscripten")));return Ad},U:function(){return 0},e:function(a){return(a=X(a))?a.Jc:0},fa:function(){if(Y)return 1;Bd=ad()/1E3;W=Cd;
Y=[];Z=null;window.addEventListener("gamepadconnected",Hd,!0);window.addEventListener("gamepaddisconnected",Jd,!0);window.addEventListener("keydown",Kd,!0);window.addEventListener("keypress",Fd,!0);window.addEventListener("keyup",Ld,!0);window.addEventListener("blur",Md,!0);f.canvas.addEventListener("touchmove",Nd,!0);f.canvas.addEventListener("touchstart",Rd,!0);f.canvas.addEventListener("touchcancel",Sd,!0);f.canvas.addEventListener("touchend",Sd,!0);f.canvas.addEventListener("mousemove",Nd,!0);
f.canvas.addEventListener("mousedown",Rd,!0);f.canvas.addEventListener("mouseup",Sd,!0);f.canvas.addEventListener("wheel",Td,!0);f.canvas.addEventListener("mousewheel",Td,!0);f.canvas.addEventListener("mouseenter",Od,!0);f.canvas.addEventListener("mouseleave",Pd,!0);f.canvas.addEventListener("drop",ae,!0);f.canvas.addEventListener("dragover",be,!0);Yc.push(function(a,b){if(Z){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Z.Fc=Z.x,Z.Gc=Z.y,
Z.Ec=Z.width,Z.Dc=Z.height,Z.x=Z.y=0,Z.width=screen.width,Z.height=screen.height,Z.ac=!0):1==Z.ac?(Z.x=Z.Fc,Z.y=Z.Gc,Z.width=Z.Ec,Z.height=Z.Dc,Z.ac=!1):Z.width!=a||Z.height!=b?(Z.width=a,Z.height=b):c=!1;c&&(Zc(Z.width,Z.height,!0),Ud(),Wd())}});return 1},ca:function(){},R:function(){},W:function(a,b){if(a=X(a)){var c=a.Lb;a.Lb=b;b=c}else b=null;return b},ha:function(a){var b=zd;zd=a;return b},Z:function(a,b){if(a=X(a)){var c=a.Mb;a.Mb=b;b=c}else b=null;return b},Y:function(a,b){if(a=X(a)){var c=
a.Rb;a.Rb=b;b=c}else b=null;return b},X:function(a,b){if(a=X(a)){var c=a.Sb;a.Sb=b;b=c}else b=null;return b},_:function(a,b){if(a=X(a)){var c=a.Vb;a.Vb=b;b=c}else b=null;return b},T:function(a,b,c){if(a=X(a))a.x=b,a.y=c},S:function(a,b,c){if(a=X(a))Z.id==a.id&&(b==screen.width&&c==screen.height?Nc():(Oc(),Zc(b,c),a.width=b,a.height=c)),a.Ab&&H(a.Ab)(a.id,b,c)},$:function(a,b){if(a=X(a)){var c=a.Ab;a.Ab=b;b=c}else b=null;return b},N:function(a,b){if(a=X(a))a.title=Fa(b),Z.id==a.id&&(document.title=
a.title)},aa:function(a,b){if(a=X(a))a.Jc=b},Q:function(){},O:function(a){a=Math.abs(a);0==a?$c(0,0):$c(1,a)},ea:function(){window.removeEventListener("gamepadconnected",Hd,!0);window.removeEventListener("gamepaddisconnected",Jd,!0);window.removeEventListener("keydown",Kd,!0);window.removeEventListener("keypress",Fd,!0);window.removeEventListener("keyup",Ld,!0);window.removeEventListener("blur",Md,!0);f.canvas.removeEventListener("touchmove",Nd,!0);f.canvas.removeEventListener("touchstart",Rd,!0);
f.canvas.removeEventListener("touchcancel",Sd,!0);f.canvas.removeEventListener("touchend",Sd,!0);f.canvas.removeEventListener("mousemove",Nd,!0);f.canvas.removeEventListener("mousedown",Rd,!0);f.canvas.removeEventListener("mouseup",Sd,!0);f.canvas.removeEventListener("wheel",Td,!0);f.canvas.removeEventListener("mousewheel",Td,!0);f.canvas.removeEventListener("mouseenter",Od,!0);f.canvas.removeEventListener("mouseleave",Pd,!0);f.canvas.removeEventListener("drop",ae,!0);f.canvas.removeEventListener("dragover",
be,!0);f.canvas.width=f.canvas.height=1;Z=Y=null},h:function(a,b){W[a]=b}};
(function(){function a(e){f.asm=e.exports;ya=f.asm._a;Na();Oa=f.asm.cb;Qa.unshift(f.asm.$a);Za("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return cb().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){k("failed to asynchronously prepare wasm: "+g);x(g)})}var d={a:ee};Ya("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return sa||
"function"!==typeof WebAssembly.instantiateStreaming||$a()||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){k("wasm streaming compile failed: "+g);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.$a).apply(null,arguments)};
var de=f.___errno_location=function(){return(de=f.___errno_location=f.asm.ab).apply(null,arguments)},Ca=f._malloc=function(){return(Ca=f._malloc=f.asm.bb).apply(null,arguments)},$d=f._free=function(){return($d=f._free=f.asm.db).apply(null,arguments)};f._gate_resizeWindow=function(){return(f._gate_resizeWindow=f.asm.eb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.fb).apply(null,arguments)};var Ja=f.stackAlloc=function(){return(Ja=f.stackAlloc=f.asm.gb).apply(null,arguments)};
f.addRunDependency=Ya;f.removeRunDependency=Za;f.FS_createPath=$b;f.FS_createDataFile=bc;f.FS_createPreloadedFile=ec;f.FS_createLazyFile=dc;f.FS_createDevice=O;f.FS_unlink=Qb;var fe;function na(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Xa=function ge(){fe||he();fe||(Xa=ge)};
function he(a){function b(){if(!fe&&(fe=!0,f.calledRun=!0,!za)){f.noFSInit||Yb||(Yb=!0,Xb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?O("/dev","stdin",f.stdin):Pb("/dev/tty","/dev/stdin"),f.stdout?O("/dev","stdout",null,f.stdout):Pb("/dev/tty","/dev/stdout"),f.stderr?O("/dev","stderr",null,f.stderr):Pb("/dev/tty1","/dev/stderr"),Sb("/dev/stdin",0),Sb("/dev/stdout",1),Sb("/dev/stderr",1));Ab=!1;db(Qa);db(Ra);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(ie){var c=a,d=f._main;
c=c||[];var e=c.length+1,g=Ja(4*(e+1));C[g>>2]=Ia(ca);for(var h=1;h<e;h++)C[(g>>2)+h]=Ia(c[h-1]);C[(g>>2)+e]=0;try{var n=d(e,g);cd(n)}catch(m){eb(m)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Sa.unshift(c);db(Sa)}}a=a||ba;if(!(0<Va)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ua();db(Pa);0<Va||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=he;function cd(a){Aa=a;noExitRuntime||0<oa||(Ta=!0);Aa=a;if(!(noExitRuntime||0<oa)){if(f.onExit)f.onExit(a);za=!0}da(a,new na(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var ie=!0;f.noInitialRun&&(ie=!1);he();
